### ISSUE TITLE
not able to upload image in S3 bucket

### ISSUE THREAD

**Issue by anjain** [comfy/comfortable-mexican-sofa#180]
I am using version 1.5.10 of comfortable_mexican_sofa.I added config.upload_file_options = {:url => '/:style/:id/:filename'} in comfortable_mexican_sofa.rb.My application is deployed on heroku.I am getting following error:

Errno::EACCES in CmsAdmin::FilesController#create

Permission denied - /app/public/original

Let me know all settings for s3 bucket in comfortable_mexican_sofa.

**Comment by Momus** [comment]
I am having a similar problem.  When I try to upload a file, the Progress meter stays red and inside:
```ruby
NameError in Comfy::Admin::Cms::FilesController#create 
````
This is my initializier/comfortable_mexican_sofa.rb:
```ruby
  config.upload_file_options = {
    :whiny   =>   false,
    :storage =>   :s3,
    :s3_credentials => {
      "access_key_id" => ENV["S3_ACCESS_KEY_ID"],
      "secret_access_key" => ENV["S3_SECRET_ACCESS_KEY"]
    },
    :bucket => ENV["S3_BUCKET_NAME"],
    :s3_host_name => ENV["S3_HOSTNAME"],
    :path => "uploaded_files/:basename.:extension"
  }
````
and my .env  which is read by heroku's foreman gem to start my dev server:
```ruby
S3_BUCKET=myappdev
AWS_ACCESS_KEY_ID=SOMESTRING
AWS_SECRET_ACCESS_KEY=SOMEOTHERLONGERSTRING
S3_BUCKET_NAME=myappdev
S3_HOSTNAME=s3-website-us-east-1.amazonaws.com
````
On my AWS bucket properties page, I have given full permissions to "Authenticated Users" but I did not enable website hosting.  Is this necessary?

**Comment by corwinstephen** [comment]
@aledalgrande you're a hero
