### ISSUE TITLE
How to handle multiple hostnames

### ISSUE THREAD

**Issue by ghost** [comfy/comfortable-mexican-sofa#183]
Hi,

I'm trying to make a CMS site work on two domains (www.xpto.pt and xpto.pt). In terms of DNS, everything is setup properly. However, on CMS, I can only setup one of them as the hostname. 

I specified xpto.pt and it worked properly while only a single site existed in CMS. When I added a second site, it only works for the exact hostname configured.

Is there a way around this ?

regards,
Ricardo

**Comment by radsimu** [comment]
we set hostname_aliases to make our site work with localhost. And the site loads but all rendered links point to the original hostname, not to localhost. Is there a sollution to making the links point to their localhost version?
