### ISSUE TITLE
Can't mass-assign protected attributes: target_page_id, is_published

### ISSUE THREAD

**Issue by marko-r** [comfy/comfortable-mexican-sofa#191]
With version 1.6.20 I get this error message(see title). When this fields are added as attr_accessible  everything works fine. 

Can someone please fix this?
Thanks!

**Comment by eggie5** [comment]
@tjhanley same here, did you figure it out?

`WARNING: Can't mass-assign protected attributes for Comfy::Cms::Layout: label, identifier, app_layout, content, css, js`

**Comment by GBH** [comment]
Guys, if you're on Rails 4 don't use protected_attributes gem. You have [strong parameters](http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters) now.

If you still need `attr_accessible` on your models you'll need to mix that in or straight up override CMS models.

**Comment by eggie5** [comment]
@GBH ugh your right I still had the gem installed!
