### ISSUE TITLE
Preferred method for ongoing updates to production environment?

### ISSUE THREAD

**Issue by kylebolstad** [comfy/comfortable-mexican-sofa#256]
If an export in a production environment is done first, should it prevent database items from being purged when an import of fixtures from a development environment is run? At least on v1.6.14, this does not seem to be the case.

Is there a preferred method of updating a production database with new/different content? After looking into the issue, I found some text in the Wiki that seems to imply the use of fixtures is not recommended after the initial seeding of content. It would be great to add/change content in a development environment via fixtures (and thus track it through Git) instead of solely relying upon the web admin interface in a production environment.

**Comment by jpbullalayao** [comment]
When you say 'Download db dump and load db locally', do you mean export the production CMS database to files?

**Comment by GBH** [comment]
@jpbullalayao you just do a sql dump. Then load that dump locally and convert it to fixtures.
