### ISSUE TITLE
Multilanguage slugs

### ISSUE THREAD

**Issue by maxcosworth** [comfy/comfortable-mexican-sofa#291]
When using the mirroring feature to create multiple versions of the same site to localize all the content, there's still one caveat: slugs.

I think it'd be nice to have them translated too. Having a look at the code I realise that slugs are the key part when syncing changes between mirrored sites, aren't them?

Anyway, I see the value when creating a new resource, let's say, a page. But once a page is created, and mirrored to the other sites, does it have any sense to continue updating all the other mirrors when making changes to one? Content is intended to be different for each mirror, so... This way we could just allow to edit the slug in one mirror without affecting the others.

Would you accept a pull request to change this behaviour?

**Comment by GBH** [comment]
In 2.0 Site mirroring functionality is gone. Now you can create translations for pages directly. Translations do not have localized slug though. This is something to implement in the future perhaps. Complexity of page lookup and full_path synchronization is pretty high. 

I added this into 2.1 project: https://github.com/comfy/comfortable-mexican-sofa/projects/2
