### ISSUE TITLE
Accessing app object instances?

### ISSUE THREAD

**Issue by polyvision** [comfy/comfortable-mexican-sofa#298]
Hi there,

I'm new to CMS and I really love it. So far, everything works perfect but there's one thing I'm trying to do.

I have a object called @something_str, which I initiate on every request in my application controller. Is there a way to output this string via CMS??

Regards, Alex

**Comment by marr** [comment]
I'm new to rails & comfy, and was hoping to ask a similar question above. It may be that helpers are the answer, but here is my scenario:

I built a route outside of the cms which renders a table from some API calls using a module I wrote. I want to use this route inside a cms page/snippet. Its kind of like this, but the opposite direction: https://github.com/comfy/comfortable-mexican-sofa/wiki/Accessing-cms-content-from-the-app. Ie, i'd like to access app content from the CMS.

Any examples, guidance on how to do that? Will appreciate low complexity rails solutions.

**Comment by Daniel-ltw** [comment]
@marr does your app have an api for the CMS to query?

**Comment by marr** [comment]
@Daniel-ltw Yes, by way of a module. The model that queries it is what I'd like to display. Currently I have a simple deploys_controller:
```
class DeploysController < ApplicationController
  # GET /deploys
  def index
    @deploys = Deploy.all
  end
end
```
And my view:
```
%h1 Latest deploys
= render "deploys"
%br
```
And partial:
```
%table.table.table-hover
  %thead
    %tr
      %th Project
      %th Time ago
      %th Revision
      %th Username

  %tbody
    - @deploys.each do |deploy|
      %tr
        %td= deploy.project
        %td= time_ago_in_words(deploy.completed_time)
        %td= link_to deploy.revision, "https://rollbar.com/deploy/#{deploy.id}"
        %td= deploy.username
```
I'd really just like to display that partial that corresponds to the deploy_controller's `index` route inside a page somewhere in the CMS.

**Comment by marr** [comment]
I do see this path listed in the routes that I could hopefully use:
`*deploys_path*	GET	/deploys(.:format)	deploys#index`

I am trying to make a helper so I could use `{cms:helpers:deploys}` like so:
```
module DeploysHelper
  # how to render deploys_path here??
end
```
obviously i'm missing something.

**Comment by marr** [comment]
So I ended up adding a file `app/controllers/comfy/cms/content_controler.rb` like this:
```
class Comfy::Cms::ContentController < Comfy::Cms::BaseController
  def show
    @deploys = Deploy.all
  end
end
```
Then I was able to use the Tag: `{cms:partial:deploys/deploys}`. I feel its not really the best way, but its the only way I know at the current time. Any improvements people can suggest?
