### ISSUE TITLE
couldn't find file 'jquery-ui'

### ISSUE THREAD

**Issue by spheregenomics** [comfy/comfortable-mexican-sofa#308]
Had some trouble getting this gem to work an existing app, so generated a basic rails app with a single model scaffold, then installed comfortable-mexican-sofa as per the instructions (added the gem and ran the installer). I still get the same error.

It cannot find jquery-ui in the gem for some reason.

Sprockets::FileNotFound in Cms_admin/sites#new

Showing /Users/sean/.rvm/gems/ruby-1.9.3-p327/gems/comfortable_mexican_sofa-1.8.1/app/views/layouts/cms_admin/_head.html.haml where line #8 raised:

couldn't find file 'jquery-ui'
  (in /Users/sean/.rvm/gems/ruby-1.9.3-p327/gems/comfortable_mexican_sofa-1.8.1/app/assets/javascripts/comfortable_mexican_sofa/application.js.coffee:3)

**Comment by marcamillion** [comment]
I am having this same issue too with gem version 1.8.5.
