### ISSUE TITLE
possible integration of ckeditor

### ISSUE THREAD

**Issue by gretel** [comfy/comfortable-mexican-sofa#321]
to prevent me from re-inventing the wheel - i would love to have https://github.com/tsechingho/ckeditor-rails as an option for a rich-text editor: somebody done that before? regards

**Comment by zeeshan-za-ahmad** [comment]
hi
i Tried this https://github.com/comfy/comfortable-mexican-sofa/wiki/Replacing-default-wysiwyg-editor-with-redactor
but its not working.
I am on rails gem 'rails', '4.2.7.1'  and want to use any of these  gem 'tinymce-rails'
gem 'ckeditor_rails'  ,please update wiki.
I prefer ckeditor wiki.

I also found this but its empty. :( 
https://github.com/comfy/comfortable-mexican-sofa/wiki/Replacing-default-wysiwyg-editor-with-tinymce/f2346011699ccdc938f88f2cb47e5dd5e11c65c2
https://github.com/comfy/comfortable-mexican-sofa/issues/595
Please help how to integrate  gem 'ckeditor_rails'   with  @GBH your awesome  CMS.

Thanks
