### ISSUE TITLE
fresh_fixture?(object, file_path) function always returns true?

### ISSUE THREAD

**Issue by ChrisGF** [comfy/comfortable-mexican-sofa#368]
I have been tracing through the code and it appears that the fresh_fixture function will always return true.

It looks like the importer has the concept of a force option, but the "force" option to the string force.  Then the function returns the string force which is interrupted as a true statement by the rest of the code.   

```
ComfortableMexicanSofa::Fixture::Importer.new(from, to, :force).import!
```

Is there a way not to force the import of old fixtures?

**Comment by GBH** [comment]
Fixtures (or CMS Seeds rather) are completely rewritten. This bug should be gone... but maybe some others added.
