### ISSUE TITLE
Categories are lost on changed file when using fixtures

### ISSUE THREAD

**Issue by toadle** [comfy/comfortable-mexican-sofa#399]
Another issue I found, when using fixtures: 
I got a page **imprint** that has the following `attributes.yml`.

```

---
label: Impressum
layout: content
parent: index
target_page: 
categories:
- footer
is_published: true
position: 7
```

The category `footer` is used to display the page only in the footer. 
Now, when changing imprint's content in the content.html, that category is lost. 

However: You can restore it by edititing its `attributes.yml` and reloading the page. I suppose the file is imported again in that instance.

**Comment by GBH** [comment]
Fixture (Seed) attributes are merged with the rest of the content. Different approach so this issue should not be a thing anymore,
