### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by calas** [comfy/comfortable-mexican-sofa#43]
**Just to note**, I've started a branch for UI and controller messages translation since I need it for Spanish clients, It's weird to see a Mexican sofa that doesn't speak Spanish. 

A first string extraction can be found in https://github.com/calas/comfortable-mexican-sofa/tree/feature/i18n 

Contributions, suggestions and blames are welcome on that branch 

I'll make a pull request once I'm done. 

Ideas I have: 
- Create one/some helper(s) for translations, something like `cms_t(:app_layout)` that handles scopes, fallbacks and default values. 
- Update the form helpers to automatically translate field labels (I see no testing on the helper methods :-X )

**Comment by forever-sumit** [comment]
Hi Guys,
I want to show the cms content in different languages.
my url will be 
http://www.example.com (For English)
http://www.example.com/zh-CN (for Chinse)

I've looked on your conversation but I didn't find find a way to how I do that.
the only solution is that I need to create a page for `/zh-CN` but I don't think its a good solution.
Beacuse my client need to create many pages and its very tough to create each page for each supported language.

and from the cms content if we go to the dynamic content page then we have no option to get which locale we have in cms content to show the dynamice content page.

So if you understand what I want. could you suggest to me the way to do.
