### ISSUE TITLE
Custom locales support

### ISSUE THREAD

**Issue by Chmarusso** [comfy/comfortable-mexican-sofa#435]
I tried to put own translations in view: `app/views/layouts/application.html.erb`

Rails way of doing this simply doesn't work. App is keep taking translations from wrong locales yml file, even when locale parameter is set straightforward. 

I am really confused, because following application controller is not setting proper locales:

```
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception 
    before_filter :set_locale

    private 

    def set_locale
        I18n.locale = "en"
    end
end
```

After refreshing browser entry `t(:main_website)` renders string from `pl.yml` file, not from `en.yml`

**Comment by williamn** [comment]
Hi guys @Chmarusso @GBH 

Is it possible to use `set_locale`? For example if I want to set locale bashed on `params[:locale]`?
