### ISSUE TITLE
cms_manageable.rb tags accessor

### ISSUE THREAD

**Issue by Emerson** [comfy/comfortable-mexican-sofa#442]
```
def tags(force_reload = false)
  self.render if force_reload
  @tags ||= []
end
```

The force reload can cause issues when working with initialized (but unsaved) blocks. It's called by the `block.rb#tag` method.

Might be a non-issue, but we should investigate.

**Comment by GBH** [comment]
As of 2.0 Tag parsing system is completely redone. Page does not have `tags` method anymore.
