### ISSUE TITLE
Errors with Multithreaded Server (Puma)

### ISSUE THREAD

**Issue by jume-dev** [comfy/comfortable-mexican-sofa#461]
Hi,
i declared a partial, which includes some javascript files. I also use puma, cause i want to use some streaming via ActionController::Live.

But some of these assets gets served with their HTTP header in the file, which isn't correct javascript and fails.

I tested various things, but came to the conclusion that comfortable-mexican-sofa seems to be the problem.

Do you have any ideas for this problem?

(made also a stackoverflow questien http://stackoverflow.com/questions/23758264/http-header-in-javascript-files-with-puma-on-development)

**Comment by GBH** [comment]
Gonna close this one as it's more of a Rails/Puma issue.
