### ISSUE TITLE
Compatibility with jquery-ui-rails 5.0.0

### ISSUE THREAD

**Issue by dinatih** [comfy/comfortable-mexican-sofa#485]
Hello, we got a :

```
Sass::SyntaxError at /cms-admin/sites/1/pages
File to import not found or unreadable: jquery.ui.all.
```

with last version of jquery-ui-rails  (5.0.0)

> 5.0.0
> Update to jQuery UI 1.11.0
> Rename jquery.ui._.{js,css} to jquery-ui/_.{js,css}
> Add jquery-ui.js and jquery-ui.css assets

Because of changed names.

**Comment by marcamillion** [comment]
Thank you @laertiades. Your workaround saved my bacon!
