### ISSUE TITLE
Using views/layouts/application.haml as the layout

### ISSUE THREAD

**Issue by mmustala** [comfy/comfortable-mexican-sofa#494]
Hi,
https://github.com/comfy/comfortable-mexican-sofa/wiki/Layouts says that I should select "App Layout" to use my current defined layout file with the cms. But I cannot see anything labelled with "App Layout" when I'm creating my first layout for a fresh site.

I'm using the newest gem version 1.11.2 and my rails version is 4.1.0

In my layouts directory there is two files, application.haml and mailer.haml

Should I use "Upload Files" button located in the upper right corner to upload my layout file or how should this work?

**Comment by dam13n** [comment]
@mmustala's answer worked for me (and I'm using slim)
