### ISSUE TITLE
File/PageFile tags file_name specs not compatible with Comfy::Cms::File.file_file_name validation

### ISSUE THREAD

**Issue by masda70** [comfy/comfortable-mexican-sofa#507]
Right now tags for files are formatted this way:

`{{ cms:file:file_name.ext }}`

However, file_name.ext has to match, for both File and PageFile tags the following regex:

`IDENTIFIER_REGEX  = /\w+[\-\.\w]+\w+/`

This is not compatible with the file name validation in Comfy::Cms::File

`validates :file_file_name,
    :uniqueness => {:scope => [:site_id, :block_id]}`

which allows a wide array of filenames (e.g. spaces, and unicode characters).

You can test this by adding files with names like "Têst.png" and "he llo.jpg"

**Comment by GBH** [comment]
As of 2.0 tag system is overhauled and there's no more Paperclip (using ActiveStorage)
