### ISSUE TITLE
Collection tag - formatting and translation

### ISSUE THREAD

**Issue by duart** [comfy/comfortable-mexican-sofa#548]
Hi,
When using collection tag I found that:
- I'm not able to translate the text "----- Select .... ------" that comes from lib/comfortable_mexican_sofa/form_builder.rb
- generated html select has no class so bootstrap formatting is not applied

How would you suggest to solve this problems (even quick fix would be helpfull) ?

**Comment by asgeo1** [comment]
Having the same problem.

You would have to patch the form-builder for `collection` method:

https://github.com/comfy/comfortable-mexican-sofa/blob/master/lib/comfortable_mexican_sofa/form_builder.rb


But perhaps it should be getting a few more values from the collection tag class (https://github.com/comfy/comfortable-mexican-sofa/blob/master/lib/comfortable_mexican_sofa/tags/collection.rb)

I.e.

  - select_text   ("--- Select tag_class ---")
  - select_css_class  ("select")
  - label_text    ("tag_class.titleize")

**Comment by GBH** [comment]
Closing. Will be dealt with in #587
