### ISSUE TITLE
page_files may "overload" regular files

### ISSUE THREAD

**Issue by glance-** [comfy/comfortable-mexican-sofa#550]
Example:
In a layout you have `{{ cms:file:logo.png:image }}`. You upload a logo.png as a file and everything is great.

You add a `{{ cms:page_file:logo:image }}` in a layout, and to a page using that layout uploads another logo.png.

Then when redering the `{{ cms:file:logo.png:image }}` its roulette which of the two logo.png's urls will get rendered into that page.

I suggest making the `:file_file_name` constrained to being unique, and implementing a "rename" of sorts on the server, as suggested in #496

**Comment by asgeo1** [comment]
@schneikai - that's awesome. Exactly what I was looking for.

I've only just got started with Comfy, and had been completely confused between the difference between the `file` tags and the `page_files` tags.  (It didn't help that the wiki pages for "files" is blank :-/)

I couldn't work out why Comfy would have a "Files" controller to upload files into, but then not have a "file picker" widget so the user could pick one of those files.

Please guys, get the image picker implemented in Comfy!

It would be awesome if the file/image picker was also be integrated with TinyMCE, so when you go to pick an image, you can pick an image from the "media library".

**Comment by schneikai** [comment]
I added this to TinyMCE too. When you insert a image you now see a little browse button behind the source field. http://cl.ly/image/1S0j0v1Y0T0Q Clicking this opens the files library to select a file.

I opened a discussion on Google Groups to discuss this change because it doesn't really fit in this issue ;) https://groups.google.com/forum/#!topic/comfortable-mexican-sofa/2HHxFrwaC5w

**Comment by GBH** [comment]
As of 2.0 Files that you attach to the Page Fragments are completely separate from the rest of the files. There's no more danger of accidentally overwriting stuff.
