### ISSUE TITLE
Render a CMS page fails for localhost:3000 when using hostname_aliases

### ISSUE THREAD

**Issue by Onumis** [comfy/comfortable-mexican-sofa#555]
Trying to do `render cms_page: '/contacts/thanks'` in a controller gives me: `ComfortableMexicanSofa::MissingSite (Cannot find CMS Site with identifier: au.lvh.me//calculator):`

This is the AR request:

```
(0.7ms)  SELECT COUNT(*) FROM "comfy_cms_sites"
  Comfy::Cms::Site Load (0.5ms)  SELECT "comfy_cms_sites".* FROM "comfy_cms_sites"  WHERE "comfy_cms_sites"."hostname" = 'au.lvh.me'
```

It's looking for the hostname that comes in the request without checking for aliases. I think its this line here: https://github.com/comfy/comfortable-mexican-sofa/blob/master/lib/comfortable_mexican_sofa/render_methods.rb#L48

It works fine in the live site.

I can work around with this:

`render cms_page: '/contacts/thanks', cms_site: (Rails.env.development? ? 'the-site-identifier' : nil)`

**Comment by GBH** [comment]
There was a PR that changes how site is loaded. Hopefully this issue goes away.
