### ISSUE TITLE
"Site not found" error in custom routes

### ISSUE THREAD

**Issue by phuong3030** [comfy/comfortable-mexican-sofa#558]
Hi,
I used cucumber, capybara, selenium in testing. When i expect redirect to admin area after user logged in (/admin routes), it returned "Site not found" error. I don't know why it happened because i have already defined my custom /admin route. How do i fix this? Thank you.
My route.rb    

```
#Admin panel routes
get '/admin' => 'admin/core#index', :as => 'admin_root'
get '/admin/login' => 'admin/core#login', :as => 'admin_login'
get '/admin/logout' => 'admin/core#logout', :as => 'admin_logout'

#Make sure this routeset is defined last
comfy_route :cms_admin, :path => '/admin/cms'
comfy_route :cms, :path => '/', :sitemap => false
```

Capybara log error
    Scenario: User logins successful            # features/admin/authen.feature:11
    Given I exist as a admin user         # features/step_definitions/admin/authen_steps.rb:15
    And I'm not logged in                     # features/step_definitions/admin/authen_steps.rb:19
    When I login with the valid credentials  # features/step_definitions/admin/authen_steps.rb:33
    Then I should be redirected to admin area # features/step_definitions/admin/authen_steps.rb:60
    Site Not Found (ActionController::RoutingError)

**Comment by danieldekay** [comment]
Can you give details on your solution?

**Comment by phuong3030** [comment]
@danieldekay: I've just wanted to create dashboard page in admin area. So I create get '/admin' => 'admin/core#index', :as => 'admin_root' as you saw. I extended my class from Comfy::Admin::Cms::BaseController. Because i don't want this controller check cms data for every action so use skip action to disable load_admin_site and fixture action. You can see more detail in https://github.com/comfy/comfortable-mexican-sofa/wiki/Reusing-sofa%27s-admin-area
