### ISSUE TITLE
Replace Paperclip with CarrierWave

### ISSUE THREAD

**Issue by GBH** [comfy/comfortable-mexican-sofa#56]
Seems a bit cleaner plus gives a class that should be easy to override.
Before that CW needs to be patched up to have CarrierWave::ImageMagick processor. Should be able to talk to imagemagick directly (just like Paperclip)

**Comment by Daniel-ltw** [comment]
Could we re-open this ticket? 

I have notice that imagemagick will become a major problem with the CVE that it has. 

If Dragonfly do support other lib, rather than imagemagick, then we could also consider that. 

Paperclip only does imagemagick.

**Comment by GBH** [comment]
what's the alternative to imagemagick these days?

**Comment by Daniel-ltw** [comment]
Like what @benvds mentioned, those would be the alternatives.

**Comment by GBH** [comment]
you mentioned vulnerabilities in imagemagick. so what's the alternative to that? Rmagick and minimagick are just wrappers on top of that, no?

**Comment by Daniel-ltw** [comment]
I guess with a simple search so far, graphicsmagick seems to be the best alt to imagemagick. 

Here are some CVE details to both library:
http://www.cvedetails.com/product/4903/Graphicsmagick-Graphicsmagick.html?vendor_id=2802
http://www.cvedetails.com/vendor/1749/Imagemagick.html

And I guess finding a ruby image/file processing gem that uses alternative library might be hard too, but should be something that needs exploring.
