### ISSUE TITLE
Moving extensions to concerns

### ISSUE THREAD

**Issue by ghost** [comfy/comfortable-mexican-sofa#562]
Hello @GBH,

I was wondering if the code within lib/confortable_mexican_sofa can be refactored to concerns:

extensions/acts_as_tree.rb
extensions/cms_manageable.rb
extensions/has_revisions.rb
extensions/is_categorized.rb
extensions/is_mirrored.rb
render_methods.rb

Do you think this is something relevant to the current project goals?

Kindly,

Rafael

**Comment by GBH** [comment]
Yeah, that makes sense. It used to be a Rails 3.0 codebase, so you had no `concerns` folder before.

**Comment by lememora** [comment]
Alright, let's evolve. I will work on it and send you a pull request later. Thanks.

**Comment by GBH** [comment]
Categorizations and old cms_manageable are concerns now. as_as_tree and has_revisions have configuation options, so they are kinda awkward as concerns. Refactor is welcome as PR.
