### ISSUE TITLE
Problem with generating page#full_path when site has path

### ISSUE THREAD

**Issue by Ynnni** [comfy/comfortable-mexican-sofa#563]
I need to build a multilang site. I'm using site#path as a site locale. The problem is the pages have wrong full_path (/something) while their ulrs are woking properly (//hostname.com/locale/something). I can resolve my problem with a usage of page#url for the inner site pages, but i think this is a wrong way and page_path is need to be fixed.

**Comment by GBH** [comment]
I guess the issue is that you `page.full_path` makes wrong links if site has a path. `page.full_path` is an accessor that can be modified. I'll try that.
