### ISSUE TITLE
Incompatibility with will_paginate

### ISSUE THREAD

**Issue by jaroslawr** [comfy/comfortable-mexican-sofa#565]
We use comfortable_mexican_sofa at our project, and also use will_paginate for pagination. Unfortunately after updating the cms gem recently some functionalities break with the error:

```
undefined method `per' for #<ActiveRecord::AssociationRelation::ActiveRecord_AssociationRelation_Comfy_Cms_File:0x007fdc96ec7d70>
```

This is because will_paginate overwrites .page(). I think it would be nice if the CMS was agnostic to the paginator choice, and this can be easily fixed by using Kaminaris functionality to use a different method than .page():

```
changing page_method_name

You can change the method name page to bonzo or plant or whatever you like, in order to play nice with existing page method or association or scope or any other plugin that defines page method on your models.
```

I can issue a pull request if you guys would be fine with using, say, .on_page() instead of .page().

**Comment by GBH** [comment]
Yeap. I figured it would be a problem. Issue is that you probably shouldn't have 2 different paginators in your app. I think I'll create a `comfy_page` wrapper and call proper methods depending what you have installed. Will remove dependency from the gemspec too. 

Super annoying though.
