### ISSUE TITLE
Replacing tinyMCE with Redactor in the core

### ISSUE THREAD

**Issue by GBH** [comfy/comfortable-mexican-sofa#567]
[Redactor](http://imperavi.com/redactor/) is pretty awesome. Easy to extend, has good image management that integrates with Sofa pretty much out of the box. However the license costs [$499](http://imperavi.com/redactor/download/) if I want to embed it into this project. License is permissive enough too, which is nice. Basically you'd get a $99 value just by using this CMS.

I'm not getting paid enough to buy it. Is there a non-shitty, visible way to collect that money?

**Comment by GBH** [comment]
Thanks @nasmorn !
Redactor is in. Just released 1.12.5 with it bundled.
Left you props in README and release notes.

**Comment by Emerson** [comment]
Awesome! @nasmorn :+1: :trophy:

**Comment by espen** [comment]
🌟@nasmorn🌟 👍👍🙏
