### ISSUE TITLE
Ability to use a custom layout for the admin pages

### ISSUE THREAD

**Issue by asgeo1** [comfy/comfortable-mexican-sofa#570]
Can we please add a `config.admin_layout` property, so we can change which layout is used to render the admin section?

Currently it is hard coded to `comfy/admin/cms`

I have a different layout which I want to use.

My workaround is currently to monkey patch in `config/initializers/comfortable_mexican_sofa.rb`, which is a bit of a pain:

    require_dependency ComfortableMexicanSofa::Engine.root.join('app', 'controllers', 'comfy', 'admin', 'cms', 'base_controller').to_s
    
    class Comfy::Admin::Cms::BaseController < ComfortableMexicanSofa.config.base_controller.to_s.constantize
      layout 'my_admin_layout'
    end

**Comment by GBH** [comment]
If you really want to override CMS admin layout, what you're doing is the way to go. Just pointing it to some template won't work. Need to re-link js and partials anyways. 

Didn't try it, but this might be cleaner?
```ruby
Comfy::Admin::Cms::BaseController.class_eval do
  layout 'my_admin_layout'
end
```
