### ISSUE TITLE
Is there anyway to default a page boolean/checkbox field to checked?

### ISSUE THREAD

**Issue by asgeo1** [comfy/comfortable-mexican-sofa#572]
Is there anyway to default a page boolean/checkbox field to checked?

**Comment by pierrebeitz** [comment]
as of now i believe there is no such possibility. 
if you are willing to do a bit of work yourself have a look at #474. I almost finished the integration of rails_bootstrap (the only bug being that i broke the form_blocks method and thus the changing of a page layout via ajax.) unfortunately i will not be able to finish this till the end of february. yet i think there is not much work to be done with (hopefully) only the ajax-functionality left. the failing test should guide into the right direction.

**Comment by GBH** [comment]
I have an idea how to completely restructure tags so it should be easy to do things like that.I'll take a stab at it this weekend.

**Comment by GBH** [comment]
Closing. Part of #587
