### ISSUE TITLE
Label for some field types (boolean, collection) does not "link" to their respective form element (i.e. using `for` and `id` attributes)

### ISSUE THREAD

**Issue by asgeo1** [comfy/comfortable-mexican-sofa#573]
The label for some field types (boolean, collection) does not "link" to their respective form element (i.e. using `for` and `id` attributes).

I found that a bit annoying, as personally I always click the labels when I want to select a form field.

**Comment by pierrebeitz** [comment]
would also be fixed with #474. (see #572)

**Comment by GBH** [comment]
Closing, as it will be part of #587
