### ISSUE TITLE
"Upload Files" is not shown in my app's admin page

### ISSUE THREAD

**Issue by 5t111111** [comfy/comfortable-mexican-sofa#574]
After I create an app following "Installation" instruction, "Upload Files", which you can see in [screenshots](https://raw.githubusercontent.com/comfy/comfortable-mexican-sofa/master/doc/preview.png) on README, is not shown on the right side in my app's admin page. There isn't language selector, either.

**Comment by GBH** [comment]
In new version files widget got moved. Now you can find it as a burger button for Files on the left nav.

Language selector shows up when you have multiple mirrored sites.

I'll close this issue when I update the screenshots.

**Comment by 5t111111** [comment]
Ah ok, I see, that would be fine. Thanks for your answer.
