### ISSUE TITLE
add more info and usability to edit pages with file uploads

### ISSUE THREAD

**Issue by andywenk** [comfy/comfortable-mexican-sofa#577]
I have created a pull request in our fork for cms-fortress where I overwrite `app/views/comfy/admin/cms/files/_page_form.html.haml` . The usability to open the image in a new tab, having no info about the picture and no response if the image has been deleted is not the best. So this is a feature request. The code is simple and can be found in the before mentioned branch at 

https://github.com/sumcumo/cms-fortress/commit/89ee2379fba0e8dfec7b540526e9b7f8b4a22123

If this is something you also want to have in comfy, I am happy to send a PR.

Thanks and all the best

Andy

**Comment by GBH** [comment]
Definitely a good improvement. PR would be great.

**Comment by andywenk** [comment]
cool - I try to send the PR this weekend ;-)

**Comment by GBH** [comment]
I opted for leaving UI as it for the moment. But you uncovered a js bug that made deleted elements not go away. Also hovering over page file items now will show a popover with image thumb (only for images). 

So same idea, only more compact.
