### ISSUE TITLE
Sprockets::FileNotFound in Comfy::Admin::Cms::Base#jump

### ISSUE THREAD

**Issue by zlu** [comfy/comfortable-mexican-sofa#578]
ruby 2.1.2
rails 4.1.9
comfy 1.12.5

![screen shot 2015-01-18 at 15 27 36](https://cloud.githubusercontent.com/assets/20940/5794542/f61e97b6-9f26-11e4-80ed-5ff3dcd1ea4e.png)

**Comment by GBH** [comment]
Thanks. Should be fixed now. No idea why it didn't pop up for me.
