### ISSUE TITLE
Redactor doesn't show in all languages

### ISSUE THREAD

**Issue by espen** [comfy/comfortable-mexican-sofa#581]
Sofa uses "nb" for Norwegian. Redactor uses "no_NB". Might be other that differ as well.

This causes Redactor not to show as it results in a JavaScript error about the language setting.

How to solve this? Use the same language code as Redactor? Specify "admin.cms.redactor_language" in each language file?

Reference: http://imperavi.com/redactor/docs/languages/

**Comment by GBH** [comment]
I think it's just matter of changing this: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/javascripts/comfy/admin/cms/lib/redactor/i18n/nb.js#L2

**Comment by espen** [comment]
Well that means that each language file has to be manually edited each time Redactor updates the affected language files for this issue. I assume every language not using two chars as language code is affected by this issue. Looks like 4 languages from what I can see.

My suggestion is that the comfy locale file has an attribute for the language used in Redactor. Fallback if needed can be the current locale in Comfy.

**Comment by GBH** [comment]
I think it's far easier to change what Redactor uses as key for locales.

**Comment by GBH** [comment]
Just to clarify: I want to follow naming convention of locales as they appear here: https://github.com/svenfuchs/rails-i18n
