### ISSUE TITLE
Using Redactor plugins

### ISSUE THREAD

**Issue by alxppp** [comfy/comfortable-mexican-sofa#586]
Thanks for the last update - the Redactor editor is great!

I would like to include Redactor's font color plugin into my app (http://imperavi.com/redactor/plugins/font-color/).

Is there a way to do this without changing *assets/javascripts/comfy/admin/cms/base.js.coffee*?

Best,
Alex

**Comment by GBH** [comment]
Absolutely. 

Step 1: Create a file: `app/assets/javascripts/comfy/admin/custom.js.coffee` (`rails g cms` will create it for you)
Step 2. Paste this method in: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/javascripts/comfy/admin/cms/base.js.coffee#L38
Step 3. Change / add whatever you want.

**Comment by alxppp** [comment]
Thanks for your quick reply!

Do I need to import this file somewhere? I added a console.log in the *app/assets/javascripts/comfy/admin/custom.js.coffee* file and it is not executed when visiting an admin page.

Also, when pasting the method from base.js.coffee that you mentioned, changes won't affect the Redactor editor (e.g. disabling the show HTML button).

**Comment by GBH** [comment]
Sorry, wrong path. You basically replacing this file: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/javascripts/comfy/admin/cms/custom.js.coffee

**Comment by alxppp** [comment]
Yes, this path is working now. Thanks!

Which location would you recommend for placing further Redactor plugins? I tried `javascripts/comfy/admin/cms/lib/redactor/fontcolor.js`, but it's not loaded in the browser; even when requiring the file explicitly with `#= require comfy/admin/cms/lib/redactor/fontcolor` in `custom.js.coffee`

**Comment by GBH** [comment]
Requiring things from custom.js should totally work. I'll need to try it out.

If you required it and it doesn't blow up see the page html source, that js file should be linked.

**Comment by andywenk** [comment]
@GBH I did exactly this with the underline and bufferbuttons plugin. Works like a charm. 

@alxppp as an example - in your application in `app/assets/javascripts/comfy/admin/cms/custom.js.coffee` add this:

    //= require comfy/admin/cms/lib/underline
    //= require comfy/admin/cms/lib/bufferbuttons

And then add the plugins with name underline.js and bufferbuttons.js in `app/assets/javascripts/comfy/admin/cms/lib`
