### ISSUE TITLE
Improving tag system.

### ISSUE THREAD

**Issue by GBH** [comfy/comfortable-mexican-sofa#587]
CMS tags meant to be simple tokens that get replaced with text on the way out. So they are simple, but at the same time rather restrictive and not so easy to change how they behave. So current tag system needs to be replaced. The goal is to increase clarity, decrease complexity and add flexibility to change things.
##### Syntax change.

Right now we have tags like `{{cms:page:identifier:text}}`, `{{cms:page:identifier:string}}`, `{{cms:field:identifier:rich_text}}` and so on. There are distinct, yet almost identical classes for those. This is a bit nuts. Now all tags that deal with data collection on the admin side will have signature of `{{cms:block:identifier}}`. Details like how they are presented on the admin side and how they are rendered out will be handled via attributes. Instead of doing this odd delimitering everything with a column, we will have something JSON-like: `{{cms:block:identifier format:string, placeholder:'Hello world', foo:bar, etc:etc}}`. No more magical "4th token means partial path" bullshit. Also sorry about [Collection Tag](https://github.com/comfy/comfortable-mexican-sofa/wiki/Tags#collection), it's awful.
##### Admin forms.

In the back there will be some sort of delegation class that will render a proper partial for the admin area. It will take into consideration options on the tag. Right now it's handled by a form helper and it's pretty annoying to override, or add anything custom.
##### Rendering

Right now rendering logic is defined in each Tag class. Something similar still will be in place.
##### When

Soon. Maybe in 1.13.0. I'll need a number of weekends to get it ready. There's still planned work for retiring Site mirroring for a better system, but that one is pretty hard.

I won't keep the old format of tags and most likely rollout this change as a minor version. Sorry SemVer people. You'll have to change tag definitions everywhere. But everything will work the same then.

I made a branch: https://github.com/comfy/comfortable-mexican-sofa/tree/cms_block_tag It's all broken at the moment, but I got options parser working.

**Comment by pierrebeitz** [comment]
as written in some other issues: 
have a look at https://github.com/pierrebeitz/comfortable-mexican-sofa/commits/feature/tag-rewrite. in those last 4 commits i basically did exactly this while being backwards-compatible with the old system, so there is some cleanup-work to be done. 

at least i want to point at [page_tag.rb](https://github.com/pierrebeitz/comfortable-mexican-sofa/blob/feature/bootstrap-tags/lib/comfortable_mexican_sofa/tags/page_tag.rb#L7), where "(field_helper)[https://github.com/pierrebeitz/comfortable-mexican-sofa/blob/feature/bootstrap_tags/lib/comfortable_mexican_sofa/tags/page_tag.rb#L17]" is meant to match to the methods provided by rails_bootstrap. 
From there things are passed to the [form_builder](https://github.com/pierrebeitz/comfortable-mexican-sofa/blob/feature/bootstrap-tags/lib/comfortable_mexican_sofa/form_builder.rb#L54) which swaps argument-indices for methods where this is needed. for example: 
```{{ cms:page:content:select( ["option1", "option2"], {"label": "my_label"} ) }}
``` where the first argument is not the usual hash, but an array of options. 

i hope [this](https://github.com/pierrebeitz/comfortable-mexican-sofa/commits/feature/bootstrap-tags) may help you in any way.

**Comment by GBH** [comment]
Thanks @pierrebeitz, I'll look over what you have. Especially the form builder stuff.

**Comment by pierrebeitz** [comment]
just updated my comment again

**Comment by schneikai** [comment]
I want to put my vote up for http://liquidmarkup.org/ again :)
It has a extendable tag syntax https://github.com/Shopify/liquid/wiki/Liquid-for-Programmers#create-your-own-tags and you can do more dynamic stuff in the templates like if-else or loops. For example you could remove the collection tag completely and use a loop inside the template.

**Comment by GBH** [comment]
Liquid is neat an all, but it deals with presentation. Current tag system deals with how data is presented when rendered and also how data is collected on the admin side (and that includes tag expansion). I'm sure it might be possible to force Liquid to do that but I'd rather not.

**Comment by schneikai** [comment]
This can be done by creating different tags for the frontend and admin like this:

```ruby
# When in frontend we want to render a tags content:
class CmsField < Liquid::Tag
  def initialize(tag_name, name, tokens)
    super
    @name = name
  end

  def render(context)
    # find content for field name however this is done
    content.find_by_field_name(@name)
  end
end

Liquid::Template.register_tag('cms_field', CmsField)

@template = Liquid::Template.parse(" {% cms_field headline %}")
@template.render # => "foo"


# When the same template is parsed in the backend you just switch the tag class and render a input field instead of the tags content:
class CmsFieldAdmin < Liquid::Tag
  def initialize(tag_name, name, tokens)
    super
    @name = name
  end

  def render(context)
    # Instead of the rendering the content show a input field
    @template.send('text_field_tag', @name)
  end
end

Liquid::Template.register_tag('cms_field', CmsFieldAdmin)

@template = Liquid::Template.parse(" {% cms_field headline %}")
@template.render # => '<input name="headline" />'
```

**Comment by schneikai** [comment]
Drops let you access your Rails Models (any object actually) in a save way from a Liquid template. This could be very nice too!!! Imaging a list of users with a attribute if they are your companies staff. You could use this list on a about page to show a list of all users who work at the company.

**Comment by schneikai** [comment]
In the end Liquid is just a token parser. What it does with the tokens is completely up to you.
I think Comfy could be much more powerful with a template language such as Liquid.

**Comment by GBH** [comment]
Ok, I'll read up on this liquid thing and see how I can integrate it. Maybe it's not as bad as I imagine it to be.

**Comment by GBH** [comment]
One thing that I can't figure out. I need to be able to nest tags. Meaning that rendered content can have tags that need to be expanded as well. So currently, parsing and rendering are basically the same process. So how would I hack that functionality into `Liquid::Template.parse`?

Besides this little problem, Liquid should be easy to integrate.

**Comment by schneikai** [comment]
You mean for the nested layouts? Maybe when pulling the content in, run it through Liquid too if the tags content supports Liquid too?

**Comment by GBH** [comment]
Good news that output of `parse` can be modified easily. It's possible to detect and expand cms tags this way. Unfortunately Liquid is won't allow tags like `{% cms:block:identifier key:value%}` Options still need to be parsed out by CMS, and tag name can't have columns in it. So it might look like {% cms_block identifier key:value %}

**Comment by schneikai** [comment]
Nice! I guess for backwards compatibility of the new syntax for tag options there needs to be some kind of pre-parser that converts the old to the new syntax. This could also convert : to _ in tag names I guess.

**Comment by GBH** [comment]
Yeah, there will be no backwards compatibility support. I think I'll be releasing this under 2.0 version.

**Comment by schneikai** [comment]
just wanted to add two little ideas I just had:
* the page_file/s tag should just be another type of the page tag:
  {{ cms:page:some_label:file }}
* the fields-tag should support all the same types just like the page-tag so you can have richtext or markdown inputs too. or select files for example for a og:image meta data field.

**Comment by GBH** [comment]
As of 2.0 Tag system is completely overhauled. Will add to Wiki shortly.
