### ISSUE TITLE
allowed_helpers  not working

### ISSUE THREAD

**Issue by arthurtalkgoal** [comfy/comfortable-mexican-sofa#590]
Hi I tried to limit the helpers allowed for security reason.

I put all my functions into the CmsHelper.

However, CMS just render empty string for my helper methods.  

If I removed the "config.allowed_helpers = [:'cms']" then the method are triggered.

```
# cms config
config.allowed_helpers = [:'cms']

# application_controller
class ApplicationController < ActionController::Base
  helperCmsHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end


# cms_helper
  module CmsHelper
    def now
      Time.now
    end
    
    def year
      now.year 
    end
    
  end

# the snippet
{{ cms:helper:year }}

```

**Comment by GBH** [comment]
It's helpers as in helper methods, not helper modules. In your case it should be `config.allowed_helpers = [:year]`
