### ISSUE TITLE
Page jitter when scrolling to bottom in admin

### ISSUE THREAD

**Issue by ryanburnette** [comfy/comfortable-mexican-sofa#591]
It looks like there's a script doing something based on scroll position that gets into a fight with itself in some situations. You can barely see it in this screen cap because the frame rate is low, but it's very disruptive.

CMS v1.12.7
Chrome v39.0.2171.71 (64-bit)

![jitter](https://cloud.githubusercontent.com/assets/2252601/5994550/ebc0f0cc-aa46-11e4-8d64-3c696d147d8e.gif)

**Comment by GBH** [comment]
There's no JS that does things based on scroll position. But that looks pretty wonky. I'll see what's up.

**Comment by ryanburnette** [comment]
Maybe there's something in the editor.

**Comment by GBH** [comment]
Ah yeah. It has a sticky toolbar. Never noticed it doing anything strange, but I'm on Firefox mostly.

**Comment by ryanburnette** [comment]
Firefox doesn't so the bouncy scrolling past the limit of the page thing so it's probably impervious to this particular oddity.

**Comment by ryanburnette** [comment]
The problem is that when `ul.redactor-toolbar` gets `position: absolute` attached to it not longer pushes elements down by the height of it which causes elements to slide up to a point where the page is no longer tall enough to warrant the toolbar having `position:absolute`. So then it is removed and the height once again warrants it having `position: absolute`. Then the whole process repeats itself.

This issue probably belongs on the redactor repo, but let me know. I'm not familiar with redactor.

I've seen this issue many times with elements that become fixed or absolute. You have to wrap them in a container that stays in place when the inner element changes to absolute positioning.

**Comment by GBH** [comment]
I bumped redactor to the latest version. Let me know if it fixes it. If not, I'll ping redactor devs.

**Comment by GBH** [comment]
I sent message to Imperavi. Will update.

**Comment by wyaeld** [comment]
@GBH Still happening.  I used my own redactor subscription to bump the version inside the comfy gem up to the 10.1 release from April 16th, but no improvement.

**Comment by wyaeld** [comment]
Actually I'm wrong.  It wasn't anything to do with redactor.  

https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/stylesheets/comfy/admin/cms/base.sass#L35

makes the leftmenu fixed, but if you add enough additional nav items to it, that results in a menu you can't scroll down.

I've overriden that value to `relative` on mine, seems to be working fine.

**Comment by GBH** [comment]
@wyaeld I never heard anything back about issue from Imperavi :| (I'll bump bundled editor to latest version, thanks for the heads up).

Regarding side nav, if you have a lot of items you kinda need to override default html/css. Make things smaller, nest items, or remove `fixed` as you've done.

**Comment by GBH** [comment]
Admin area css and markup are completely redone. I have not noticed this jitter anymore.
