### ISSUE TITLE
How does one use this alleged `comfy_cms_render_css_path` method?

### ISSUE THREAD

**Issue by kulte** [comfy/comfortable-mexican-sofa#592]
![screen shot 2015-02-03 at 8 05 30 pm](https://cloud.githubusercontent.com/assets/633289/6035012/2de08c70-abe0-11e4-8068-91cba544c807.png)

Yes, this should just about say it all...

**Comment by GBH** [comment]
`rake routes | grep comfy_cms_render_css`

It's a route used for rendering CSS defined in CMS Layouts. What do you need to know about it?

**Comment by kulte** [comment]
I now see that, thanks. What I need to know is how to actually have the Stylesheet from the Layout affect the styling of elements on a Page. I don't see how to do that anywhere. I style a button using the Stylesheet field, and it changes nothing.

**Comment by GBH** [comment]
Here's a small entry about it in the Wiki: https://github.com/comfy/comfortable-mexican-sofa/wiki/Layouts#css-and-js

Let me know if you need clarification.
