### ISSUE TITLE
how to replace default Redactor with TinyMCE ? 

### ISSUE THREAD

**Issue by LyriD** [comfy/comfortable-mexican-sofa#595]
in version 1.12.7 Redactor is default, but i want to use free tinymce(with image uploading if possible) in my project.  
how can i do that without "badcode"? 
Thanks for answers :)

**Comment by GBH** [comment]
See: https://github.com/comfy/comfortable-mexican-sofa/wiki/Replacing-default-wysiwyg-editor-with-redactor

It applies for replacing editor with whatever you want. I need to change Wiki entry though.

TinyMCE doesn't have image manager out of the box. This is something they sell as an add-on. So I never had to integrate image uploading using it. I'm sure it's not that hard. Might need to override a few things.

**Comment by schneikai** [comment]
I think the path for the file he has to overwrite has changed from */app/assets/javascripts/comfortable_mexican_sofa/admin/application.js.coffee* to */app/assets/javascripts/comfy/admin/cms/custom.js.coffee* in a recent commit.

**Comment by andywenk** [comment]
Disclaimer: I am using cms-fortress

Thanky you very much @GBH for including Redactor. This is really awesome.

**First, a question**

I got this working so far, as I replaced TinyMCE. So now I see the Redactor editor. YAY ;-). But either uploading an image or a file does not work. The JS console says when clicking the "Insert image" button:

    GET http://localhost:3000/cms-admin/sites/1/pages/13/undefined?  
    source=redactor&type=image&_=1424561594889 404 (Not Found)

Choosing an image for upload is for sure also not working:

    POST http://localhost:3000/cms-admin/sites/1/pages/13/undefined?source=redactor&…
    Bo5O6qGhreDo2Om7Ql3K6BZgtcaDMF3ZJdEiCFWkKJ61D4PFk39tOz0KSGReK%2FHdEw
    %3D%3D 404 (Not Found)

I am not sure what the value for `undefined` should be so I debugged the JavaScript a bit and found out, that `CMS.file_upload_path` is undefined. I am wondering where I have to define that?

**Secondly,**

I assume that the images will be uploaded in the same directories server side when using the Redactor editor as when I upload them in the Upload section directly. Correct?

Thanks you very much!

**Comment by andywenk** [comment]
UPDATE:

My analyses with `CMS.file_upload_path` was correct. I changed it back to:

    imageUpload:      $('.cms-files-modal').data('iframe-src') + "?source=redactor&type=image&#{params}"
    imageManagerJson: $('.cms-files-modal').data('iframe-src') + "?source=redactor&type=image"
    fileUpload:       $('.cms-files-modal').data('iframe-src') + "?source=redactor&type=file&#{params}"
    fileManagerJson:  $('.cms-files-modal').data('iframe-src') + "?source=redactor&type=file"
    
and now it is working. I placed everything in app/assets/javascripts/comfy/admin/cms/custom.js.coffee ...

**Comment by GBH** [comment]
It's this file: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/views/layouts/comfy/admin/cms/_head.html.haml

If it's replaced by cms-fortress, that would explain missing js variables

**Comment by andywenk** [comment]
@GBH perfect! Thanks for the tipp. This is now running. 

I have some ideas for improving the Image and FileManager popup. I guess it's best to open a new issue to discuss it?

**Comment by GBH** [comment]
There's already one in progress: #593
