### ISSUE TITLE
Helper tag can be rendered in layout, but not via cms_snippet_content

### ISSUE THREAD

**Issue by arthurtalkgoal** [comfy/comfortable-mexican-sofa#599]
I have a helper,

which can be rendered correctly in my Layouts
```
{{ cms:helper:pages_menu }}

```

but when it is put in my snippet and was triggered in my application.html.erb

```
<%= cms_snippet_content('header').html_safe %>
```

The whole string is not rendered

Snippet  - "header"
```
<div>
         {{ cms:helper:pages_menu }}
</div>
```

**Comment by GBH** [comment]
Try `cms_snippet_render` helper. It will do tag rendering as well.
