### ISSUE TITLE
comfortable-mexican-sofa+spree

### ISSUE THREAD

**Issue by connecticus** [comfy/comfortable-mexican-sofa#600]
Maybe someone had a successful experience of such integration...

I use a https://github.com/hazg/spree_comfy to integration. 

I try to render spree partials in comfy layout via {{ cms:partial:path/to/partial }} (share/products for ex.) but have problems with methods.

Is it possible a closer integration comfy+spree?

I understand that add any decorators is need...

Thank you for your work!

Kate.

**Comment by GBH** [comment]
Are you getting any errors? Partial tags simply expands to `render :partial => '/path` Maybe you got path wrong?
Also I wonder if it has anything to do with Spree being an isolated engine.

**Comment by connecticus** [comment]
Thank you, it was my fault. Thank you for a great product !!!

**Comment by arthurtalkgoal** [comment]
Hi , I have merged Comfy with Spree, everything works pretty fine. I am modifying the layout, may be a bit messy. notice namely the comfy assuming you have a site built, and allow you have multi site, there may be some troubles in Spree controllers.

Also, I hack the Spree Admin login as it's quite useful if we can keep the spree_auth_device gem; but the Spree::LegacyUser have different cancan ability or verification methods as comfy:

![mysystem](https://cloud.githubusercontent.com/assets/7088330/6477947/3dc091c2-c264-11e4-9290-baa93dfedf89.jpg)


![fronteng](https://cloud.githubusercontent.com/assets/7088330/6477952/585aeae6-c264-11e4-9591-7d365d504b21.jpg)
