### ISSUE TITLE
pages not showing up, 404 error

### ISSUE THREAD

**Issue by confact** [comfy/comfortable-mexican-sofa#601]
I tried to use Comfortable mexican sofa in my existed application.
I add domain for site (b.-----.com), add page for //b.-----.com/abouts/ and try to go to http://b.****.com/abouts/ but i get 404 error.
routes says this:

                        sidekiq_web                   /sidekiq                                                                      Sidekiq::Web
                        comfy_cms_render_css GET      /cms-css/:site_id/:identifier(/:cache_buster)(.:format)                       comfy/cms/assets#render_css
                        comfy_cms_render_js GET       /cms-js/:site_id/:identifier(/:cache_buster)(.:format)                        comfy/cms/assets#render_js
                        comfy_cms_render_page GET     /(*cms_path)(.:format)                                                        comfy/cms/content#show
                        websocket GET                 /websocket(.:format)                                                          websocket_rails

Could websocket_rails make it stop working, shall i test disable websocket rails? this is not anything i set manually.

**Comment by GBH** [comment]
I don't see why the page wouldn't load. Watch the log and you'll see what's getting hit. 
Also that websocket path is not accessible anymore. Globbing route has to be last.

Actually that gem is appending routes instead of prepending: https://github.com/websocket-rails/websocket-rails/blob/master/lib/websocket_rails/engine.rb#L10 That's wrong and needs to be fixed.

**Comment by confact** [comment]
okay, i have test around a bit and now i can make it work on the test environment but not in production, so i am probably doing some settings wrong here. It goes to right path, but it goes not to CMS.

**Comment by confact** [comment]
Okay, i tested reset the db and run migration again, and magically that worked. Pretty weird if you ask me.

Thanks for the help anyway and for a amazing CMS!
