### ISSUE TITLE
is it a bug my .png file is triggerring ContentController?

### ISSUE THREAD

**Issue by arthurtalkgoal** [comfy/comfortable-mexican-sofa#602]
My ```small.png``` is indeed exists and displayed in frontend.

However, i found the log file contains the following trigger ContentController

```
Started GET "/assets/noimage/small.png" for 203.218.199.170 at 2015-02-11 23:02:
50 +0800
Processing by Comfy::Cms::ContentController#show as PNG
  Parameters: {"cms_path"=>"assets/default_taxon"}

```

**Comment by GBH** [comment]
Is that Spree? Looks like it's trying to load default taxon icon and ends up hitting CMS content controller.

That log doesn't make much sense to me though. Request is for `/assets/noimage/small.png` but ends up being `assets/default_taxon.png`

**Comment by arthurtalkgoal** [comment]
Hi @GBH,

Yes, that's right, it's spree's no image. I don't know how to **disable the comfy routes for PNG images (and other assets)**, I put my spree above comfy in my routes.rb

```
 mount Spree::Core::Engine, :at => '/shop'
  
  
  comfy_route :blog_admin, :path => 'blog-admin', :as => :blog_admin
  comfy_route :blog, :path => 'blog', :as => :blog
  
  comfy_route :cms_admin, :path => '/admin', :as => :cms_admin

  ...
  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false, :as => :cms
  
  match '*a', :to => 'errors#routing'  , :via => :get
  
  # match '/422', :to => 'errors#server'
  match '/500', :to => 'errors#server', :via=>[:get]
```

**Comment by GBH** [comment]
You just need to make sure that requests for images don't get piped to Rails stack. Generally web server should be configured not to hit Rails if it's a request for `/assets`. In development environment I wouldn't worry about that. Google around on how to do that.

Also about `Make sure this routeset is defined last`. It's not a suggestion. Your `errors#routing` and `errors#server` are not accessible anymore. (You don't need `errors#routing` anymore though)
