### ISSUE TITLE
Content field got indented

### ISSUE THREAD

**Issue by arthurtalkgoal** [comfy/comfortable-mexican-sofa#603]
Hi , 

I found that it happens in many place, whenver I update my ``` content``` field in snippets (fact, same as other field which is in textarea), I got auto indentation if there is html
e.g.
```
TEST
<div>
    Tagging?
</div>

```
was changed to
```
TEST
            <div>
               Tagging?
            </div>

```

I wonder it was codemirror bugs, but it happens even after I disabled codemirror js helper

**Comment by lokson** [comment]
Couldn't replicate this. Created a snippet, edited it with your example content and it was not indented. Do you use latest version?

**Comment by arthurtalkgoal** [comment]
Hi lokson,

I am using 
```
comfortable_mexican_sofa (1.12.7 7bbf7a9)
```

I got the commit from the pull request (as I need translation)

https://github.com/comfy/comfortable-mexican-sofa/pull/522

**Comment by GBH** [comment]
Closing this one, unless it's still an issue. I couldn't replicate this either.

**Comment by cerdiogenes** [comment]
It's not a problem with comfy, but with haml: https://github.com/haml/haml/issues/828
