### ISSUE TITLE
Comfy Organization

### ISSUE THREAD

**Issue by arthurtalkgoal** [comfy/comfortable-mexican-sofa#608]
Hi , 

First off, Comfy is very useful for my projects. And as the codes got bigger, many projects are harder to manage. I found that some useful PR are pending for a while. Namely the translation for pages and live preview. 

Can I ask if comfy has existing github organizations now?  Or the community want to create one and get more people to do the project merging and operation tasks?

https://github.com/blog/674-introducing-organizations

I am very happy to help for the project tasks.

**Comment by GBH** [comment]
Comfy is a Github organization. But it's just me here.

There's not much of a problem with pull request merging as bug fixes and small improvements get merged in pretty quickly. What usually sits around for a long time are pull requests that introduce a lot of changes. Sometimes I want to merge it, but it takes time to polish it before merging. Other pull requests might not get merged if I think they provide less than optimal solution. Very subjective, it's just I want to maintain this project over a long time, so I want to keep everything in a state I can work with.

There are few pull requests open (like the i18n one) that I'll keep open until I'll come up with solution that deals with content internalization properly. There's nothing wrong with using forks if it works for you for the moment.

About helping. There are a few issues open that need to be dealt with. Feel free to tackle those. It always takes considerable time to debug those.
