### ISSUE TITLE
Redactor stripping divs

### ISSUE THREAD

**Issue by latazzajones** [comfy/comfortable-mexican-sofa#609]
We just upgraded from comfy sofa 1.12.3 to 1.12.7. It looks like Redactor's stripped all of the wrappers our of our html. I think this is a bug with Redactor but is there any kind of workaround that can be implemented within comfy sofa?

**Comment by GBH** [comment]
That's generally not a bug. Wysiwygs like to strip tags that they don't like: http://imperavi.com/redactor/docs/settings/clean/ So there's a setting that can disable this. Take a look in the Wiki on how to override Redactor initialization.

**Comment by latazzajones** [comment]
So, I'd probably have to fork this to change the setting right? I might just switch back to TinyMCE for the interim but It would be great if the default was to avoid stripping anything. Redactor looks way nicer but is there an advantage to 'cleaning up' the html? 

also - thanks for getting back to me so quickly yesterday :smile_cat:

**Comment by GBH** [comment]
Forking is always an option. Or you just override this method: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/javascripts/comfy/admin/cms/base.js.coffee#L40 which you can plop into this file: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/javascripts/comfy/admin/cms/custom.js.coffee (you should have it in your /app if you ran `rails g comfy:cms`)

**Comment by latazzajones** [comment]
@GBH Thanks! 
I had to run `rails g comfy:cms` again. It created the `app/assets/javascripts/comfy/admin/cms/custom.js.coffee` directory and I deleted the old `comfortable_mexican_sofa` directory. 

I've been able to add the customization from there with no problem. Let me know if you'd like me to add this information about customizing Redactor to the wiki and if so - where you'd like it to go.

Great project btw!

**Comment by Shehbaz** [comment]
@latazzajones @GBH I am trying to override and allow div tags but it does not work. Can you tell me how should I do it in custom.js? 

Simply doing it like follow does not work. Also tried to add it under page ready. Any help is appreciated.

window.CMS.wysiwyg = ->
  csrf_token = $('meta[name=csrf-token]').attr('content')
  csrf_param = $('meta[name=csrf-param]').attr('content')

  if (csrf_param != undefined && csrf_token != undefined)
    params = csrf_param + "=" + encodeURIComponent(csrf_token)

  $('textarea.rich-text-editor, textarea[data-cms-rich-text]').redactor
    minHeight:        160
    autoresize:       true
    imageUpload:      "#{CMS.file_upload_path}?source=redactor&type=image&#{params}"
    imageManagerJson: "#{CMS.file_upload_path}?source=redactor&type=image"
    fileUpload:       "#{CMS.file_upload_path}?source=redactor&type=file&#{params}"
    fileManagerJson:  "#{CMS.file_upload_path}?source=redactor&type=file"
    definedLinks:     "#{CMS.pages_path}?source=redactor"
    buttonSource:     true
    formatting:       ['div','p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6']
    plugins:          ['imagemanager', 'filemanager', 'table', 'video', 'definedlinks']
    lang:             CMS.locale
    convertDivs:      false

**Comment by latazzajones** [comment]
@Shehbaz You have to add the "allowedTags" setting. http://imperavi.com/redactor/docs/settings/clean/#setting-allowedTags

You'll probably also need to add "allowedAttributes". 
http://imperavi.com/redactor/docs/settings/clean/#setting-allowedAttr

**Comment by Shehbaz** [comment]
@latazzajones thanks for answering that quickly. I did try that and it doesnt work. What apperas to me is that redactor has some issue, its not taking into account allowed attribute and convertDiv=false for some reason. I moved to tinymce version (1.12.3) and its working fine.

I would like to mention my mistake that I mentioned in previous comment , mentioned formatting: ['div','p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'] instead of allowedTags

Thanks

**Comment by kirichkov** [comment]
I believe the option ````convertDivs```` was renamed to ````replaceDivs````

**Comment by Shehbaz** [comment]
@kirichkov did not know that. I believe you are right. I have already sent the feature to production with tinyMCE.

**Comment by hallaathrad** [comment]
Not sure why, but the `clean`section of redactor's documentation has gone MIA and I cannot find how to remove these annoying filters. Please advise?

**Comment by Daniel-ltw** [comment]
Another simpler way to do this is to overwrite what comfy has set for redactor. 

Change the settings yourself to fit your own use.

**Comment by hallaathrad** [comment]
Not really sure how to do that on RoR. I come from the JS stack.
Will that imply somehow overriding the gem from the app? and if so, how do you go about it?

**Comment by Daniel-ltw** [comment]
Just make a copy of https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/javascripts/comfy/admin/cms/lib/redactor.js

in app/assets/javascripts/comfy/admin/cms/lib/redactor.js

change whatever you need in there to fit your needs.

**Comment by hallaathrad** [comment]
Thank you!

**Comment by hallaathrad** [comment]
So I've tried the file override, and even typing stuff on the console, but nothing seems to take effect other than patching the gem directly (which I'm sure you agree is not a great idea for production). I wonder why m app would not be including the file to override the default. Any ideas?

**Comment by donrestarone** [comment]
Revisiting this issue in 2021! Great library, but it looks like the way to configure redactor in the current version of comfy 2.0.19  ( with Rails 6.1) has changed yet again. 

Is it still recommended to override https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/assets/javascripts/comfy/vendor/redactor.js ?
