### ISSUE TITLE
Trying to get desktop and mobile site running with aliases

### ISSUE THREAD

**Issue by andywenk** [comfy/comfortable-mexican-sofa#610]
There is the neat feature to define aliases (https://github.com/comfy/comfortable-mexican-sofa/blob/master/config/initializers/comfortable_mexican_sofa.rb#L89). I am trying to use this for two different layouted sites: desktop and mobile in a Rails 4.2 application. I am achieving this by using prepend_view_path for all application views. With comfy I created two sites: desktop and mobile. This is also the host setting. Originally I just used //localhost:3000 and //localhost:3001. But since comfy is not looking to the port, this does not work

https://github.com/comfy/comfortable-mexican-sofa/blob/master/lib/comfortable_mexican_sofa/render_methods.rb#L48

So my settings in the comfy initializer are these:

    config.hostname_aliases = {
      'desktop' => 'localhost:3000',
      'mobile'  => 'localhost:3001'
    }

I assume when starting the Rails application on port 3000, comfy will serve the desktop site. If running on port 3001 comfy will serve the mobile site. But this does not work. Do I misunderstand the functionality of aliases?

Thanks a bunch for your help and warm regards

Andy

**Comment by GBH** [comment]
Sofa doesn't do Site lookups using port info. Take a look at #554 and see if it helps (and doesn't break other things)

**Comment by andywenk** [comment]
I have no problems in local environment with using `request.host_with_port`. Can you remember which issues you had when using this? I mean this would increase the usability for config.hostname_aliases tremendously because in development you work on localhost:3000 in 90% of all cases.

**Comment by andywenk** [comment]
This is fixed by the merging the PR https://github.com/comfy/comfortable-mexican-sofa/pull/554
