### ISSUE TITLE
Two different sites sharing same views

### ISSUE THREAD

**Issue by andywenk** [comfy/comfortable-mexican-sofa#611]
Following up my previews question in https://github.com/comfy/comfortable-mexican-sofa/issues/610, I would like to know if it is possible to share pages / content between two sites. Let's say we have two sites:
- desktop
- mobile

The usecase:

If there is content for a requested page in the mobile site, serve this.
If there is no content for a requested page in the mobile site, server the content from the desktop site.
If there is no content for a requested page in the mobile or desktop site, return a 404

The functionality I am looking for is the same like I described in the previews question with prepend_view_path in Rails. Is it possible to achieve this? If not, is this worth a feature request (we would hack on)? If not, any ideas where in the comfy code this should be "hacked" in?

Thanks and warm regards 

Andy

**Comment by GBH** [comment]
This is something I was trying to implement. Things that are shared across sites. If you take a look at db schema you'll see unused `is_shared` flag. Honestly, I don't think it's trivial to implement.

**Comment by andywenk** [comment]
Hi @GBH ,

thanks for your reply. We needed to implement that and we ended up hacking it. The hack does only work with two sites atm. We have a mobile and a desktop version. So the rule is: if no mobile content exists, use the desktop content.

We have furthermore integrated many other stuff and am now in the very unfortunate situation, that we can only merge the original comfy repo with a lot of effort. You may want to scan through our changes. You can find them at https://github.com/sumcumo/comfortable-mexican-sofa/commits/integration

If there is anything you want to discuss or want to have, I can try to create a PR.

All the best 

Andy

**Comment by GBH** [comment]
Site mirroring is removed in 2.0. So Sites are completely separate. I think if you want to have reusable components I'd create a Crud for them and then pull them in via a cms helper.
