### ISSUE TITLE
Can't create site using a rake task

### ISSUE THREAD

**Issue by nnunn** [comfy/comfortable-mexican-sofa#614]
task :prepare do
    Comfy::Cms::Site.create!(:identifier => 'site-identifier', :hostname => 'localhost')
  end

gives me:

uninitialized constant Comfy

Do I need to load a something so that Comfy is recognized? 

Please Help!!

**Comment by GBH** [comment]
I think you need ` task :prepare => :environment do`. This way it loads Rails and everything else.

**Comment by nnunn** [comment]
THANK YOU!!!

**Comment by GBH** [comment]
:+1:
