### ISSUE TITLE
Layout's snippets identifier cannot use "-"

### ISSUE THREAD

**Issue by arthurtalkgoal** [comfy/comfortable-mexican-sofa#616]
I have the following tags in my layout,
The snippet named ```header-test``` doesn't work
```
{{ cms:field:meta_description:string }}
{{ cms:snippet:header-test }}
{{ cms:page:content }}
{{ cms:page:sidebar }}
{{ cms:snippet:footer }}
```

But it displayed after I renamed the snippet to ***headertest***

The tricky thing is snippets identifiers are generated with "-" when there are spaces in the Name

**Comment by GBH** [comment]
Works for me: http://comfy-demo.herokuapp.com/admin/sites/1/layouts/1/edit (username//password)

**Comment by arthurtalkgoal** [comment]
Hi @GBH,

Thanks for your help. I cannot reproduce the problems. Let me investigate into it more. I bet there is something else preventing the snippet to be rendered when I set up the layouts.
