### ISSUE TITLE
Inline javascript prevents strict CSP against inline JS

### ISSUE THREAD

**Issue by rossettistone** [comfy/comfortable-mexican-sofa#619]
Thanks very much for your work on this great gem!

Using a strict content security policy to prevent execution of inline JS, I noticed that you have two lines of JS in `app/views/layouts/comfy/admin/cms/_head.html.haml`.  Looks like they may be the only two in the gem, and moving these into an existing JS file would allow for consistent CSP across the whole site.

**Comment by GBH** [comment]
Interesting. Never had to deal with Content Security Policy stuff before. I guess it's possible to move that inline js into meta tags as we just need to set variables there. I wonder how does this also affect `text/javascript` based responses from Rails? I often use `action.js.erb` to do dom manipulation.
