### ISSUE TITLE
Can conditional helper login used in content_cache

### ISSUE THREAD

**Issue by arthurtalkgoal** [comfy/comfortable-mexican-sofa#621]
I have some helpers that with condition

e.g. ```link_signinout ```

which create a link to sign out if user signed in, and a link to sign in if user signed out.
```
if user_signin?
   ...
else
  ...
end

```

The {{cms:helper:link_signinout}} is used in my page.

I found that Comfy put the contents into database via ***content_cache***

Can I ask if my conditional helper got snapshoted cached or it will rendered dynamically?

Thanks

**Comment by GBH** [comment]
content_cache will be holding `<%= link_signout %>` so it will be dynamic
