### ISSUE TITLE
Nested snippets don't evaluate nested calls when called by cms_snippet_content

### ISSUE THREAD

**Issue by ryanburnette** [comfy/comfortable-mexican-sofa#623]
If I build a nested snippet, let's say the parent is `cms:snippet:foo` and the child is `cms:snippet:bar` and I call it from inside a content editor, it works fine. But if I call the parent snippet using `cms_snippet_content`, the parent snippet's content is returned, but nested snippets still contain `{{ cms:snippet:bar }}`.

https://groups.google.com/forum/#!topic/comfortable-mexican-sofa/8tQ-1QT2nSU

**Comment by ryanburnette** [comment]
I needed to use `cms_snippet_render`. It wasn't rendering the snippet. 😳

https://groups.google.com/d/msg/comfortable-mexican-sofa/8tQ-1QT2nSU/weE0WLXMlh0J

**Comment by GBH** [comment]
Need to update wiki: https://github.com/comfy/comfortable-mexican-sofa/wiki/Accessing-cms-content-from-the-app
