### ISSUE TITLE
comfy_cms_render_css_path does not fingerprint css

### ISSUE THREAD

**Issue by tarr11** [comfy/comfortable-mexican-sofa#624]
I use cloudfront CDN but I've noticed that my Comfy CSS URL looks like:

https://somethingxxxx.cloudfront.net/cms-css/1/home.css

I'd expect it to be MD5 fingerprinted like my application.css file:

https://somethingxxx.cloudfront.net/assets/application-d22c5fb48f31ae2badca66fb086a26bb.css

Without the fingerpinting, it will get cached and changes won't get picked up when I change that CSS.  Does this option exist?

**Comment by GBH** [comment]
There's a way to control cache via a get param: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/controllers/comfy/cms/assets_controller.rb#L32

But, honestly, I think we need a better solution.

**Comment by schneikai** [comment]
I did this by adding helpers that work pretty much like Rails *stylesheet_link_tag* and *javascript_include_tag*. Check this out: https://gist.github.com/cd1d389cbaa88d482b49

**Comment by GBH** [comment]
Old issue. Pretty sure not valid anymore as assets tags will append layout cache-busters into .css and .js filenames.
