### ISSUE TITLE
Export failure if file_image present

### ISSUE THREAD

**Issue by ryanburnette** [comfy/comfortable-mexican-sofa#625]
Once I started adding `{{ cms.page_file.avatar }}` to keep up with images, my fixture export stopped working.

![screen shot 2015-04-10 at 2 14 08 am](https://cloud.githubusercontent.com/assets/2252601/7082905/0c087a1e-df29-11e4-8579-cdfbdaaeb1c3.png)

It looks like this ternary https://github.com/comfy/comfortable-mexican-sofa/blob/master/lib/comfortable_mexican_sofa/fixture/file.rb#L54 expects `block.page` to be defined if `block.present?` returns true, but that's apparently not always the case.

https://groups.google.com/forum/#!topic/comfortable-mexican-sofa/P9XjcKypPB4

**Comment by GBH** [comment]
Fixed in current master
