### ISSUE TITLE
Broken links when migrating from local storage to S3.

### ISSUE THREAD

**Issue by lyneux** [comfy/comfortable-mexican-sofa#627]
To make my app more scaleable, I want to move to using Amazon S3 to store files (previously I had been storing them locally).

I have configured my sofa to use S3 without problems: in the CMS Admin pages I can see that all images are now being referenced correctly from S3 and uploading images works (the new images are placed on S3 storage).

The existing pages on my site however, are full of broken links as they seem to be referencing the old (filesystem) file locations. If I preview the page from the Admin pages, everything looks fine. If I Update the page, it looks fine.

Do I really need to Update every page of the site using the Admin pages to migrate to S3? Is there a smarter way of doing this?

**Comment by GBH** [comment]
CMS probably still has cached content with old links. When you hit 'update' it refreshes cache for the page content. You can just blow away caches:
```ruby
Comfy::Cms::Page.update_all(:content_cache => nil)
```
