### ISSUE TITLE
Tags are not available inside of CSS

### ISSUE THREAD

**Issue by mguterl** [comfy/comfortable-mexican-sofa#629]
It would be nice to be able to use CMS or ERB tags inside of CSS files so that images can be referenced by name for background images.

For example:

To use an image stored in the CMS in a page or snippet:

``` html
<img src="{{ cms:file:icon-pub.png }}" alt="">
```

To use an image stored in the CMS in CSS:

```
.link-arrow {
  content: url("/system/comfy/cms/files/files/000/000/045/original/link-arrow.png");
}
```

We use CMS fixtures to export sites and re-import them and the ids referenced in the CSS change.

**Comment by GBH** [comment]
Interesting. It's an idea. Should be pretty easy to run it through tag expander.

**Comment by schneikai** [comment]
I posted this on Google Groups once https://groups.google.com/d/msg/comfortable-mexican-sofa/IFCN9KjHd9I/TmqtnlErvw8J :)

**Comment by GBH** [comment]
Closing this as it's not a bug. PR is welcome.
