### ISSUE TITLE
configuration with devise and cancan

### ISSUE THREAD

**Issue by samro** [comfy/comfortable-mexican-sofa#630]
Hello !

I'm sorry if my question is a bit stupid, i'm just an amateur :)

I'm testing comfy with a new site and trying to configure comfy to work with devise and cancan. I followed the wiki but i have a routing error .

what is 'MyApp' in following instructions ? 
"in lib/my_app/devise_auth.rb
module MyApp::DeviseAuth"

I tryed 'something' and i have 'uninitialized constant something' error message when i'm going to 'http://localhost:3000/admin'

rails 4.2.1
comfy 1.12.8
devise 3.4.1
cancancan 1.10.1

**Comment by GBH** [comment]
Take a look inside your `config/initializers/comfortable_mexican_sofa.rb'. There's a pretty clear example on how to attach your own authentication/authorization. Basically, it's a module with a method that gets crammed into CMS admin controller. So inside that method you'd normally have something like this:

```ruby
module ComfyPublicAuthentication
  def authenticate
    unless current_user && current_user.is_admin?
      flash[:error] = 'Login an an admin pls'
      redirect_to login_path
    end
  end
end

```
