### ISSUE TITLE
Comfy or ComfortableMexicanSofa??

### ISSUE THREAD

**Issue by rkukuczka** [comfy/comfortable-mexican-sofa#631]
Hi Everybody,

I'm very new to ComfortableMexicanSofa. I've just installed the 1.8. under rails 3.22. Please enlighten me 
how do relate the Comfy to ComfortableMexicanSofa. On the web there are plenty code samples regarding a 'comfy' but almost no for ComfortableMexicanSofa. How comes? Do I use a dead version or miss sth else?

**Comment by GBH** [comment]
I don't really understand the question. Rails 3.2 is pretty old though. So current CMS is only for Rails 4.0+

**Comment by rkukuczka** [comment]
I know that the 3.22 is a history but I mount it as an engine to an existing app. 

Is it possible to have the main app working on rails 3.22 and engine with rails 4.0?

independly from rails version. What is the relation of comfy to ComfortableMexicanSofa?

Regards

**Comment by GBH** [comment]
No, you can't use engine made for Rails 4.0 with Rails 3.2 app. Well, sometimes you can if there are no breaking dependencies, but generally Rails 4.0 and 3.2 are pretty different. Strong params, for example.

What other "comfy" you're talking about?

**Comment by rkukuczka** [comment]
I use 

Gemfile:

rails ‘3.22’
...
gem 'comfortable_mexican_sofa', '~> 1.8.0’ in my main app’s gem file
and I need to have this in my route.


  ## CMS
  ComfortableMexicanSofa::Routing.admin(:path => ‘/a/admin')
  # Make sure this routeset is defined last
  ComfortableMexicanSofa::Routing.content(:path => ‘/a', :sitemap => false)

why no comfy? because it is not available. Shall I upgrade to rails 4 in order to use comfy namespae everywhere or I miss sty else?

Greetings

**Comment by GBH** [comment]
That's what 1.8 version did for routing. And yeah, it didn't have `Comfy::` namespace yet.

**Comment by rkukuczka** [comment]
So I need to use another version or what you suggest?

**Comment by GBH** [comment]
If you want to use current version of CMS, you need to have a Rails 4.0+ app.

**Comment by rkukuczka** [comment]
I understand. Where to get documentation for the old version from?

**Comment by GBH** [comment]
Not much of the documentation, but you can browse source code for that version: https://github.com/comfy/comfortable-mexican-sofa/tree/v1.8.5

**Comment by rkukuczka** [comment]
Oleg,

the light at the end of the tunnel :)

When I try to summarise my problems today I see that the Wiki is the main obstacle. There is no version info and It references the version 2.0 at the same time it is available from github page with examples giving examples of installing by 1.8 
For someone new in this field it is not that easy to sort it out. 
 
I do not see version information anyway. 
Do you think there is a version in wiki that I shall reference to, or pay more attention to? I see I can edit the page but I think it is not a very good idea that a not-very-experienced coder like me  can modify it on will :) 

Anyway thank you very much for assistance.

Best Regards

**Comment by GBH** [comment]
Wiki should only have info on the current version. There's no versioning of content there.
New users generally install currently available version, and not one from 2 years ago (v 1.8)
If you have issues with getting 1.8 running, post them on googlegroups.
