### ISSUE TITLE
Admin/CMS Controllers use permit! instead of whitelisting params

### ISSUE THREAD

**Issue by pivotal-rivals** [comfy/comfortable-mexican-sofa#632]
Admin::Cms::FilesController, LayoutsController, PagesController, and SitesController use `permit!` instead of whitelisting allowed parameters with `permit`. These issues are flagged by running the `brakeman` gem against a project with Comfy as an engine. An example of a fix for the FilesController method on line 113 is as follows:

``` ruby
params.fetch(:file, {}).permit!
```

to

``` ruby
params.fetch(:file, {}).permit(:label, :description, :file)
```

**Comment by GBH** [comment]
Yeap. I'm aware of that. Thinking is that only admins are allowed into CMS admin area. So it doesn't make sense to restrict params. Also because you can extend CMS models / forms with new fields, it's going to be annoying to configure controllers.
