### ISSUE TITLE
Render cms_page with anker in url (which doesn't belongs to cms page path)

### ISSUE THREAD

**Issue by claudia-pfeil** [comfy/comfortable-mexican-sofa#634]
Hi there,

I would like to render a cms_page with a specific anker in the url so the user hasn't to scroll down to the interesting area of content. If I would pass the anker '#interesting_area' to cms_page '/'  as I would do in the browser url e.g. '/#interesting_area' than comfy can't find the page. Can you help me to find a solution for cms_page with ankers, please?

**Comment by schneikai** [comment]
I try to a answer this: The server does actually not deal with anchors (aka hashmarks; http://en.wikipedia.org/wiki/Fragment_identifier#Basics). It's a client thing. Maybe you add some javascript to scroll there when the page loads?

**Comment by claudia-pfeil** [comment]
Hi Kai, 
thanks for your answer. I have already solved it with Javascript in that way: 
<% if @anchor.present? %>
      <script type="text/javascript">
          window.location.hash = "<%= @anchor %>";
          if(navigator.userAgent.indexOf('Firefox') > -1){
              window.location.reload();
          }
      </script>
 <% end %>
Actually I think it should be possible to manage it by a new param in the cms_page e.g. 'render :cms_page => '<comfy_path_name>', :anchor => '#hashtag'. I mean this should give comfy the possibility to match the right page in the cms by cms_page param and the additional information via :anchor param for the scroll down. As long as this is 100% pure HTML we shouldn't be in the need of Javascript, right?

**Comment by pierrebeitz** [comment]
@claudia-pfeil: as browsers do not send them, you can not retrieve the anchor on the server side in any language.
And actually you do not need javascript: if the URL contains a hash, all browsers will move the viewport so that the element with the corresponding `id` or `name` will be at the top. For smooth scrolling you WILL NEED js.

**Comment by claudia-pfeil** [comment]
Hi Pierre,
as you know anchors are just a name or id in HTML5 to a DOM-tree object as you can read in http://www.w3schools.com/tags/att_a_name.asp. Only Comfy can't support it because cms_page can't solve the url of the page path apart from the hashtag of the anchor e.g. page path = '/start' and you wanna link to '/start#downtobottom' than comfy can't find the page. In my eyes it is possible to teach comfy more flexibility with an additional parameter for example: render :cms_page => '/start', :anchor => 'downtobottom' and comfy could do the magic to link to /start#downtobottom'. That's it! Thx
