### ISSUE TITLE
Rendering CMS Page from rake/capistrano task

### ISSUE THREAD

**Issue by kirichkov** [comfy/comfortable-mexican-sofa#636]
Is there a way to render_to_string a CMS Page from a rake task?

My idea is to keep error pages (public/404.html, public/500.html) manageable in CMS but to use a rake/capistrano task to dump their contest into a static page.

From digging through the code I think the render methods are heavily dependent on the request object but thought of asking anyways.

**Comment by GBH** [comment]
With Rails 5.1 it's possible to render outside the request. So it would be just a matter of iterating through pages and calling `render inline: page.content_cache`
