### ISSUE TITLE
Loading fixtures in tests. Documentation wrong?

### ISSUE THREAD

**Issue by schneikai** [comfy/comfortable-mexican-sofa#637]
The documentation shows how to load fixtures in tests: https://github.com/comfy/comfortable-mexican-sofa/wiki/Working-with-CMS-fixtures#using-fixtures-in-tests. This didn't work for me. The task doesn't run when doing `rake test`. Maybe this is because `rake db:test:prepare`is gone in Rails 4? Also the code snippet is missing the environment constraint on the task definition so Comfy wouldn't be defined. Also Site creation is missing the _path_ attribute.

Anyway, what about just a little test helper like this?

``` ruby
require 'rake'

def load_comfy_fixtures!(from='sample-site', to='sample-site')
  Comfy::Cms::Site.create!(:identifier => to, :hostname => host, :path => '/')

  Rake::Task.clear
  MyApplication::Application.load_tasks
  ENV['FROM'] = from
  ENV['TO']   = to
  silence_stream(STDOUT) do # If you don't want to see the import task log messages in your test output...
    Rake::Task['comfortable_mexican_sofa:fixtures:import'].invoke
  end
end
```

You could load fixtures in individual testes via `load_comfy_fixtures!`or via `setup`-block.

I know I can change documentation but I wanted to check with you first :)

**Comment by kirichkov** [comment]
I've moved the code from a rake task to ````test/test_helper.rb```` and it's importing the fixtures just fine

**Comment by schneikai** [comment]
What you mean?

**Comment by kirichkov** [comment]
The code you posted:

```
  Comfy::Cms::Site.create!(:identifier => to, :hostname => host, :path => '/')

  Rake::Task.clear
  Photocase::Application.load_tasks
  ENV['FROM'] = from
  ENV['TO']   = to
  silence_stream(STDOUT) do # If you don't want to see the import task log messages in your test output...
    Rake::Task['comfortable_mexican_sofa:fixtures:import'].invoke
  end
```

remove it from the rake task and place it in `test/test_helper.rb`

**Comment by schneikai** [comment]
I would hope so :D
