### ISSUE TITLE
Couldn't find Comfy::CmsHelper

### ISSUE THREAD

**Issue by hayesgm** [comfy/comfortable-mexican-sofa#640]
We're experiencing an auto-load issue on Rails 4.2 with Comfortable Mexican Sofa.  While the gem works correctly in development, it fails when running rspec tests on CircleCI with the following error:

```
Couldn't find Comfy::CmsHelper, expected it to be defined in helpers/comfy/cms_helper.rb (NameError)
```

We were able to fix this by changing `app/helpers/comfy/cms_helper.rb` from:

```ruby
module Comfy::CmsHelper
  ..
```

to

```ruby
module Comfy
  module CmsHelper
    ..
```

(commit: https://github.com/hayesgm/comfortable-mexican-sofa/commit/9a80e3e48531858a6c5d81e8a1293e6f091b483f). I'd be happy to find a good way to solve this load issue.

**Comment by GBH** [comment]
These issues pop up from time to time and I never know why. Yes, your solution is good. Pull request away. Thanks.
