### ISSUE TITLE
Disabling Redactor & CodeMirror

### ISSUE THREAD

**Issue by sowasred2012** [comfy/comfortable-mexican-sofa#646]
Hi, I'm loving this gem!

Is there a way to disable Redactor and CodeMirror altogether? I'm looking to add a textarea to pages that I can attach [SirTrevorJS](https://github.com/madebymany/sir-trevor-js) to.

**Comment by GBH** [comment]
Yeap. Just follow these instructions: https://github.com/comfy/comfortable-mexican-sofa/wiki/Replacing-default-wysiwyg-editor-with-redactor

You can change wysiwygs and codemirror editors to whatever you want by overriding some javascript.

**Comment by sowasred2012** [comment]
Nice one, thanks a lot.

**Comment by radsimu** [comment]
the content on that article is empty
