### ISSUE TITLE
Add information about the need to include Comfy::CmsHelper somewhere

### ISSUE THREAD

**Issue by januszm** [comfy/comfortable-mexican-sofa#650]
It seems that when upgrading from older versions to 1.12 now we need to `include Comfy::CmsHelper
`. Correct me if I'm wrong but this was so far the only solution I found to be able to use `cms_snippet_content` and `cms_block_content` helper methods in views.

**Comment by timpwbaker** [comment]
Sorry januszm. I think I've got the same problem. Where do I need to `include Comfy::CmsHelper` ?

**Comment by januszm** [comment]
Include it in your helper(s), I've put it to ApplicationHelper but it seems that it'll soon go to my PagesHelper (it seems that I use ```cms_snippet_render``` only in my 'Page' resource in Rails app)

Example

    module ApplicationHelper
         +  include Comfy::CmsHelper
    
         ...
    end

**Comment by timpwbaker** [comment]
Thanks very much. I'm actually using an old version of comfy and it was actually this that I needed: 
https://groups.google.com/forum/#!topic/comfortable-mexican-sofa/0rFBzhXXwUQ

So thank you again for having that conversation.

**Comment by GBH** [comment]
There are now `Comfy::Admin::CmsHelper` that gets automatically included for the admin area and `Comfy::CmsHelper` that needs to be added to your app if you opt-out from loading all helpers. Will make a note of this in the Wiki.
