### ISSUE TITLE
undefined method `comfy_form_for' for #<#<Class:0x007ffd1cf64660>:0x007ffd1cf7f6e0>

### ISSUE THREAD

**Issue by karlingen** [comfy/comfortable-mexican-sofa#652]
Trying to set this one up in my current app, and I have no idea why it is vomiting this error.

I have followed the readme but cannot seem to get past this error. 

![screen shot 2015-06-02 at 16 19 09](https://cloud.githubusercontent.com/assets/2265452/7937964/324c78a8-0943-11e5-81a0-6381b2a727b4.png)

routes.rb:

```
Rails.application.routes.draw do
  root 'landing_page#index'
  ..
  comfy_route :cms_admin, :path => '/cms_admin'
  comfy_route :cms, :path => '/cms', :sitemap => false
end
```

Gemfile:

```
..
gem 'rails', '~> 4.2.0'
gem 'comfortable_mexican_sofa', '~> 1.12.0'
gem 'kaminari', '~> 0.16.1'
..
```

**Comment by GBH** [comment]
For some reason it looks like CMS view helpers are not accessible from your app. I'm guessing it's related to #650. I need to investigate why this is happening all of the sudden.

**Comment by karlingen** [comment]
@GBH I'm glad you said that. 

The reason this is happening is because I am limiting which helpers should be included. 
Inside application.rb i have this line: 
```
config.action_controller.include_all_helpers = false
```

I'm using this so that I can tell my controllers which helper(s) belongs to that specific controller.
