### ISSUE TITLE
Metadata/tags associated to pages

### ISSUE THREAD

**Issue by rhymes** [comfy/comfortable-mexican-sofa#654]
It's more a "request for information" than an actual issue. 

Is there a way to associate metadata in the form of tags or just plain ruby hashes to a Page? 
For example: let's say I want to tag a certain set of pages as "green" and another as "blue" (two random words), is it possible?

Thank you.

**Comment by elmartinezinfo** [comment]
Use Node Node by Joyent Technologies.
Build a server in Express. Use mongoose.js to serialize your data postegre
into a schema for a client side mongo service.... Parsed as REST Events,
use a cypher to encrypyt any data processed under your domain with either
ir any srrcer call ./green/ or ./blue/

It's simple and easy ro integrate ssl for encryption. You can avoid
crawlers (google/bing/ask) by hiring develoers like me for contract when in
real need.

Good Luck...

**Comment by elmartinezinfo** [comment]
By the way, this (in my previous response )  is how you would avoid a
foolish scenario like you describe...

as far as instructing you...?
You're just a tech who has to ne in early for customer support---so I think
you can read, if so and you are hard-working...books can both solve and
explain this situation in Rails to you, and without necessitating such
measures.

I am a developer.
Unlesd you pay me...you're just going to hear a bunch a written bullshit
from yours trully.

**Comment by GBH** [comment]
CMS has tagging in the form of 'categories'. You can manage those from the index view. This might be useful too: https://github.com/comfy/comfortable-mexican-sofa/blob/master/lib/comfortable_mexican_sofa/extensions/is_categorized.rb

**Comment by rhymes** [comment]
@GBH thanks!

**Comment by elmartinezinfo** [comment]
What did you fix.
I'm still a Mexican from Mexico.
I am not comfortable with anything you have claimed to resolve!

Fix your Lexicon... Not your technology.
