### ISSUE TITLE
Helpers are not being evaluated from snippets

### ISSUE THREAD

**Issue by amuntasim** [comfy/comfortable-mexican-sofa#656]
VERSION: 1.12.8
I have a helper method `render_main_nav` 

In one of my snippets, I have: 

`{{ cms:helper:render_main_nav }}`

But showing as {{ cms:helper:render_main_nav }}

I have default snippets configuration in config file: 

 # By default you cannot have irb code inside your layouts/pages/snippets.
  # Generally this is to prevent putting something like this:
  # <% User.delete_all %> but if you really want to allow it...
  #   config.allow_irb = false

  # Whitelist of all helper methods that can be used via {{cms:helper}} tag. By default
  # all helpers are allowed except `eval`, `send`, `call` and few others. Empty array
  # will prevent rendering of all helpers.
  #   config.allowed_helpers = nil
  # Whitelist of partials paths that can be used via {{cms:partial}} tag. All partials
  # are accessible by default. Empty array will prevent rendering of all partials.
  #   config.allowed_partials = nil

**Comment by GBH** [comment]
Where is that snippet? Are you rendering it through the page or a view helper? You might be using `cms_snippet_content` when you want `cms_snippet_render`

**Comment by amuntasim** [comment]
Previously I was using  ` <%= cms_snippet_content('header', @cms_site).html_safe %>`

Now using ` <%= cms_snippet_render('header', @cms_site).html_safe %>` and it works
