### ISSUE TITLE
Don't work upload files in production.

### ISSUE THREAD

**Issue by bjsmth** [comfy/comfortable-mexican-sofa#657]
Hello. Why file do not upload in production(capistrano)?

My deploy.rb

```
set :linked_dirs, %w{bin log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system public/uploads}
set :linked_dirs, fetch(:linked_dirs) + %w{public/system public/uploads}
```

**Comment by Rubyum** [comment]
hi, It's same for me. I can't upload files.
Not using capistrano, tho.

**Comment by vairix-dmacchi** [comment]
Have you checked if ImageMagick is installed in your server? http://www.inmotionhosting.com/support/website/software/is-imagemagick-installed-on-the-servers

**Comment by Rubyum** [comment]
right, that was it! thanks, sir.
