### ISSUE TITLE
cms_is_categorized for ActiveResource

### ISSUE THREAD

**Issue by Daniel-ltw** [comfy/comfortable-mexican-sofa#658]
This is just a suggestion. 

Would this be possible? 
Could someone make a pull request with such feature?

**Comment by GBH** [comment]
I think you'd need a very different implementation for ActiveResource. What's your use-case?

**Comment by Daniel-ltw** [comment]
There are data driven information that we would like on the site, but they are store in a remote database with an API.

**Comment by Daniel-ltw** [comment]
Just to re-illustrated the scenario that we could use this. 

Working with microservices framework, I have database and API as a backend service. 
Using Comfy as a front-end, creating static and dynamic data driven pages.

**Comment by GBH** [comment]
Closing this as it's an old feature request. PR is welcome.
