### ISSUE TITLE
RoutingError raised in ContentController# not rescued in Rails 4 (not propagated)

### ISSUE THREAD

**Issue by januszm** [comfy/comfortable-mexican-sofa#659]
I recently upgraded a legacy app from Rails 3 to 4 and CMS 1.8 to 1.12. I've noticed that the code in the app's ApplicationController used to rescue from errors is NOT executed:

```
rescue_from ActionController::RoutingError, ActiveRecord::RecordNotFound do |exception|
  render template: '/errors/page_not_found', status: 404
end
```

Instead, I get an error page in Dev env and blank page in Prod.

Here's the code in CMS that raises RoutingError

```
def page_not_found
  @cms_page = @cms_site.pages.published.find_by_full_path!('/404')

   respond_to do |format|
     format.html { render_page(404) }
   end
rescue ActiveRecord::RecordNotFound
  raise ActionController::RoutingError.new("Page Not Found at: \"#{params[:cms_path]}\"")
end
```

Does it seem like an issue with CMS or it's an application concern? Hmm, docs for rescue_from say that since Rails version 4.0

```
Exceptions raised inside exception handlers are not propagated up.
```

If so, then should we modify page_not_found method to call somehow the global rescue_from (if possible at all)? Or maybe we should remove `rescue_from` from ContentController ? Or make rescue_from configurable in CMS ?

**Comment by GBH** [comment]
I ran into this issue as well. I had to do some dumb workaround. Let me know what you ended up doing.

**Comment by januszm** [comment]
Here's one proposition wrapped in PR: https://github.com/comfy/comfortable-mexican-sofa/pull/661

Make rescue_from conditional, configurable in initializer.

Alternatively I was thinking about putting the logic to handle "rescue" in a module and include that module in ContentController with the initialiser if possible.

**Comment by januszm** [comment]
Another solution is to unset the exception handler for ContentController with

    Comfy::Cms::ContentController.rescue_handlers.delete(["ActiveRecord::RecordNotFound", :page_not_found])

in your application code (perhaps an initialiser)

**Comment by GBH** [comment]
Closing as we don't rescue from exceptions in content serving controller.

**Comment by januszm** [comment]
We ended up using `... ContentController.rescue_handlers.delete ...` 2 years ago.

It's great that this CMS project is still under active development, thanks!
