### ISSUE TITLE
how to add plain css or links css file(not from the rails app) in layout

### ISSUE THREAD

**Issue by amandameng** [comfy/comfortable-mexican-sofa#663]
Now I have a requirement, there are many pages which may have different style, I can choose different layout for each page.
 What I don't understand is when I add plain css to 'textarea' of a layout, the css does not work on the pages using this layout.

just very simple  and plain css added to stylesheet textarea of a layout!! How to make it work? Please help

![s3](https://cloud.githubusercontent.com/assets/1794331/8476825/b1e7509e-20f7-11e5-809b-cd2b63808f2e.png)

![style_box](https://cloud.githubusercontent.com/assets/1794331/8476767/0b7506e8-20f7-11e5-85b7-91ef99632605.png)

**Comment by amandameng** [comment]
![style_box](https://cloud.githubusercontent.com/assets/1794331/8476767/0b7506e8-20f7-11e5-85b7-91ef99632605.png)

**Comment by GBH** [comment]
This Wiki entry should answer your question: https://github.com/comfy/comfortable-mexican-sofa/wiki/Layouts#css-and-js

**Comment by amandameng** [comment]
@GBH Thanks, got it right!

![image](https://cloud.githubusercontent.com/assets/1794331/8518001/a5ff86ee-23f8-11e5-97a6-608bd833e946.png)


![image](https://cloud.githubusercontent.com/assets/1794331/8517993/96f94fc2-23f8-11e5-8dfa-11f366fd5cc2.png)
