### ISSUE TITLE
erb code is rendered as plain text in snippets.

### ISSUE THREAD

**Issue by atbyrd** [comfy/comfortable-mexican-sofa#665]
I am having a hard time understanding how snippets and layouts work. I`m trying to use Rails Form Helpers within my snippets but it is being rendered as plain text. I enable irb in the config file. 
### config/initializers/comfortable_mexican_sofa.rb

```
  config.allow_irb = true
```
### {{ cms:snippet:header}}

```
<head>
  ...
  <%= stylesheet_link_tag "style" %>
 ...
</head>
```

**Comment by lpil** [comment]
```ruby
config.allow_irb = true
```

Should that be `allow_erb` ?

**Comment by atbyrd** [comment]
@lpil Not according to the [source.](https://github.com/comfy/comfortable-mexican-sofa/blob/master/config/initializers/comfortable_mexican_sofa.rb#L74)

**Comment by lpil** [comment]
How strange... It's wrong though- it's called `erb`, `irb` is a REPL.

**Comment by GBH** [comment]
Anything with `<% %>` will be escaped if plugged into snippet's content. You need to wrap it in `{{cms:helper}}`. Or enable erb. It's `allow_erb` now, my bad.
