### ISSUE TITLE
Changing Page Title inside of a Link to that Page Breaks the Link

### ISSUE THREAD

**Issue by keesbriggs** [comfy/comfortable-mexican-sofa#671]
I have a two-column layout with a left nav in the first column, populated by an unordered list with A tags inside of LI tags, with the A tags referencing the page slugs, and the A tags wrapping around the page label.

However, if I trim the page label to be anything but the exact wording of the Page Label in the page panel, the link breaks! In other words, it's almost like the href is pointless, as the link apparently is being generated by the Page Label?

Strangely, this seems like it only happens for some links... Other links can take text other than the Page Label and work fine.

**Comment by GBH** [comment]
Closing very old issue. I think code examples would be helpful to understand the issue though.
