### ISSUE TITLE
Outdated wiki page Customizing-the-WYSIWYG-Editor

### ISSUE THREAD

**Issue by mspanc** [comfy/comfortable-mexican-sofa#672]
It seems that this page is outdated:

https://github.com/comfy/comfortable-mexican-sofa/wiki/Customizing-the-WYSIWYG-Editor

link to http://elrte.org/redmine/projects/elrte/wiki/Docs_EN#Custom-toolbar does not work and `$.CMS` is not available in the admin panel.

**Comment by GBH** [comment]
Will be redoing Wiki shortly.
