### ISSUE TITLE
Customizing underlying table names

### ISSUE THREAD

**Issue by wintondeshong** [comfy/comfortable-mexican-sofa#675]
In the https://github.com/comfy/comfortable-mexican-sofa/blob/master/db/upgrade_migrations/08_upgrade_to_1_12_0.rb migration, tables were switched to be prefixed with 'comfy_'. Has anyone successfully overridden the table names to revert back? When I attempt to change the table names via standard Active Record approach I run into a variety of issues. Before attempting to list each one, is there an easy way to do this documented somewhere I'm not finding? 

I'm not very hopeful given I see this table prefix hardcoded in scopes (ie. Comfy::Cms::Page)...

``` ruby
# -- Scopes ---------------------------------------------------------------
default_scope -> { order('comfy_cms_pages.position') }
```

Any insight would be much appreciated!

**Comment by GBH** [comment]
Closing super old issue. Generally I'd never attempt to override table names. It just introduces too many problems.
