### ISSUE TITLE
Hefty speed-problem with `cms_block_content`?

### ISSUE THREAD

**Issue by toadle** [comfy/comfortable-mexican-sofa#678]
Hey guys, 

I don't know if it is just me, but I noticed a quite hefty speed problem on our page. We rely quite heavy on custom-cms-fields/blocks that decide if some element is displayed or not. Like so: 

`if cms_block_content(:"txtblock.display") == "1"`

Now when trying to track down the speed problem, I noticed this line in `cms_block_content`: 

```
  def tag
    @tag ||= blockable.tags(:reload).detect { |t| t.is_cms_block? && t.identifier == identifier }
  end
```

I monkey-patched it to:

```
  def tag
    @tag ||= blockable.tags.detect { |t| t.is_cms_block? && t.identifier == identifier }
  end
```

And got a quite significant speed increase: The page loaded in 900ms instead of 2.5s
But I also got problems with the content being loaded. So it seems this "reload" is essential. 

I don't really get, what it does. 

Any explanation? Any idea to make it fast again?

**Comment by toadle** [comment]
![bildschirmfoto_2015-08-10_um_17 04 41_1024](https://cloud.githubusercontent.com/assets/115103/9177037/28840a52-3f8f-11e5-9303-662dc11523e9.png)

I could achieve the following on our site by changing the `cms_block_content` method to this: 

```
  def cms_field_content(identifier, blockable = @cms_page)
    blockable && (block = blockable.blocks.find_by_identifier identifier) && block.content || ''
  end
```

**Comment by GBH** [comment]
What you did makes sense. Issue is that block is kinda complicated structure. `content` is not necessarily data from the `content` column. Tag that is associated with that block decides what to output. So there's a pile of content parsing that needs to be done. It's slow. 99% of the time you just want to get text from the database, what you're doing is fine.

Eventually this entire tag junk needs to be rewritten.

**Comment by wyaeld** [comment]
Not sure if this is the right place, but @GBH  I'd really like to have a discussion on if/how things can be refactored to take advantage of the Rails4 caching, or what the best alternative is.

**Comment by toadle** [comment]
@wyaeld @GBH I my oppinion the default-behaviour should be moved back to something more speedy. Since the documentation advises to actually use `cms_block_content` and this thing gets slow very fast, I think the default should be like getting only text from the DB. 

If people really want to use tags here, then the `cms_block_content` could offers something like `cms_block_content(tags: true)` where the caller is aware of the problem. 

Why does this tags-behviour exist anyway? That is because I should be able to use something like `{{cms:helper:...}`, correct?

**Comment by Preen** [comment]
+1

**Comment by GlombSt** [comment]
Struggling with a similar challenge here.

Root cause seems to be:
from module ComfortableMexicanSofa::CmsManageable
    # Array of cms_tags for a page. Content generation is called if forced.
    # These also include initialized cms_blocks if present
    def tags(force_reload = false)
      self.render if force_reload
      @tags ||= []
    end

if I understand this correctly it means because of ' blockable.tags(:reload)' in the calling method, all tags of the page are re-rendered for EVERY application code request to some tag.

What I am considering as a workaround right now is to pull the information directly from the @cms_page object, something like this:

ComfortableMexicanSofa::Tag.process_content(@cms_page, @cms_page.blocks.find_by_identifier('meta.keywords').tag.content)

or even just: 

@cms_page.blocks.find_by_identifier('meta.keywords').tag.content

Any thoughts on this?

**Comment by GBH** [comment]
As of 2.0 tags parsing is overhauled. You don't need to rerender layout just to get some content from the Fragment (aka block). I'm sure there can be some expensive calls (if you want to rerender fragments content with tags) but otherwise it should be much faster.
