### ISSUE TITLE
Customizing pages form

### ISSUE THREAD

**Issue by atbyrd** [comfy/comfortable-mexican-sofa#681]
I'm trying to modify the form for a pages so that I can add a messages to users suggesting that they only upload so many files at a time. I'm tried overriding `lib/comfortable_mexican_sofa/form_builder``as well as``app/views/comfy/admin/cms/files/_form.html.haml`` and I'm not able to see any changes. How can I modify this view?

![screenshot](https://cloud.githubusercontent.com/assets/974295/9583620/234a0700-4fd2-11e5-8dc2-0eaf103368e1.png)

**Comment by GBH** [comment]
Now it's a matter of overriding tag class: https://github.com/comfy/comfortable-mexican-sofa/blob/master/lib/comfortable_mexican_sofa/content/tags/files.rb

or just overriding partial that shows attachments: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/views/comfy/admin/cms/pages/_fragment_attachments.html.haml
