### ISSUE TITLE
SQL Cache

### ISSUE THREAD

**Issue by Preen** [comfy/comfortable-mexican-sofa#683]
Is it possible to cache the method cms_block_content? I find that when building a large one page site the page takes forever to load.

[2015-09-07T12:26:39.972968 #26811] DEBUG -- :   CACHE (0.0ms)  SELECT  "comfy_cms_pages".* FROM "comfy_cms_pages" WHERE "comfy_cms_pages"."id" = ?  ORDER BY comfy_cms_pages.position LIMIT 1  [["id", 1]]
D, [2015-09-07T12:26:39.974337 #26811] DEBUG -- :   CACHE (0.0ms)  SELECT  "comfy_cms_layouts".* FROM "comfy_cms_layouts" WHERE "comfy_cms_layouts"."id" = ?  ORDER BY comfy_cms_layouts.position LIMIT 1  [["id", 1]]
D, [2015-09-07T12:26:39.976742 #26811] DEBUG -- :   CACHE (0.0ms)  SELECT "comfy_cms_blocks".* FROM "comfy_cms_blocks" WHERE "comfy_cms_blocks"."blockable_id" = ? AND "comfy_cms_blocks"."blockable_type" = ?  [["blockable_id", 1], ["blockable_type", "Comfy::Cms::Page"]]

I can see that the queries dont get cached at all.

**Comment by Daniel-ltw** [comment]
I think the load time is due to the parsing of the whole html content block. 

https://github.com/comfy/comfortable-mexican-sofa/issues/678

**Comment by Preen** [comment]
@Daniel-ltw 
You're right. I used the code @toadle had wrote and saw a really nice speed decrease!

def cms_field_content(identifier, blockable = @cms_page)
  logger.debug 'CONTENT?!'
  blockable && (block = blockable.blocks.find_by_identifier identifier) && block.content || ''
end
