### ISSUE TITLE
redactor.js version upgrade?

### ISSUE THREAD

**Issue by dmartiniuc** [comfy/comfortable-mexican-sofa#684]
We spotted some bugs in redactor.js which break our desired functionality and which supposedly are fixed in newer versions. Is it planned to upgrade redactor.js in the near future?

**Comment by GBH** [comment]
I bumped redactor to 10.2.3 in master. Let me know if it works.

**Comment by dmartiniuc** [comment]
Yes, it works. Thank you very much.
