### ISSUE TITLE
Release with export change

### ISSUE THREAD

**Issue by mguterl** [comfy/comfortable-mexican-sofa#685]
Would it be possible to get a new release to the 1.12.x series with this commit cherry picked on to it? https://github.com/comfy/comfortable-mexican-sofa/commit/4a19f04ff446906b210b517c971bdcf5f172a84f

Without this commit we are not able to export content that is stored in S3.

Thanks!

**Comment by lokson** [comment]
Could you describe wrong behavior that is fixed by that commit? I would write missing test (which, I guess, is the reason that this fix haven't been merged).

**Comment by mguterl** [comment]
This commit fixes a bug where files stored on S3 were not included in the export. The metadata was there, but the file contents were not.

**Comment by GBH** [comment]
1.12.9 has that commit now
