### ISSUE TITLE
Using snippets with unique content more than once in a layout

### ISSUE THREAD

**Issue by mattliebetrau** [comfy/comfortable-mexican-sofa#688]
What is the best method to allow the ability to use the same snippet more than once in a layout while allowing each instance of the snippet to have unique field values?

For example, right now, if you wanted to use the same snippet twice in a layout, the snippets would be identical since the field names would be the same. I'd like to reuse the structure of a snippet without keeping the same field values. Is this possible by modifying the gem?

**Comment by GBH** [comment]
Closing this as it's old. 

Honestly I don't get the question. Snippet has content (as in one textarea). How can it have different structure for the same name?
