### ISSUE TITLE
Bootstrapped Site Generation Worthwhile?

### ISSUE THREAD

**Issue by davidahopp** [comfy/comfortable-mexican-sofa#689]
Hello,

I was just wondering if anyone else thought having an ability to generate a basic bootstrapped site after installing Comfy would be worthwhile. I am working on this a little bit, and was curious if it would be worthwhile to continue.

**Comment by GBH** [comment]
That's not a bad idea. Maybe as a generator? `rails g comfy:cms:site_template` or something like that?

**Comment by davidahopp** [comment]
Here is what I have so far, it's incredibly basic but wanted to get some thoughts before diving in too far.

https://github.com/davidahopp/comfortable-mexican-sofa/commit/856d297ac4255cf058a946b31db7659952215332

It builds out a site looking like this:
<img width="1319" alt="screen shot 2015-10-23 at 2 09 20 pm" src="https://cloud.githubusercontent.com/assets/1263382/10702493/b26204f6-798f-11e5-81f6-b71bc724099a.png">

**Comment by GBH** [comment]
Closing this as in 2.0 has a lot of changes. If there's interest, let's reopen this as a new PR.
