### ISSUE TITLE
Do not use I18n.locale = :xx when changing locale

### ISSUE THREAD

**Issue by fabn** [comfy/comfortable-mexican-sofa#692]
I think the proper way to change locale in any controller is to use [I18n.with_locale](https://github.com/svenfuchs/i18n/blob/master/lib/i18n.rb#L252) otherwise the locale remains set in the following requests and this may introduce some weird behavior in the rest of the app.

In my case I'm using a multi language app which has `en` only backend. Backend code does not deal with translations, however when any comfy page is browsed in public part following requests to backend retain that locale and backend is screwed.

I fixed this by forcing en locale in backend code, however your code should not change global variables permanently.

I found the following places where locale is changed:
- [BaseController](https://github.com/comfy/comfortable-mexican-sofa/blob/10b8e353902fa4396269916d266cd628ef241f2d/app/controllers/comfy/cms/base_controller.rb#L23-L25)
- [Admin::BaseController](https://github.com/comfy/comfortable-mexican-sofa/blob/10b8e353902fa4396269916d266cd628ef241f2d/app/controllers/comfy/admin/cms/base_controller.rb#L39)
- [SiteController](https://github.com/comfy/comfortable-mexican-sofa/blob/10b8e353902fa4396269916d266cd628ef241f2d/app/controllers/comfy/admin/cms/sites_controller.rb#L57)

It should be pretty easy to change `I18n.locale = :xx` to use an around_action that uses `I18n.with_locale`, what do you think?

**Comment by GBH** [comment]
Never ran into issue like this personally, but it totally makes sense. PR is welcome. Thanks.

**Comment by GBH** [comment]
Content controller is not setting locale anymore. That's delegated to main app now. Admin area does set the locale based on selected site language. PR is welcome if it somehow messes something up. Never encountered this myself though.
