### ISSUE TITLE
Different user authorisation level

### ISSUE THREAD

**Issue by Daniel-ltw** [comfy/comfortable-mexican-sofa#695]
Been curious on how we could manage this. 

Users with different permission level will have different ability on the CMS admin interface. 

Like a admin should have full control. 
A publisher should have publishing rights and any permissions that a lower level would have. 
An editor would only have editing rights but not publish. 

Could this be done? 

Currently, the few ideas that I have at the top of my head is:
Via jquery and use gon to hand over the users permission? 
Via opal, keep the user permission on ruby and use opal to write the javascript to manipulate the page? 
Via overwriting the whole partial?

Is there other suggestions?

**Comment by GBH** [comment]
You can't solve authorization flow via partials/js. I suggest you fork the entire project and do required changes on the controller level directly inside the gem. 

There's a way to implement basic authorization (briefly mentioned here: https://github.com/comfy/comfortable-mexican-sofa/releases/tag/v1.12.3), but you're better off just hacking directly. It will be much easier I think.
