### ISSUE TITLE
undefined method `pages' for nil:NilClass 

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [comfy/comfortable-mexican-sofa#700]
Can some one tell me how to fix this?   
- @cms_site.pages.root.children.published.each do |page|
  
  ```
    = link_to page.label, page.full_path
  ```

**Comment by GBH** [comment]
Closing as it's old. But it looks like `@cms_site` is not populated, so this code is running outsize of page serving controller?

**Comment by maxiaoan** [comment]
> Can some one tell me how to fix this?
> 
> * @cms_site.pages.root.children.published.each do |page|
>   ```
>     = link_to page.label, page.full_path
>   ```

had you solved this problem?
