### ISSUE TITLE
How to access cms pages in app?

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [comfy/comfortable-mexican-sofa#701]
page.full_path
=> "/resources"

 page.url
=> "//0.0.0.0:3000/cmsadmin/resources"

No route matches [GET] "/resources" for  "0.0.0.0:3000/resources"

**Comment by lilijreey** [comment]
Hi, I want to access echo page's layout field, I can find this Doc in Wiki
I use Comfy::Cms::Page.first ?? I can't get this page Layout field

**Comment by GBH** [comment]
Closing very old issue.
