### ISSUE TITLE
Editor striping html div's

### ISSUE THREAD

**Issue by mrosel** [comfy/comfortable-mexican-sofa#705]
Using the content/html within the CMS admin, when I update page it strips the div's out of the html. I havn't figured out how to keep it from doing it and it doesn't effect all divs. Notice div class="bs-example bs-example-tabs" data-example-id="togglable-tabs" was stripped (see screenshot)

![before_screenshot_2016-01-14_14-53-38](https://cloud.githubusercontent.com/assets/1315867/12337308/d337296a-bace-11e5-847e-85e59d820521.png)
![after_screenshot_2016-01-14_14-54-18](https://cloud.githubusercontent.com/assets/1315867/12337309/d34aa8b4-bace-11e5-87e4-df18bf935836.png)

**Comment by Daniel-ltw** [comment]
https://github.com/comfy/comfortable-mexican-sofa/wiki/Customizing-the-WYSIWYG-Editor

**Comment by vairix-dmacchi** [comment]
I solved this creating this file /app/assets/javascripts/comfy/admin/cms/custom.js.coffee and inside it changing redactor settings (like this):

window.CMS.wysiwyg = ->
  csrf_token = $('meta[name=csrf-token]').attr('content')
  csrf_param = $('meta[name=csrf-param]').attr('content')

  if (csrf_param != undefined && csrf_token != undefined)
    params = csrf_param + "=" + encodeURIComponent(csrf_token)

  $('textarea.rich-text-editor, textarea[data-cms-rich-text]').redactor
    minHeight:        160
    autoresize:       true
    deniedTags:       []
    imageUpload:      "#{CMS.file_upload_path}?source=redactor&type=image&#{params}"
    imageManagerJson: "#{CMS.file_upload_path}?source=redactor&type=image"
    fileUpload:       "#{CMS.file_upload_path}?source=redactor&type=file&#{params}"
    fileManagerJson:  "#{CMS.file_upload_path}?source=redactor&type=file"
    definedLinks:     "#{CMS.pages_path}?source=redactor"
    buttonSource:     true
    formatting:       ['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6']
    plugins:          ['imagemanager', 'filemanager', 'table', 'video', 'definedlinks']
    lang:             CMS.locale
    replaceDivs:      false

**Comment by mrosel** [comment]
worked like a charm!
Just had to add 
if window.CMS != undefined && window.CMS.wysiwyg != undefined

to the top and the wysiwyg editor still works. Preview shows up nice as well.

Curious, why this isn't a default?

Thanks guys!

**Comment by vairix-dmacchi** [comment]
I think it's not by default because is more "secure" for non-technical users (the same applies with <style>, <javascript>, etc.). If the editor lets add anything you can easily broke the layout of the render view if you don't know what are you doing.
