### ISSUE TITLE
Is this project still in active development?

### ISSUE THREAD

**Issue by calvinl** [comfy/comfortable-mexican-sofa#707]

**Comment by Daniel-ltw** [comment]
From my understanding, there are improvements being made around the place. 

People are using Comfy. 

Oleg might be too busy at times to get around to them. 

@GBH, you might want to answer @calvinl when you see this message.

**Comment by GBH** [comment]
Yeah, pretty much. I don't really have time to work on this right now. I'm here to deal with any game-breaking bugs but it's been pretty stable for a long time now. I'll release a version to rubygems that contains all the small bug fixes we had over the last year, but there are no features to speak of.

Rails 5 will force a significant work to get this gem working again. I'd say it would require need a rewrite from the ground up just to implement things like nicer translation support and a proper publishing flow.

**Comment by calvinl** [comment]
Great, thanks for the quick responses @Daniel-ltw and @GBH. I'm just sizing up some CMS platforms for the features I need in my next project. Would be nice to see some new features, but I understand time is a big issue. Thanks for all your hard work.

**Comment by siax84** [comment]
I use this topic as an opportunity to tell you how great I find this CMS! There are so many developer-friendly but also user-friendly approaches in this CMS that it is really a pleasure to work with it. I am super happy with the status quo, but I hope it doesn't die!

**Comment by vairix-dmacchi** [comment]
I think that would be better to focus on Rails 5 update rather than new features (it's pretty complete in that sense!)

**Comment by champiooon** [comment]
Can you add Comfy on Gitter Oleg?

**Comment by GBH** [comment]
So I spend good month full time working on 2.0. So it's active. Will be ready the moment Rails 5.2 get into beta by the end of the year or so. 

I have project created here: https://github.com/comfy/comfortable-mexican-sofa/projects/1

All fixes are more than welcome. 

@Ch1mpooya I added gitter link to the README.
