### ISSUE TITLE
Uploaded assets from CMS missing

### ISSUE THREAD

**Issue by kotowick** [comfy/comfortable-mexican-sofa#709]
Having a strange issue...

I used urls from uploaded images through the CMS for some assets (such as the logo and profile pictures). 

About 1 day after those photos are uploaded, they disappear. I will go to the site and the photos will be blank. I go to the CMS under uploads and the photos are blank there as well. Any suggestions?

Using Heroku if that matters.

**Comment by GBH** [comment]
What's happening with your S3 bucket? Are your files there? (You need to have S3 setup with Heroku as there's no local storage)

**Comment by Daniel-ltw** [comment]
Could someone explain how comfy is pushing the files into the S3? 

Is this just using the aws-sdk?

**Comment by GBH** [comment]
It's just using your standard Paperclip for file attachments. You can configure it to use S3 (it's in the wiki somewhere) but otherwise it's storing files to the disk by default.

**Comment by Daniel-ltw** [comment]
Attempted to do that, but it seems like the file is still being put on disk, or the file is missing. 

S3 does not have the file. 

Will attach some of my config tomorrow when I am back at my workstation.

**Comment by Daniel-ltw** [comment]
config.upload_file_options = {
    storage: :s3,
    s3_credentials: {
      bucket: ENV['S3_BUCKET'],
      access_key_id: ENV['S3_ACCESS_KEY_ID'],
      secret_access_key: ENV["S3_SECRET_ACCESS_KEY"],
      s3_region: 'ap-southeast-2'
    },
    s3_host_name: "s3-ap-southeast-2.amazonaws.com",
    path: '/system/:class/:id/:attachment/:style/:filename'
  }

**Comment by GBH** [comment]
So it doesn't end up on S3? It's all very fishy. I'd turn on dev logging on heroku and see exactly where that file goes.

**Comment by Daniel-ltw** [comment]
Also, I'm keen to find out what version of the aws-sdk and paperclip gem are you running with. 

Have not found a wiki page on this. Might have to start one up after we get all this resolved.

**Comment by GBH** [comment]
CMS uses whatever config you got for Paperclip. It only injects some stuff to generate thumbs. It doesn't change where you store files. You can change that via `config.upload_file_options` or even by setting global defaults for your entire app: https://github.com/thoughtbot/paperclip#defaults

**Comment by Daniel-ltw** [comment]
I do know, some versions of paperclip only play nice with certain versions of the aws-sdk. 

There is some work on the paperclip gem around that area.

**Comment by GBH** [comment]
Have you seen issue #666

**Comment by Daniel-ltw** [comment]
Attempting to test that right now. 

Based on my gemfile.lock:
aws-sdk (2.6.48)
paperclip (5.1.0)

Will see how that goes.

**Comment by Daniel-ltw** [comment]
Okay, with the latest gems, all seem to work. 

Got it working on our application. 

The only caveat is that you have to put in the s3 settings in the paperclip defaults. 

`  config.paperclip_defaults = {
    storage: :s3,
    region: ENV['AWS_REGION'],
    s3_credentials: {
      bucket: ENV['S3_BUCKET'],
      access_key_id: ENV['S3_ACCESS_KEY_ID'],
      secret_access_key: ENV["S3_SECRET_ACCESS_KEY"],
      s3_region: 'ap-southeast-2'
    },
    s3_host_name: "s3-ap-southeast-2.amazonaws.com",
    bucket: ENV['S3_BUCKET'],
    command_path: '/usr/bin'
  }`
