### ISSUE TITLE
Change datetimepicker lib

### ISSUE THREAD

**Issue by cerdiogenes** [comfy/comfortable-mexican-sofa#711]
I'm using this datetimepicker: https://eonasdan.github.io/bootstrap-datetimepicker/

I'm also integrating Comfy to my layout, for this I'm adding my assets before the Comfy ones, the layout I'm using for Comfy has the current lines in head:

``` ruby
= stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track' => true
= stylesheet_link_tag    'comfy/admin/cms/application', 'data-turbolinks-track' => true
= javascript_include_tag 'dashboard', 'data-turbolinks-track' => true
= javascript_include_tag 'comfy/admin/cms/application', 'data-turbolinks-track' => true
```

The datetimepicker used in Comfy makes use of the noConflict strategy, and I expected that this would save the $.fn.datetimepicker that I'm using, but for some reason, when the noConflict code is executed, $.fn.datetimepicker is undefined. I already make some debug, googled about it, but didn't find an explication to why $.fn.datetimepicker is undefined, since my javascript is already loaded when Comfy datetimepicker is loaded. Due this, I decide to replace this lib in my local Comfy code.

I think that this datetimepicker that I'm using has a better UX than the current one in Comfy. @GBH, since I will do this work in my local code, I would like to hear if you think that this another datetimepicker is an improvement, and in an affirmative case I can provide a PR to replace it.

Best regards!

**Comment by GBH** [comment]
Datepicker is changed to Flatpickr now. It's still possible to change it to whatever by overriding `CMS.timepicker()` method.
