### ISSUE TITLE
How to insert page Label / Title in layout?

### ISSUE THREAD

**Issue by siax84** [comfy/comfortable-mexican-sofa#714]
I want to use the Label I give a page inside the layout and I've found a bunch of different ways throughout wiki pages:

Quick Start Guide shows this: 
`<h1>{{ cms:page:header:string }}</h1>`

Screenshot in Quick Start Guide shows
`<h1>{{ cms:page:html-title:string }}</h1>`

Wiki Overview shows this
`<h1>{{ cms:page:title:string }}</h1>`

Since the field is called "Label" I assumed this would be logical:
`<h1>{{ cms:page:label:string }}</h1>`

**Unfortunately all this doesn't render the page label within my layout. It just adds another field to the pages**

Is this a foreseen feature? Is this supposed to work

![how_to_reference_label](https://cloud.githubusercontent.com/assets/3499137/14518850/1fac5656-021b-11e6-98e9-9ca9b202ebb8.png)

**Comment by GBH** [comment]
You want to use a different tag. See: https://github.com/comfy/comfortable-mexican-sofa/wiki/Tags#field

**Comment by siax84** [comment]
So that means it's not available as a tag, right? By intention or could it be added? I just wonder why I would want to duplicate this info if it's already in the page's label

**Comment by ilp416** [comment]
So. this query is actual for me.
Now I have two fields with same content: `Label` and `Title`
How can I show `Comfy::Cms::Page#label` as a title or some header on page?

**Comment by GBH** [comment]
You can create a view helper and call it like so
```
def cms_page_label
  @cms_page&.label
end
```
```
{{ cms:helper cms_page_label }}
```
