### ISSUE TITLE
Routing error in multilingual CMS

### ISSUE THREAD

**Issue by modreoci** [comfy/comfortable-mexican-sofa#720]
I have got the multilanguage mirrored CMS and it produces the routing error when it has to show any page in any language (everything seems to be correctly set):
`http://localhost:3000/en`
![screenshot-localhost 3000 2016-04-21 18-42-47](https://cloud.githubusercontent.com/assets/10616435/14724213/f7be3880-0814-11e6-9c60-5ddd70057b54.png)
Gemfile:
```ruby
source 'https://rubygems.org'

gem 'comfortable_mexican_sofa', '~> 1.12.0'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
```
routes.rb
```ruby
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin'

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

```
Definitions of sites:
![screenshot-localhost 3000 2016-04-21 22-10-20](https://cloud.githubusercontent.com/assets/10616435/14724528/18c021ae-0817-11e6-9553-e214f71021cf.png)
![screenshot-localhost 3000 2016-04-21 22-09-12](https://cloud.githubusercontent.com/assets/10616435/14724531/219c5b4e-0817-11e6-9fd0-d36f18425352.png)
![screenshot-localhost 3000 2016-04-21 22-07-31](https://cloud.githubusercontent.com/assets/10616435/14724533/25b4f178-0817-11e6-9f33-4776694669e5.png)

**Comment by GBH** [comment]
I think it might be a trailing/leading slash you need to have in the path. Probably a bug.

**Comment by modreoci** [comment]
With leading slashes it produces the same error. The trailing slashes are not possible to save. :-(

**Comment by modreoci** [comment]
Hi Oleg, What now? This is the crucial feature for my apps. C-M-S with its open interface with the rest of the app seems like the best choice for me...

**Comment by GBH** [comment]
Hey, I think your problem is actually how the host is defined. Put `localhost:3000` in there and it should work.

**Comment by modreoci** [comment]
Yesss! It works ;-) What simple. Thanks a lot...

**Comment by maxiaoan** [comment]
> Hey, I think your problem is actually how the host is defined. Put `localhost:3000` in there and it should work.

thanks for your help, god bless you
