### ISSUE TITLE
Exporting fixtures from Heroku

### ISSUE THREAD

**Issue by jonlemmon** [comfy/comfortable-mexican-sofa#721]
Our team has been using fixture exporting/importing to keep our content synced between each other. Whenever we make changes to content, we export the fixtures and commit them to the repository.

Now we're about to deploy to production (Heroku). However, because you can't really save files to Heroku, I'm just wondering if you can you think of an elegant way export fixtures on Heroku so that we can save them to our repository.

I'm also open to other options if you think there's a better solution than fixtures for keeping content synced between development and production.

Thanks!!

**Comment by rossettistone** [comment]
Assuming you're using something like Heroku's Postgres add-on for your database, you should be able to add the database's URL do your `database.yml` file and then run the import/export tasks from your local machine, prefixing them with `RAILS_ENV=production`. That should avoid any steps that require using the filesystem of the Heroku dyno.

The database URL should be on the database dashboard when you log into Heroku. Note that you'll have to prefix the URL with your username and password in your `database.yml` file in order for the connection to succeed.

I expect the end result might look something like:
```yml
production:
  <<: *default
  database: myapp_production
  url: psql://<username>:<password>@aws-psql-instance.amazonwebservices.com:5432/
```

Hope that's helpful to you or anyone else who stumbles upon this post!
