### ISSUE TITLE
Dynamic element list of a tag?

### ISSUE THREAD

**Issue by tonatiuh** [comfy/comfortable-mexican-sofa#722]
The situation:

Let's say I need to create pages about cars, every car page needs to include a list of the car's features. However, the number  of car features is dynamic, some cars have 3 features or n features.

I can set the car's page layout as:

```
{{ cms:page:feature_1:string }}
{{ cms:page:feature_1:string }}
{{ cms:page:feature_1:string }}
...
```

The problem is, that doesn't work for me. I need to be able to set the field as a dynamic field so that in the page's form I can add n elements of that type.

Is there a way to do this? (I've read the docs but I haven't found accomplish this).
Thanks.

**Comment by GBH** [comment]
Dynamic list of things is something that comes up often, but there's no way to natively do that. I usually create a separate custom CRUD, like CarFeatures or something. Then I link to them via {{cms:helper}} or {{cms:partial}}.

**Comment by GBH** [comment]
While not possible in 1.12. CMS 2.0 has support for parsing block-like tags. Basically something like that is parseable:

```
{{cms:block feature}}
   <div class="feature">
     <h2>{{ cms:text title }}</h2>
      {{ cms:markdown description}}
   </div>
{{cms:end}}
```

While it's parceable, we don't have a way to store and manage that data just yet. I added it as a TODO in the 2.1 project: https://github.com/comfy/comfortable-mexican-sofa/projects/2
