### ISSUE TITLE
Experiencing two routing exceptions for every 404

### ISSUE THREAD

**Issue by samullen** [comfy/comfortable-mexican-sofa#725]
I've recently inherited a project and immediately added Rollbar to get a handle on the exceptions and bugs on the site (no testing from the previous company). As I've started knocking the bugs out, I've noticed that for 404 pages, I'm seeing two exceptions for each `ActionController::RoutingError`. We're only seeing a single exception listed in the logs, however. I've narrowed it down to comfy by testing both with and without the gem in a staging environment. When comfy's removed, we're only seeing a single exception per RoutingError. When it's there, we're getting two.

Our subscription limits us to a certain number of exceptions and if we're getting two exceptions for each 404, we'll blow through that limit quickly (we get a lot of traffic to now defunct pages).

Thanks

**Comment by GBH** [comment]
With 2.0 there's no more crazy exception throwing in content serving controller. While I don't know what the original issue was, hopefully it won't reemerge.
