### ISSUE TITLE
PageFiles not working after migrating to postgress

### ISSUE THREAD

**Issue by jusefb** [comfy/comfortable-mexican-sofa#727]
Hi,

I am having an issue with using PageFiles in my CMS pages. I used to use a MySQL database for my CMS and all was working fine. I have now migrated to Postgress due to a requirement from my server provider. Since the upgrade I can no longer use the PageFiles functionality. I have configured paperclip correctly as I can upload files from the Files section. After trying to upload a file in a specific page the content field of the cms_block table populates with an entry that looks like this: #ActionDispatch::Http::UploadedFile:0x007fd8cbbc39b8.

I have spend already quite a few hours on this but could not get it to work, would appreciate some help.

Kind regards

Jusef

**Comment by GBH** [comment]
Hopefully this was resolved. Closing old issue.
