### ISSUE TITLE
Helper method to access files from a partial

### ISSUE THREAD

**Issue by hallaathrad** [comfy/comfortable-mexican-sofa#731]
Other than creating a snippet that reads a file (i.e. image, or its url) and then rendering that, is there any way to access the files uploaded to Comfy directly from the app?

If this feature doesn't exist yet, this would certainly help us enabling non-coders to easily edit the contents of our apps, increasing the usage and utility of this gem.
I'd definitely work on creating the method but I have next to 0 understanding of back-end stuff.

**Comment by GBH** [comment]
CMS has `{{cms:file_link}}` tag to directly link uploaded files. 2.0 has the same thing just different params and some extra options that were not available before due to move from Paperclip to ActiveStorage. Will document everything in WIki shortly.
