### ISSUE TITLE
Partial tags not parsed correctly in Markdown content blocks

### ISSUE THREAD

**Issue by rossettistone** [comfy/comfortable-mexican-sofa#733]
I'm presently using a partial tag with multiple arguments to insert content from a `haml` partial into a bunch of CMS pages.

The tag looks like this:
`{{ cms:partial:shared/link_box:"https://example.com/":"PAY":"Renewal Fee Online" }}`

And the partial itself like this:

``` haml
- link = link || param_1
- line_1 = line_1 || param_2
- line_2 = line_2 || param_3

%a.media-object.link-box{ href: "#{link}", target: '_blank', onclick: "trackOutboundLink('#{link}')" }
  .media-object-section.middle
    .link-box_icon
  .media-object-section.middle
    %div #{line_1}
    %div #{line_2}
```

While this works just fine when the tag is used in a section with the `text` content type, when parsed with the `markdown` content type, the arguments are parsed incorrectly. As far as I can tell, it's treating the `:` inside the URL as an argument divider (or markdown column divider?) instead of just part of the URL string.

As far as I can tell, it seems like something might need to be added in the logic for `page_markdown.rb` to preserve the tag when the markdown is parsed: https://github.com/comfy/comfortable-mexican-sofa/blob/7b7cbb8d5c77d51779d06132cb4d1e35656c27dd/lib/comfortable_mexican_sofa/tags/page_markdown.rb#L14

I haven't figured out the exact fix yet - if anyone has ideas, I'd love to hear 'em!

**Comment by GBH** [comment]
Closing old issue.  In 2.0 partial cms tags are defined a bit differently.

If markdown does odd things with that `https://` I's probably split it as a separate argument.
