### ISSUE TITLE
Layouts without `.html` don't appear in App Layout selector

### ISSUE THREAD

**Issue by rossettistone** [comfy/comfortable-mexican-sofa#734]
While layouts in other templating languages (e.g. `erb`, `haml`) were previously required (?) to have `.html` in the filename, this is now deprecated (don't recall by which gem/framework) unnecessary. Comfy only looks for files containing `*.html.*`, which means something like `application.haml` isn't included. Was able to fix this easily in my project by renaming to `application.html.haml`.

Relevant bit of code: https://github.com/comfy/comfortable-mexican-sofa/blob/7b7cbb8d5c77d51779d06132cb4d1e35656c27dd/app/models/comfy/cms/layout.rb#L48

I may be able to put a PR together for this - just don't have the time right this moment and wanted to get it logged first :-)

**Comment by GBH** [comment]
Unless I'm completely wrong, templates should be named like "template.response_format.parser". So while `application.haml` will work, correct way to name is `application.html.haml`.

I'll leave app_layout selector as-is.
