### ISSUE TITLE
Other than Oleg

### ISSUE THREAD

**Issue by Daniel-ltw** [comfy/comfortable-mexican-sofa#738]
@GBH Maybe you should gather and consider adding a few others to be maintainers to the repository? 

Considering the user base, you could be overwhelm with all the requests and your personal life. 

My suggestion is talk to a couple of top contributors and give them a fair amount of access, so that things could move on with the gem. Will like the gem to not become stale due to you being too busy.

**Comment by GBH** [comment]
Sorry about super delayed response. I'm more than happy to add committers to the the project, but there weren't many recently that had significant or frequent contributions. 

With 2.0 development and coming Rails 5.2 release there's plenty of opportunity to change that though. There's still tons of work needed https://github.com/comfy/comfortable-mexican-sofa/projects/1 and I could use some help.
