### ISSUE TITLE
site path should be nil by default

### ISSUE THREAD

**Issue by chamnap** [comfy/comfortable-mexican-sofa#744]
On rails 5, when the value is empty string, it will generate `/`. Therefore, it will break optional routes, because it produces double forward slash. If it's nil, it will generate nothing.

```
comfy_blog_post GET    (/:cms_path)/blog(/:blog_path)/:slug(.:format)
```

```
> app.comfy_blog_post_path('', '', :slug)
=> //blog//slug

> app.comfy_blog_post_path(nil, nil, :slug)
=> /blog/slug
```

On rails 4, it's different. Either empty string and nil will generate the same result.

```
> app.comfy_blog_post_path('', '', :slug)
=> /blog/slug

> app.comfy_blog_post_path(nil, nil, :slug)
=> /blog/slug
```

**Comment by chamnap** [comment]
sorry wrong repo :(.

**Comment by GBH** [comment]
@chamnap do you mind making a PR that fixed this issue?

**Comment by GBH** [comment]
This a blog issue. Will deal with this there.
