### ISSUE TITLE
Rails5: Preview button disables Preview and Update buttons

### ISSUE THREAD

**Issue by robmathews** [comfy/comfortable-mexican-sofa#747]
This seems to be new to Rails5, but when you press on the Preview button when editing a page (like for a url like cms/sites/1/pages/4/edit ), the "disabled" attribute is added to both the Preview and Update buttons and the page no longer functions.

Latest rails5 version, latest comfy:

* ruby 2.3.1p112
* rails 5.0.1
* comfortable_mexican_sofa 1.12.10

**Comment by GBH** [comment]
Is that Rails going that or Bootstrap?

**Comment by robmathews** [comment]
That's a really good thought. We also upgraded bootstrap as part of the rails5 upgrade.

I see that CMS wants:

      bootstrap-sass (>= 3.2.0)
      bootstrap_form (>= 2.2.0)

and we ended out with 

    bootstrap-sass (3.3.7)
    bootstrap_form (2.5.2)

So maybe there is something in there that I can find.

**Comment by robmathews** [comment]
Ok, so not sure who the culprit is, but playing around with various versions of bootstrap in [clean sample project](https://github.com/rmccown/comfy_testing) () does not reproduce the problem. 

Some magic part of our project is changing the button definition from:
`<input` type="submit" name="preview" value="Preview" class="btn btn-default">
to: 
`<input` type="submit" name="preview" value="Preview" class="btn btn-default" data-disable-with="Preview">

We are currently examining all the things. I'll report back here if we ever find the culprit.

**Comment by robmathews** [comment]
Additionally, you can fix that Preview button by changing the code to 

`  = form.submit t('.preview'), :name => 'preview', :id => nil, :class => 'btn btn-default', :data => { disable_with: false }
`
