### ISSUE TITLE
Redactor II integration does not work

### ISSUE THREAD

**Issue by sapraaman** [comfy/comfortable-mexican-sofa#749]
Instructions provided at https://github.com/comfy/comfortable-mexican-sofa/wiki/Integrating-Redactor-II-With-Comfy--1.12.9-or-Later do not seem to work.

I am using latest CMS and purchased redactor to integrate. After following all the instructions, the default toolbar is not coming up properly. Please see https://screencast.com/t/TvunICBTtMev. See the missing B/I buttons in toolbar, also "Format" button is missing​. Dropdown menu on clicking "Link" shows empty menu item instead of "Insert Link".

Any thoughts ? Am I missing something ?

**Comment by GBH** [comment]
I don't have redactor 2 to test, but do you see anything odd when you inspect for requests for missing assets? I'm just guessing there's a wrong url to something like js or css.

**Comment by sapraaman** [comment]
No, there was no error in console, or 404 or any other error

**Comment by GBH** [comment]
Send me redactor oleg at khabarov.ca and I'll see what is going on.

**Comment by sapraaman** [comment]
Sent

**Comment by GBH** [comment]
Sent you rails app with redactor 2 hooked up. Should be good. Still gotta change file/image linking as redactor2 changed those. I think wiki entry here should be helpful. 

I'm more than willing to add Redactor 2 as part of CMS, but I just don't have money to do so. Last time I checked Imperavi wanted $1500 for "OEM" license there you can bundle it with open-source projects. Now it's not even a thing they have listed on their site. So maybe it's not even an option anymore. 

<img width="940" alt="screen shot 2017-01-24 at 11 42 54 am" src="https://cloud.githubusercontent.com/assets/78363/22264014/5e8b9ea4-e22b-11e6-9f98-f572995ce215.png">

**Comment by sapraaman** [comment]
Yes, the changes you have made work. 

However, as you have indicated, files and images do not work. The [example files controller](https://gist.github.com/mattmueller/0b933bf64b7bc1d419cc369ea48a1d11) does not work. When files are uploaded, line 102 @site.files... gives error.  Will you be able to look into it?

**Comment by GBH** [comment]
Example controller works if you change line 51 to return tuple with `:url` and `:id` as per wiki entry.

Also Internet says that Froala is better than Redactor now: https://www.froala.com/wysiwyg-editor Those guys have OEM licence. Looks pretty nice.

**Comment by GBH** [comment]
Closing this. 

CMS 2.0 still using Redactor 1 as it works just fine (and that's the only one I have licence for anyways). It's fully integrated with file uploading and stuff. So unless you have a really good reason I'd still with bundled Wysiwyg.
