### ISSUE TITLE
Enabling PDF Docs upload

### ISSUE THREAD

**Issue by Daniel-ltw** [comfy/comfortable-mexican-sofa#750]
Does anyone have any idea how this could be achieve? 

The file model seems to be written in a way that it only allow images.

**Comment by GBH** [comment]
No, files are files. It has some handling for images to create thumbnails, but any file can be uploaded. Are you getting an error of some kind?

**Comment by Daniel-ltw** [comment]
A mistake on our part. 

Nginx/Apache configuration is disabling the users from uploading files larger than certain size.
