### ISSUE TITLE
Uncaught TypeError: Cannot set property 'wysiwyg' of undefined after adding redactor

### ISSUE THREAD

**Issue by JohnSmall** [comfy/comfortable-mexican-sofa#751]
Now that I've installed Redactor, and followed the instructions to integrate it I'm getting this error

    Uncaught TypeError: Cannot set property 'wysiwyg' of undefined

This is because the line in etc/admin/application.js.coffee

    window.CMS.wysiwyg = ->

gets called before window.CMS has been set up.

Also I can't get the Redactor editor to work unless I precompile assets. Any idea why?

**Comment by GBH** [comment]
Are we talking about Redactor2, or the one that comes with CMS?

**Comment by JohnSmall** [comment]
Hi, thanks for the quick response. Especially as it's the weekend. Much appreciated :-)

>>
Are we talking about Redactor2, or the one that comes with CMS?
>>
Is there one that comes with CMS? 

I followed the instructions in [Replacing default wysiwyg editor with redactor](https://github.com/comfy/comfortable-mexican-sofa/wiki/Replacing-default-wysiwyg-editor-with-redactorl) paid for Redactor. As I downloaded it after 5th Feb 2017, it's version 2.0. Should I switch to an earlier version?

But I am using CMS 1.12.9, not 1.12.2 as it says in the instructions. If it's only a point release it shouldn't be breaking features. 

The other thing that happens is that with that code in place it completely blows out jQuery, because the script runs before the main application.js, and therefore blows up and application.js doesn't load jQuery.  

If I have assets precompiled that fixes things. But I shouldn't need to to that in development mode. 

Testing loses it completely, so all Cucumber scenarios that rely on jQuery then fail.

What's the critical difference between 1.12.2 and 1.12.9 that makes using Redactor impossible? There must be a workaround.

**Comment by GBH** [comment]
CMS got Redactor 1 bundled in v1.12.5  

I really don't know what benefits Redactor2 has over 1 other than being a rewrite to be more modular/faster/etc. As far as features go, whatever comes with CMS out of the box should be fine. 

So don't try replacing anything yet, and give built-in wysiwyg a try.

**Comment by JohnSmall** [comment]
I just read through the code and I see that CMS already includes Redactor 10.2.5 So now I'm totally confused. If Redactor is included with CMS, why is there a page in the Wiki that advises me to pay for and download it from Imperavi, and why is does the code sample on that page that pretty much match what's already in app/assets/javascripts/comfy/admin/cms/base.js.coffee. 

Is that page out of date and should be removed?

**Comment by GBH** [comment]
Yes, it is confusing and irrelevant wiki page. I nuked it now.

**Comment by JohnSmall** [comment]
Thanks I just closed this issue
