### ISSUE TITLE
Oh dear, Uncaught ReferenceError: CMS is not defined

### ISSUE THREAD

**Issue by JohnSmall** [comfy/comfortable-mexican-sofa#752]
I just closed [issue 751](https://github.com/comfy/comfortable-mexican-sofa/issues/751). Removed all the extra code I'd added to use Redactor, as it's included in 1.12.5+, and now I get a stack of errors when loading

     Uncaught ReferenceError: CMS is not defined
     Uncaught ReferenceError: CodeMirror is not defined
     Uncaught TypeError: Cannot read property 'DEFAULTS' of undefined
     Uncaught ReferenceError: mOxie is not defined

So I'm guessing that something has to be done in the initialization file to tell CMS not to use CodeMirror, but to use Redactor instead. I see that the classes on the text areas are set correctly data-cms-rich-text=true. But because the Javascript is failing on load, all I see is the raw html in the edit field. And the background from the main site bleeds through on the left behind the "Sites","Layouts" etc menu options.

What's the secret configuration setting?

**Comment by GBH** [comment]
Try installing CMS on a fresh Rails app. I'm guessing you have some remnant files messing things up.

**Comment by JohnSmall** [comment]
Mmm, can't really do that. This is a long running website with lots in it.

What I can do is create a new application, add CMS, and look carefully for any differences so I can see what I need to delete from the existing app.

**Comment by JohnSmall** [comment]
Ok, I did that. Luckily I had a recently created new website, using CMS 1.12.9 I could refer to. So I did this

     cp /directory_to_other_site/app/assets/javascripts/comfy app/assets/javascripts
     rm -rf rm -rf app/assets/javascripts/comfortable_mexican_sofa/

And the copied the newer config/initializers/comfortable_mexican_sofa.rb over the old one. That did the trick. 

You might want to add a page about how to upgrade from an older CMS version to the newer one

I thought semantic versioning meant that a 1.12.x release should only be fixes to 1.12 and shouldn't break anything. New features would be 1.13.0 and breaking changes would be 2.0.0. 

Replacing CodeMirror with Redactor would be a new feature therefore 1.13.0 and changing the naming of directories so that things break would have to be 2.0.0

**Comment by JohnSmall** [comment]
The fix works but please add instructions for upgrading from earlier versions of CMS to 1.12.9

**Comment by JohnSmall** [comment]
Oh dear. It only works in development mode if you've not precompiled assets. I'm reopening this.

If I precompile assets, as I would when deploying to staging or production then I'm back to where I started. With

      Uncaught ReferenceError: CMS is not defined
 
Also if I precompile assets for e.g. staging, on my development machine, and then start rails s in development mode then again it doesn't work
  
I'm guessing that there's a critical configuration option that has to be set somewhere.

**Comment by JohnSmall** [comment]
Still can't get that working. Though I did discover 2 things
1) If I create a completely new site I don't have the problem
2) If I reload the admin page the problem goes away.

I'll hazard a guess that it's something to do with the order assets are loaded. Though it's a complete mystery because as far as I can see the assets are being loaded in the same order in a new site as in the site I've got problems with.

**Comment by GBH** [comment]
It's very difficult to diagnose something like that for me as host app can have non-obvious settings or overrides that may affect CMS related stuff. If you could grant me access to the repo I could take a look, but there's no guarantee that I can find the problem.

**Comment by DamengRandom** [comment]
If you were a mac user, please type Command + F and then type the CMS keyword to find the CMS, if you find the keyword CMS inside the file, and you didn't import CMS npm package, please type import CMS from 'netlify-cms' to import the package inside the file.

Problem solved ...
