### ISSUE TITLE
Rails 5.0.2 and rails generate comfy:cms error

### ISSUE THREAD

**Issue by ElliotGage** [comfy/comfortable-mexican-sofa#755]
Have a clean rails 5.0.2 app.
I've installed bundle with gem 'comfortable_mexican_sofa', '~> 1.12.0

rails generate comfy:cms bombs out. See below

rails generate comfy:cms --trace
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-5.0.2/lib/rails/app_loader.rb:40: warning: Insecure world writable dir /root/.rbenv/versions in PATH, mode 040777
Version: 2.0.1

Usage: spring COMMAND [ARGS]

Commands for spring itself:

  binstub         Generate spring based binstubs. Use --all to generate a binstub for all known commands. Use --remove to revert.
  help            Print available commands.
  server          Explicitly start a Spring server in the foreground
  status          Show current status.
  stop            Stop all spring processes for this project.

Commands for your application:

  rails           Run a rails command. The following sub commands will use spring: console, runner, generate, destroy, test.
  rake            Runs the rake command
rails aborted!
Don't know how to build task 'rails' (see --tasks)
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task_manager.rb:58:in `[]'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:151:in `invoke_task'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/root/.rbenv/versions/2.2.6/lib/ruby/gems/2.2.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'

**Comment by GBH** [comment]
It's almost like it's running `rake rails generate` for some reason. Can you confirm that other generators work? Like `rails generate model`?

**Comment by ElliotGage** [comment]
Oh, thank you! Nothing to do with Comfortable!!
Oh, this is related to https://github.com/rails/rails/issues/26056.
Windows 10 bash for windows.
Fix is to not use spring and listen
rails new --skip-spring --skip-listen

Thanks for your help GHB!
