### ISSUE TITLE
Pagination for the files page

### ISSUE THREAD

**Issue by Daniel-ltw** [comfy/comfortable-mexican-sofa#761]
Has someone previously raise this? 

I have not seen this through the search. 

Can someone actually help in this aspect?

**Comment by GBH** [comment]
What's the issue exactly? Files are paginated.

**Comment by Daniel-ltw** [comment]
Do we need to install WillPaginate or Kaminari to enforce pagination?

**Comment by GBH** [comment]
Yes. You need to put either gem in your Gemfile.

**Comment by Daniel-ltw** [comment]
Cool. 

Will close this ticket then.
