### ISSUE TITLE
Rendering page_file image in partial is always ""

### ISSUE THREAD

**Issue by donni106** [comfy/comfortable-mexican-sofa#762]
I wonder how to render an image in my partial. Currently it only renders "".

```
>> cms_block_render("content.image_1")
=> ""
>> cms_block_content("content.image_1")
=> ""
```

I defined `{{ cms:page_file:content.image_1:field }}` in my layout and uploaded an image on my page.
Then I want to render the following:

```
  .container
    .col-md-8
      %img{ src: cms_block_content("content.image_1") }
    .col-md-4
      %div
```

Where is my mistake?
Thanks.

**Comment by GBH** [comment]
Hmmm. Doesn't look wrong to me. Double-check that you have that record saved on the database. Maybe image saving silently failed?

**Comment by donni106** [comment]
From wiki:
All you need to do is add this tag in place of the src content:
```
{{ cms:page_file:header }}
```
This will output the URL of the uploaded file.

Defining `{{ cms:page_file:content.image_1 }}` (without :field) in my layout let me output the URL per `%img{ src: cms_block_content("content.image_1") }`. The Problem is, that it is also rendered automatically as string on the page. Therefore i wanted to use `{{ cms:page_file:header:field }}        # Won't render anything out. Access via cms_page_content helper` from the wiki. But then it results in "".

I tried a work around with `<div class="hidden">{{ cms:page_file:teaser.image }}</div>` in my layout to hide the automatic render but this is not good for me in any case.

As the helper works for the one way, image uploading is successful.

Do you understand where the problem is? What can I do to render the image uploaded per ``{{ cms:page_file:header:field }}`?

**Comment by GBH** [comment]
Try `cms_block_content("content.image_1").file.url`

It's some weird combination of page files and them being a field. I'll investigate why it's so clunky in this case.

**Comment by donni106** [comment]
Does not work unfortunately.

`cms_block_render("content.image_1").file.url` => `undefined method `file' for "":ActionView::OutputBuffer`
`cms_block_content("content.image_1").file.url` => `undefined method `file' for "":String`

So I have to use a workaround with having html and tags in my layout instead of having it in partials in my application code, where i would have more opportunities.

Would like to help or give more infos on this for fixing it.

**Comment by GBH** [comment]
That's really odd. Do some debugging. Do `bundle open comfortable_mexican_sofa` and navigate here: https://github.com/comfy/comfortable-mexican-sofa/blob/master/app/helpers/comfy/cms_helper.rb#L54

Do some raises and see what data it's pulling out. `cms_block_content` should be returning paperclip record (I did get it working locally) so I have no idea why it doesn't work for you.

**Comment by GBH** [comment]
In 2.0 files are handled from ActiveStorage so everything is a bit different. Closing this for now.
