### ISSUE TITLE
Duplicating sites does not duplicate their content

### ISSUE THREAD

**Issue by spencerldixon** [comfy/comfortable-mexican-sofa#763]
I have a multilingual website with a site for English, French and recently Spanish. Checking the mirror site box copies the layouts and pages but without their content. 

Is there a way to get it to copy the content too? An option for this in future would be really helpful for those copying large sites who could then just change the content they needed rather than all of it.

Is there any way to do what I'm looking for?

**Comment by GBH** [comment]
Mirroring is gone as of 2.0. Pages can be translated directly.
