### ISSUE TITLE
method app_layouts_for_select in 1.12.10 breaks compatibility with comfy-blog

### ISSUE THREAD

**Issue by spacewaffle** [comfy/comfortable-mexican-sofa#764]
I tried using the latest version of comfortable-mexican-sofa and comfy-blog together. Looks like the above method was changed from taking 0 arguments to taking 1 argument. This breaks comfy-blog's compatibility when making a new blog in the admin.

**Comment by GBH** [comment]
Blog gem is being ignored for a while now. I'll get it up to speed after I'll release cms 2.0. 

It's a bug in the Blog though: https://github.com/comfy/comfy-blog/blob/master/app/views/comfy/admin/blog/blogs/_form.html.haml#L5 

Seems like that method doesn't even belong on the model level as it relies on  ActionView::LookupContext::ViewPaths stuff. 

For the time being just replace the view to include this: `options = Comfy::Cms::Layout.app_layouts_for_select(lookup_context.view_paths)`

**Comment by spacewaffle** [comment]
Gotcha thanks. I ended up just downgrading my Comfortable Mexican Sofa version to 1.12.7 and things are working fine for now.

**Comment by GBH** [comment]
Closing. Will be updating Blog to work with CMS 2.0 shortly.
