### ISSUE TITLE
render_cms_template doesn't support views & layouts sharing data via instance variables

### ISSUE THREAD

**Issue by morgant** [comfy/comfortable-mexican-sofa#765]
`render_cms_template` (and maybe `render_cms_page`?) doesn't support layouts & views sharing data via instance variables because it renders blocks & content using `render_to_string` which can read instance variables, but changes made to instance variables are not preserved.

In my case, I'm using the [gretel](https://github.com/lassebunk/gretel/) gem which uses calls to `breadcrumb` in the view, then a call to `breadcrumbs` in the layout to render the breadcrumbs. It does this through an `@_gretel_renderer` instance variable. This works fine using standard rails `render layout: 'some-layout'`, but not `render cms_layout: 'some-layout'`.

**Comment by GBH** [comment]
Rendering cms_template doesn't work as a regular template as content construction doesn't happen on the view layer. You need to access that `@gretel` variable in a `{{cms:helper}}` or `{{cms:partial}}`. How do you have it set-up?

**Comment by morgant** [comment]
@GBH Thanks for your response and for all your work on CMS!

We had one Controller method that was performing error handling and calling `render cms_template: :some_template`, where :some_template had our main app layout set in its "App Layout" field (and our app layout is what contains the call to `breadcrumbs`). So, it wasn't getting called through `{{cms:helper}}` or `{{cms:partial}}` in this particular case. I switched it to `render layout: :our_app_layout` and to bypass CMS and just render our app layout directly, which is fine since it was really just an error handler.

Most of our pages get handled by CMS (with most of the actual views being included via `{{cms:partial}}`) and work fine with Gretel. So, I have a workaround, but if there's a better way to handle this I'm all ears.

**Comment by GBH** [comment]
I think when you're rendering template like that you're not passing instance variables to it. Method signature is like this: `def render(options = {}, locals = {}, &block)`. So you should be able to pass instance variables explicitly.

So you can try: `render({cms_layout: "some_layout"}, {gretel: "something"})`
