### ISSUE TITLE
CMS Working Demo

### ISSUE THREAD

**Issue by grichardomi** [comfy/comfortable-mexican-sofa#766]
I'm having difficulty implementing CMS basic functionalities. Can someone point me to working demo app? Thanks!

**Comment by Daniel-ltw** [comment]
What functionality are you trying to work with? 

If you do follow the installation, you should be able to get it working with rails 4 easily.

**Comment by GBH** [comment]
@grichardomi what issues are you having? You could also just clone https://github.com/comfy/comfy-demo and it should work immediately.

**Comment by grichardomi** [comment]
I'm having issues related the use of tags integration into my app.. Would like to use CMS for static content generation.

**Comment by GBH** [comment]
You gotta be more specific here.
