### ISSUE TITLE
Migration from 1.x to 2.x?

### ISSUE THREAD

**Issue by glebm** [comfy/comfortable-mexican-sofa#776]
There seem to be quite a few changes in the 2.x release (translations, snippets, file uploads, etc). Has anyone migrated and is there a migration they can share?

**Comment by GBH** [comment]
There's no easy simple migration from 1.12 to 2.0. Biggest change is move from Paperclip to ActiveStorage. Can't really automatically migrate that. Also mirrored sites are gone and replaced with page translations. Pretty different...

I'm thinking that this process is the easiest one:

- In 1.12 export all content to CMS Fixture files via `rake comfortable_mexican_sofa:fixtures:export FROM=site_identifier TO=folder_name`
- Nuke existing 1.12 CMS related db tables and Paperclip attachment files wherever they might be.
- Edit files into new CMS Seeds format like this: https://github.com/comfy/comfortable-mexican-sofa/tree/master/db/cms_seeds/sample-site (I probably need to add wiki page about file structure, but it's pretty simple)
  - change tags from old `{{cms:foo:bar:red:green}}` format to the new `{{cms:foo bar, red: green}}`
  - if you attached files via WYSIWYG editor prepare for the pain of trying to locate and re-link those files later.
- Install 2.0
- Import CMS Seeds with `rake comfy:cms_seeds:import[folder_name,site_identifier]`

**Comment by GBH** [comment]
Added wiki entry: https://github.com/comfy/comfortable-mexican-sofa/wiki/HowTo:-Upgrade-CMS-From-1.12-to-2.0

And expanded entry on CMS Seeds: https://github.com/comfy/comfortable-mexican-sofa/wiki/Docs:-CMS-Seeds
