### ISSUE TITLE
Image uploading within wysiwyg not working

### ISSUE THREAD

**Issue by romdim** [comfy/comfortable-mexican-sofa#790]
*Note:* For general questions and feature requests please leave a message
on Gitter: https://gitter.im/comfy/comfortable-mexican-sofa

### Expected behavior
I should have been able to upload an image through wysiwyg image button.

### Actual behavior
An error is thrown in javascript as the CMS.file_upload_path is interpreted as undefined.

### Steps to reproduce
Install locally, run everything as stated and layout should include `{{ cms:wysiwyg content }}`.
Then try to create a new page and in the text try to upload an image. It should fail

I have already figured out why this happens and will create a pull request.
Spoiler.. this in /app/assets/javascripts/comfy/admin/cms/base.js.coffee:
```
"#{CMS.file_upload_path}?source=redactor&type=image&#{params}"
```
Should become like this:
```
$('.cms-files-modal').data('iframe-src') + "?source=redactor&type=image&#{params}"
```

### System configuration
**Rails version**: 5.2.0.beta2

**CMS version**: 2.0.7

**Ruby version**: 2.5.0

**Comment by GBH** [comment]
Interesting. Do you see the same issue in https://github.com/comfy/comfy-demo ?

There are few things that rely on `CMS` js object. Although it's probably better to move it into html meta tags.

**Comment by romdim** [comment]
Hm, that's weird! Comfy-demo seems to be working just fine!
What would be the differences?

**Comment by GBH** [comment]
Demo app, is there just to confirm if everything works as advertised. It's a good reference.

So there's something slightly different in your app that breaks javascript in some way. Are you getting any other js errors in console?

**Comment by romdim** [comment]
Steps for reproducing.
`rails new app`
Added gem definition to my Gemfile:
`gem 'comfortable_mexican_sofa', '~> 2.0.0'`
```
bundle install
rails g comfy:cms
rails db:migrate
rails s
```
Navigate to http://localhost:3000
then create a new site and a new Layout with `application` App Layout and `{{ cms:wysiwyg content }}` in the content.
When I go to create a new page now and try to upload an image it fails.

The errors are:
```
new:241 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https:". Either the 'unsafe-inline' keyword, a hash ('sha256-K+Ak/vnYxJHWOTpaj4oWxcaaUkXmAA/kLXw00rG3YD8='), or a nonce ('nonce-...') is required to enable inline execution.
```
```
jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:9567 GET http://localhost:3000/admin/sites/1/pages/undefined?source=redactor&type=image&_=1515618860715 404 (Not Found)
send @ jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:9567
ajax @ jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:9174
load @ imagemanager.self-aeded7055fc27c237e6386a18270eaa0b3056a13b76ce741090e306163227170.js?body=1:27
load @ redactor.self-7e72c3b242d5a0355d5cb34ec8819838c2a9329732bad35e3214ba4cfb0627f9.js?body=1:6634
show @ redactor.self-7e72c3b242d5a0355d5cb34ec8819838c2a9329732bad35e3214ba4cfb0627f9.js?body=1:3655
onClickCallback @ redactor.self-7e72c3b242d5a0355d5cb34ec8819838c2a9329732bad35e3214ba4cfb0627f9.js?body=1:1658
onClick @ redactor.self-7e72c3b242d5a0355d5cb34ec8819838c2a9329732bad35e3214ba4cfb0627f9.js?body=1:1646
(anonymous) @ redactor.self-7e72c3b242d5a0355d5cb34ec8819838c2a9329732bad35e3214ba4cfb0627f9.js?body=1:1602
proxy @ jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:497
dispatch @ jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:5207
elemData.handle @ jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:5015
```
```
redactor.self-7e72c3b242d5a0355d5cb34ec8819838c2a9329732bad35e3214ba4cfb0627f9.js?body=1:9018 POST http://localhost:3000/admin/sites/1/pages/undefined?source=redactor&type=image&authenticity_token=kxOk6ZKn5V8cAmb1ET6nxeKSbKH3Tn83Df1vJIz%2FWeVGjzKjHK1THqUm0psCzEWVs47E9%2FdKJJPN2LHggUgxsg%3D%3D 404 (Not Found)
```

The first error is I guess because of serving through http.
The 2 next are 404s because it tries to access http://localhost:3000/admin/sites/1/pages/undefined where undefined should have been the image upload path.

**Comment by GBH** [comment]
I think you're hitting this issue: https://github.com/comfy/comfortable-mexican-sofa/issues/619

I'm moving that stuff into meta tags. Will ping you when it's done.

**Comment by romdim** [comment]
Sure thing! Thanks!

I've managed to resolve it for now by using the custom.js.coffee and altering all `"#{CMS.file_upload_path}?source=redactor&type=image&#{params}"` lines with `$('.cms-files-modal').data('iframe-src') + "?source=redactor&type=image&#{params}"` which does the trick!

So I'm not entirely sure that #619 is the issue here, but can't tell for sure.

**Comment by GBH** [comment]
I'm betting if you try to upload files directly from the side nav there, you're going to have similar issues. There's a few inline scripts that are not running for you, so it's all borked.

**Comment by romdim** [comment]
Nope, this works! I can upload a file just fine! But I can't access it through the wysiwyg editor.

**Comment by GBH** [comment]
That's confusing then. Pull down master branch and see if works not for you. I moved those `CMS` things into meta tags: https://github.com/comfy/comfortable-mexican-sofa/commit/6f2d44c641ffb173edecbf58b1ff568fc4c29591

**Comment by romdim** [comment]
The master branch already worked for me as it was, the gem was not working when I added it to a new repo of mine.
Maybe you should draft a new release?

**Comment by romdim** [comment]
Ok, let me check first by using it by source. Responded without thinking first.. :P

**Comment by GBH** [comment]
2.0.7 didn't work but master branch before my last commit did? That makes no sense. There were no changes that would affect JS in anyway.

**Comment by romdim** [comment]
What I meant was that it worked when I used comfortable-mexican-sofa not as a gem but as a rails repo.

**Comment by romdim** [comment]
How can I reference the master branch in Gemfile?
I've tried:
`gem 'comfortable-mexican-sofa', git: 'https://github.com/comfy/comfortable-mexican-sofa.git', ref: '6f2d44c'` or `gem 'comfortable-mexican-sofa', git: 'https://github.com/comfy/comfortable-mexican-sofa.git', branch: 'master'` or `gem 'comfortable-mexican-sofa', git: 'https://github.com/comfy/comfortable-mexican-sofa.git'`

But I get:
```
Could not find gem 'comfortable-mexican-sofa' in https://github.com/comfy/comfortable-mexican-sofa.git (at 6f2d44c@6f2d44c).
The source does not contain any versions of 'comfortable-mexican-sofa'
```

**Comment by romdim** [comment]
Argh! The dashes!

**Comment by GBH** [comment]
`gem "comfortable-mexican-sofa", github: "comfy/comfortable-mexican-sofa"`

and then

`bundle update`

**Comment by romdim** [comment]
gem "comfortable_mexican_sofa", github: "comfy/comfortable-mexican-sofa"

**Comment by romdim** [comment]
Yes, fixed! That was the issue indeed, all the errors vanished 👍

**Comment by GBH** [comment]
Good stuff. I'll remove that last inline js and will publish 2.0.8 shortly.

**Comment by romdim** [comment]
Cheers! Thanks again for everything!
