### ISSUE TITLE
undefined method site' for #<Comfy::Cms::Translation:0x00007f3d1bbf24a8>

### ISSUE THREAD

**Issue by metekabak** [comfy/comfortable-mexican-sofa#791]
### Expected behavior
I should use snippets in layout

### Actual behavior
`undefined method `site for #<Comfy::Cms::Translation:0x00007f3d1bbf24a8>`

### Steps to reproduce
Create a snippet and use it on layout, and change the language

### System configuration
**Rails version**:
5.2
**CMS version**:
2.0.8
**Ruby version**:
2.5

**Comment by GBH** [comment]
Yeap. I can see the error. Will fix.

**Comment by metekabak** [comment]
i did add the gem with git,

english version of site is fixed. but i throws another one right now

```
ComfortableMexicanSofa::Content::Tag::Error in Comfy::Cms::ContentController#show
Missing identifier for fragment tag
```

Extracted source (around line #20):
```
    unless @identifier.present?
      raise Error, "Missing identifier for fragment tag"
    end

    @namespace  = @options["namespace"] || "default"
```

**Comment by GBH** [comment]
Can you please paste what your cms layout looks like? This seems to be a malformed tag.

**Comment by metekabak** [comment]
I can't even edit or see the page code

![image](https://user-images.githubusercontent.com/3997926/34927055-886c8934-f9c4-11e7-96d3-feb7c6116bf8.png)

**Comment by GBH** [comment]
Yeah. Looks like a malformed tag. I thought I had a rescue for that. Will fix.

**Comment by metekabak** [comment]
Possible, thanks

**Comment by GBH** [comment]
Should be fixed. Your problem is that you have tag defined in the layout like `{{cms:markdown}}` instead of `{{cms:markdown something}}`. You need to hunt it down.

**Comment by GBH** [comment]
@metekabak Did it solve your issue? Can this be closed?

**Comment by metekabak** [comment]
Kind of, it gives the error, But i can't edit the page now 😄 

![image](https://user-images.githubusercontent.com/3997926/34993624-f6a0c60e-fae1-11e7-8400-97ae8038b5c7.png)

**Comment by metekabak** [comment]
Ok I found the problem, i made the identifier problem on layouts,

Couldn't be nice if we tell to user the name of layout?

**Comment by metekabak** [comment]
I got plan the turn this into enduser cms

**Comment by GBH** [comment]
👍 I'll try to make error a bit more useful.
