### ISSUE TITLE
Content tag for partial doesn't render with quotes

### ISSUE THREAD

**Issue by chadcodes** [comfy/comfortable-mexican-sofa#795]
### Expected behavior
Using the cms:partial tag I expect the reference to the partial and local_vars should be inside ""

### Actual behavior
This breaks the page with an error:
`ComfortableMexicanSofa::Content::ParamsParser::Error in Comfy::Cms::ContentController#show`

### Steps to reproduce
In any page add a content tag for partial using quotes:
`{{ cms:partial 'path/to/partial', local_var: 'value' }}`

### System configuration
**Rails version**: 5.2.0.rc1

**CMS version**: 2.0.11

**Ruby version**: 2.5.0p0

**Comment by GBH** [comment]
I know what's going on. Quotes inside wysiwyg are not your regular quotes. They get converted into fancy quotes. `“foo/bar”` is not the same as `"foo/bar"`. Parser obviously chokes on that. I don't want to mess with editor, so I'll deal with those fake quotes during tag parsing.

**Comment by chadcodes** [comment]
Let me know if I can help test in anyway.  I was digging into the parser a little but not sure I would know how to fix it at this point.

**Comment by GBH** [comment]
Fixed in master. Doing straight gsub to replace quotes to proper ones. I don't think this can backfire in a bad way.
