### ISSUE TITLE
rails_blob_path always renders with only_path: true

### ISSUE THREAD

**Issue by glebm** [comfy/comfortable-mexican-sofa#800]
Does that actually work for files on an external host? E.g. S3 / CloudFront, Google Cloud Storage

**Comment by GBH** [comment]
Not sure. Don't have app that uses S3. I talked to somebody who does, and it seems that it works fine if storage is configured to use cloud hosts. For local storage it doesn't cram full though. Please confirm though.

**Comment by glebm** [comment]
Closing this for now and will re-open if there are any issues
