### ISSUE TITLE
Tag form group labels should be associated with the respective inputs

### ISSUE THREAD

**Issue by glebm** [comfy/comfortable-mexican-sofa#801]
Using the `for` attribute on the label.
This improves usability, accessibility, and makes system tests easier to write.

**Comment by GBH** [comment]
Yes. Page fragments don't put `id` on inputs or `for` attribute on labels. Should be easy enough to add via `lib/form_builder.rb`

**Comment by GBH** [comment]
All labels properly put inputs into focus. The only exceptions are codemirror and redactor editors. Not unexpected though.
