### ISSUE TITLE
Why is the files widget an iframe?

### ISSUE THREAD

**Issue by glebm** [comfy/comfortable-mexican-sofa#807]
Did you encounter problems with just `render partial: ..., layout: false`?

**Comment by GBH** [comment]
I think the same can be done with a partial. Iframe was a PR from many moons ago. Very simple implementation. I think it's still good if we even put filtering/searching in there. Easier than doing ajax.

**Comment by glebm** [comment]
It is very easy to do the kind of ajax we'd need for filtering and searching with modern APIs though. On the other hand, the current hackish drag'n'drop implementation is something I'd like to replace with a simple one.

**Comment by GBH** [comment]
If you're willing to nuke iframe, I'm all for it.
