### ISSUE TITLE
cms_fragment_render not rendering fields defined with 'render: false'

### ISSUE THREAD

**Issue by kirichkov** [comfy/comfortable-mexican-sofa#820]
### Expected behavior

`cms_fragment_render()` should return the field's contents with tags expanded.

When a field is defined with `render: false` it shouldn't render on screen where it is defined in the layout, but it should be possible to manually render the content using `cms_fragment_render()` 

### Actual behavior
`cms_fragment_render()` returns an empty string ("")

### Steps to reproduce

1. Define a minimal layout in cms:
````
{{ cms:textarea head, render: false }}
{{ cms:wysiwyg content }}
````

2. In `app/views/layout/application.html.haml` have:

````haml
!!!
%html
  %head
    = cms_fragment_render(:head)
  %body
    = yield
````

if `render: false` is **not set** (`{{ cms:textarea head }}`)  the content in the field "head" for the page is output twice - once in the <head> section from `cms_fragment_render()` and once in the body where `yield` is.

if `render: false` is set, the content is not output anywhere on the page because cms_fragment_render() returns an empty string.

### System configuration
**Rails version**:
5.2.0

**CMS version**:
2.0.14

**Ruby version**:
2.5.1

**Comment by GBH** [comment]
Yeah. That looks like an issue. Will take a look.

**Comment by kirichkov** [comment]
Thanks, I tried to follow it down the code, but I couldn't find where the issue stems from.

Just as a use case: I'm trying to embed into CSS the urls of attached images.

**Comment by kirichkov** [comment]
I confirm! The fix is working! Thanks!
