### ISSUE TITLE
Missing context when using cms_snippet_render

### ISSUE THREAD

**Issue by GBH** [comfy/comfortable-mexican-sofa#823]
If snippet content has tags that rely on context to be rendered out, we get an exception like:

Snippet content:

```
{{ cms:file_link 123, as: image }}
```
Error:
```
undefined method `files' for nil:NilClass
lib/comfortable_mexican_sofa/content/tags/file_link.rb:43:in `file_record'
```
In:
```ruby
def file_record
  @file_record ||= context.site.files.detect { |f| f.id == identifier.to_i }
end
```

Maybe context needs to be snippet object in this case.

**Comment by GBH** [comment]
@kirichkov this should fix your file linking issue in snippets. Confirm that it works for you and I can release new version.

**Comment by kirichkov** [comment]
Working! Thanks!

Do you think it's possible to (easily) add tag expansion for the layout's CSS/JS fields as well? Perhaps even just to include links to files in both fields?

**Comment by GBH** [comment]
Not sure about adding parsing/rendering to layout css/js. You can give a try and submit a PR though.
