### ISSUE TITLE
cms:datetime fails to pass empty string to strftime

### ISSUE THREAD

**Issue by kbroderick** [comfy/comfortable-mexican-sofa#827]
### Expected behavior
When cms:datetime is given any strftime parameter, that parameter is passed to strftime. E.g. {{ cms:datetime foo, strftime:"" }} should pass an empty string ("") to strftime as the format string and return an empty string, as DateTime.now.strftime("") does.

### Actual behavior
The .present? check for the strftime parameter in datetime.rb treats a blank string as not present and does not pass the format string to strftime.

### Steps to reproduce
Add {{ cms:datetime foo, strftime: "" }} to a layout and note that the datetime is rendered as if not strftime value is present.

Changing datetime.rb:22 to 
`if strftime.present || (strftime.is_a?(String) && strftime.blank?)`
seems to resolve this, but I'm not sure if there are any other edge cases where string.present? returns false even though there is some string value.

### System configuration
**Rails version**:
5.2
**CMS version**:
Master
**Ruby version**:
2.5.1

**Comment by GBH** [comment]
Wonder if this is something we need to worry about. What's the use-case for wanting a `""` date format for rendering? Did it have something to do with the issue where `render: false` was broken and you were seeking a work-around?

**Comment by kbroderick** [comment]
Yes, that's where I noticed, and I can't come up with a convincing use case now that you've fixed render: false. I'll update the Wiki to indicate "non-blank" strftime option.
