### ISSUE TITLE
New pages always need a parent?

### ISSUE THREAD

**Issue by nisevi** [comfy/comfortable-mexican-sofa#828]
Hi there, I just have a question regarding the creation of new `pages` within a `site`. Is it possible to create pages that don't depend on a parent? Or I need to create a new `site` per each `page` if I want them all at the same level and not under a `parent`?

I have read the documentation [here](https://github.com/comfy/comfortable-mexican-sofa/wiki/Docs:-Pages) and it seems that I always need a parent, but I wanted your confirmation anyways :+1: 

### System configuration
**Rails version**:
rails 5.0.7

**CMS version**:
comfortable_mexican_sofa 1.12.10

**Ruby version**:
ruby 2.5.0

**Comment by GBH** [comment]
It's a website. So there's only one root page: `/` (think index.html). All other pages are children of that index. `/foo` and `/bar` are children of `/`. 

Here's a decent illustration: https://www.webpagefx.com/blog/web-design/information-architecture-101-techniques-and-best-practices/ Note that all pages are attached to "home page" or root page.
