### ISSUE TITLE
Asset precompile fails in production

### ISSUE THREAD

**Issue by stevegeek** [comfy/comfortable-mexican-sofa#832]
Due to the use of ES6 JS for the admin interface for CMS, the default `production` configuration for Rails will fail as `uglifier` doesn't support ES6 syntax. 

    Uglifier::Error: Unexpected token: punc ()). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).

Also even if we enable harmony support in uglifier we still end up having the CMS admin interface only working on browsers with ES6 support as I guess it doesnt also transpile. Maybe the JS could be built using webpacker instead of sprockets which would allow the source to be transpiled by babel?

### Expected behavior
I should be able to compile assets with `RAILS_ENV=production` 

### Actual behavior

    Uglifier::Error: Unexpected token: punc ()). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).

### Steps to reproduce

Checkout `comfy-demo` , run `SECRET_KEY_BASE=123 RAILS_ENV=production rake assets:precompile`

**Comment by GBH** [comment]
I'm open to suggestions here. While I don't really care about supporting browsers that can't do ES6 I understand that every application out there is different. Also I don't have a lot of experience dealing with all the ways to prepare assets for production environment.

Webpacker doesn't really work for Rails engines at the moment, so it's really not an option.

**Comment by GBH** [comment]
Going to close this one as adding:
```
# environments/production.rb
config.assets.js_compressor = Uglifier.new(harmony: true)
```
is the way to go as per https://github.com/lautis/uglifier
