### ISSUE TITLE
Load fontsize plugin

### ISSUE THREAD

**Issue by nisevi** [comfy/comfortable-mexican-sofa#833]
### Expected behavior
It should load the [fontsize](https://github.com/nisevi/redactor-plugins/blob/master/fontsize.js) plugin

### Actual behavior
It loads the file but no icon with functionality appears on the bar:

![image](https://user-images.githubusercontent.com/3024789/41539360-e9e4b174-730d-11e8-9b46-13a56098c78a.png)

### Steps to reproduce
I have added the `fontsize.js` here `app/assets/javascripts/comfy/admin/cms/lib`:

![image](https://user-images.githubusercontent.com/3024789/41539477-2957b00e-730e-11e8-803c-a490ff42f9a1.png)

This is the code I have in place:

```javascript
if (!RedactorPlugins) var RedactorPlugins = {};

console.log('file loaded');

(function($) {
  RedactorPlugins.fontsize = function()
  {
    return {
      init: function () {
        console.log('init function');
        var fonts = [10, 11, 12, 14, 16, 18, 20, 24, 28, 30];
        var that = this;
        var dropdown = {};

        jQuery.each(fonts, function (i, s) {
          dropdown['s' + i] = {
            title: s + 'px', callback: function () {
              that.setFontsize(s);
            }
          };
        });
        dropdown['remove'] = {
          title: 'Remove font size', callback: function () {
            that.resetFontsize();
          }
        };
        this.buttonAddFirst('fontsize', 'Change font size', false, dropdown);
      },
      setFontsize: function (size) {
        this.inlineSetStyle('font-size', size + 'px');
      },
      resetFontsize: function () {
        this.inlineRemoveStyle('font-size');
      }
    }
  };
})(jQuery);
```

As you will see I have added `console.log('file loaded');` to see is the file was being loaded and yup :+1: it is being loaded.

I also have this in place `app/assets/javascripts/comfy/admin/cms/custom.js.coffee` with just:

```javascript
#= require comfy/admin/cms/lib/fontsize
```

I will really appreciate your guidance @GBH for adding a plugin to the Redactor version this CMS is using :+1: 

### System configuration
**Rails version**: 5.0.7

**CMS version**: 1.12.10

**Ruby version**: 2.5.0

I also have read this https://github.com/comfy/comfortable-mexican-sofa/issues/586 and I was able to use it as guidance to load the file but I'm pretty much stuck now.

**Comment by GBH** [comment]
I think the bit you're missing is actually declaring plugin during editor initialization. See: https://github.com/comfy/comfortable-mexican-sofa/blob/1.12/app/assets/javascripts/comfy/admin/cms/base.js.coffee#L75

You need to overrride that method and add your plugin into `plugins` key.

**Comment by nisevi** [comment]
@GBH ok I think I'm a step closer I have been able to add the button for changing the font size, but! the dropdown is not working. 

I have coded this so far here `app/assets/javascripts/comfy/admin/cms/lib/fontsize.js`:

```javascript
if (!RedactorPlugins) var RedactorPlugins = {};

(function($) {
  RedactorPlugins.fontsize = function()
  {
    return {
      init: function () {
        var fonts = [10, 11, 12, 14, 16, 18, 20, 24, 28, 30];
        var that = this;
        var dropdown = {};

        jQuery.each(fonts, function (i, s) {
          dropdown['s' + i] = {
            title: s + 'px', callback: function () {
              that.setFontsize(s);
            }
          };
        });
        dropdown['remove'] = {
          title: 'Remove font size', callback: function () {
            that.resetFontsize();
          }
        };
        this.button.add('fontsize', 'Change font size', false, dropdown);
      },
      setFontsize: function (size) {
        this.inline.setFormat('font-size', size + 'px');
      },
      resetFontsize: function () {
        this.inline.removeFormat('font-size');
      }
    }
  };
})(jQuery);
```

As you will see I have changed `this.buttonAddFirst` by `this.button.add` when this message appeared:
![image](https://user-images.githubusercontent.com/3024789/41764003-1e4bff4a-7600-11e8-94f7-e5aaf94aa80b.png)

And after that change I got it on here:
![image](https://user-images.githubusercontent.com/3024789/41764040-39921b36-7600-11e8-9bd9-24e65867e2f0.png)

But as I said the dropdown functionality is still not working, so I'm not able to select the font size I want, I also have changed `this.inline.inlineSetStyle` by `this.inline.setFormat` and `this.inline.inlineRemoveStyle` by `this.inline.removeFormat`. I will read the code of the redactor library to see if I can get it working :+1:

**Comment by nisevi** [comment]
I have found [here](https://github.com/amineo/plugins) an updated list of the plugins that can be integrated with this CMS and the way I have found for it to work was to put the code in this way:

```javascript
(function ($) {
  $.Redactor.prototype.fontsize = function () {
    return {
      init: function () {
        var fonts = [8, 9, 10, 11, 12, 14, 16, 18, 20, 24, 28, 30, 36, 48, 60, 72, 96];
        var that = this;
        var dropdown = {};

        $.each(fonts, function (i, s) {
          dropdown['s' + i] = {
            title: s + 'px', func: function () {
              that.fontsize.set(s);
            }
          };
        });

        dropdown.remove = {title: 'Remove Font Size', func: that.fontsize.reset};

        var button = this.button.add('fontsize', 'Size');
        this.button.addDropdown(button, dropdown);
      },
      set: function (size) {
        this.inline.format('span', 'style', 'font-size: ' + size + 'px;');
      },
      reset: function () {
        this.inline.removeStyleRule('font-size');
      }
    };
  };
})(jQuery);
```

The call and code here `app/assets/javascripts/comfy/admin/cms/custom.js.coffee` remains the same :+1:
