### ISSUE TITLE
Page#url method definition seems to have changed since the wiki edit of https://github.com/comfy/comfortable-mexican-sofa/wiki/HowTo:-Creating-navigation-from-pages

### ISSUE THREAD

**Issue by dinatih** [comfy/comfortable-mexican-sofa#834]
### Expected behavior
The wiki https://github.com/comfy/comfortable-mexican-sofa/wiki/HowTo:-Creating-navigation-from-pages page should use the `url(relative: true)` 

### Actual behavior
The wiki page use the `url(:relative)` 

### Steps to reproduce
Try to call @cms_page.url(:relative) and you'll get a "wrong number of arguments (given 1, expected 0)" error

### System configuration
**Rails version**:
5.2
**CMS version**:
2.0.17
**Ruby version**:
2.4.2

**Comment by GBH** [comment]
Fixed the wiki. If you see wiki entries that are out of date, feel free to tweak them.

**Comment by dinatih** [comment]
> Fixed the wiki. If you see wiki entries that are out of date, feel free to tweak them.

Alright :)
