### ISSUE TITLE
cms:helper:asset_url no longer works

### ISSUE THREAD

**Issue by AdnanTheExcellent** [comfy/comfortable-mexican-sofa#835]
I am upgrading from ruby 2.4, rails 5.1.4, and cms branch rails5.1 to ruby 2.5.1, rails 5.2.0, cms 2.0.17. I am getting errors when i try to render some of my snippets. it seems like the line comes from:

`<a href="{{cms:helper:asset_url:8.5x11.zip}}">Color Copy (8.5"x11") Templates</a>`

I have a lot of assets in the asset pipeline (that are cached on an amazon cloudfront CDN) that are images, zip files ,etc. I used the cms::helper::asset_url to get the URLs of them. However, with the upgrade, it seems like this method no longer exists. I see that there is an asset helper but in the documentation it says it only works for css and js files?

Any idea what i should do to get this working? 

thanks.

**Comment by GBH** [comment]
That tag doesn't look like that in 2.0. Take a look at the upgrading wiki entry: https://github.com/comfy/comfortable-mexican-sofa/wiki/HowTo:-Upgrade-CMS-From-1.12-to-2.0

And the new tag structure is documented here: https://github.com/comfy/comfortable-mexican-sofa/wiki/Docs:-Content-Tags#helper

**Comment by AdnanTheExcellent** [comment]
Thanks! i didnt realize there was a section in the wiki for upgrading.
