### ISSUE TITLE
Upgrade to 2.0 - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by piotrpietrusewicz** [comfy/comfortable-mexican-sofa#841]
Hi,
I've done upgrade subject gem from 1.12 to 2.0 and additionally done upgrade rails from 4.2 to 5.2.
I followed steps by this link : https://github.com/comfy/comfortable-mexican-sofa/wiki/HowTo:-Upgrade-CMS-From-1.12-to-2.0 but got the subject error still. 
Maybe I missed something. I don't know really yet. It took me a lot of time to figure this out and nothing. Still blind. 

Has anyone ever had a similar problem ? 

It happens after rails s and going to localhost:3000 url.
Stack: 
Rails 5.2.1
Ruby 2.5.1
subject gem 2.0.17.

**Comment by GBH** [comment]
Post stack trace. Going from 4.2 to 5.2 is never that smooth.

**Comment by GBH** [comment]
Assuming you figured it out?
