### ISSUE TITLE
Render method doesn't render translation of a page

### ISSUE THREAD

**Issue by hendryiskandar** [comfy/comfortable-mexican-sofa#854]
### Expected behavior
I am trying to render a page from CMS within a rails controller as described in the documentation.

### Actual behavior
And I found out that the method render wont render the available translations of that page.

But if I call the page directly (without a rendering action in a controller, any translation can be correctly displayed).
Is this a known bug? Or did I miss something there?

### My code
**In my rails controller**:
def about_us
  render cms_page: '/about_blub'
end

And of course on my admin site I have a page about_blub.

Thanks in advance,
Hendry Iskandar

**Comment by GBH** [comment]
I think it's a bug. https://github.com/comfy/comfortable-mexican-sofa/blob/master/lib/comfortable_mexican_sofa/render_methods.rb#L63 is not selecting proper fragments. It needs to call `page.translate!(locale)` somewhere there.

Feel free to make a PR or I'll deal with this a bit later.

**Comment by hendryiskandar** [comment]
Thanks for the reply Oleg.
I think I would wait until it is fixed.
Let me know when the fix is done.

Have a nice day Sir!

**Comment by bartekv2** [comment]
Is it possible that this bug still exists when trying to render navigation using @cms_page.children.published.each... or <% Comfy::Cms::Site.first.pages.root.children.published.each do |page| %>? I'm getting only the original language version although translation exists...

**Comment by GBH** [comment]
Well, you're grabbing actual page object. You'd need to pull in translated content. So I think this would work:
```
pages.each do |page|
  translated_page = page.translate!
  translated.label
end
```

**Comment by bartekv2** [comment]
It works :) Thank you so much.
