### ISSUE TITLE
Is it possible to add html class for image?

### ISSUE THREAD

**Issue by hendryiskandar** [comfy/comfortable-mexican-sofa#855]
Hallo Oleg,

is it actually possible to add html class for image?
I was imagining like in the following code.
{{ cms:file example, as: image, label: "My Photo", **class: "class-1 class-2 class-3"** }}

Thanks in advance,
Hendry Iskandar

**Comment by GBH** [comment]
No, there's no support for that. Easy solution is to give image a container and style using that:
```
<div class="class-1 class-2 class-3>
  {{cms:file foo, as: image}}
</div>
```

**Comment by hendryiskandar** [comment]
Thanks for the replay Sir...

I have modified the plugin so that it's possible to add html class directly to img tag since there are some html class in Bootstrap that are meant to be placed directly in the img tag (at least as written in the documentation).

1 question, it is OK to modify the plugin to fit my own needs right? Or is it prohibited?

Thanks in advance,
Hendry Iskandar

**Comment by GBH** [comment]
Yeah, feel free to fork and do whatever you need. 👍

**Comment by hendryiskandar** [comment]
Thanks Sir and have a great day! God bless You.

**Comment by robmathews** [comment]
I'd really like to be able to do this. Adding the div is cumbersome.
