### ISSUE TITLE
Preview button is broken

### ISSUE THREAD

**Issue by robmathews** [comfy/comfortable-mexican-sofa#856]
### Expected behavior
You can save your changes after previewing.

### Actual behavior
After you preview a page, the buttons on the bottom (cancel/update) are disabled and the labels are changed to 'false', 'false'
You cannot save your changes after previewing.

### Steps to reproduce
Things that help:

* Choose a page, any page
* Hit 'Preview'
* Note that you cannot save.

### System configuration
**Rails version**: 5.2.1

**CMS version**: 2.0.17

**Ruby version**: 2.5.1p57

**Comment by GBH** [comment]
Closing as I can't replicate the issue. See https://github.com/comfy/comfortable-mexican-sofa/pull/857
