### ISSUE TITLE
going from sass => sassc is a breaking change

### ISSUE THREAD

**Issue by robmathews** [comfy/comfortable-mexican-sofa#859]
*Note:* For general questions and feature requests please leave a message
on Gitter: https://gitter.im/comfy/comfortable-mexican-sofa

### Expected behavior
I'd like to be able to deploy my app. Or, if a breaking change is introduced, have a semantic version number and upgrade notes.

### Actual behavior
It breaks when precompiling assets. Seems to be caused by https://github.com/comfy/comfortable-mexican-sofa/commit/8d8f40f46dd05da2601bf57f65ca4b0b4dfab539

### Steps to reproduce
Things that help:

* have a complicated real life project, not a toy project.
* attempt to deploy.
* get lots of incomprehensible errors precompiling assets from other gems that are also not under my control, like these:
`
SSHKit::Command::Failed: rake exit status: 1
rake stdout: rake aborted!
SassC::SyntaxError: Error: Invalid CSS after "...expression(this": expected expression (e.g. 1px, bold), was ".src = this.src ? t"
        on line 4042 of stdin
>>   _behavior: expression(this.src = this.src ? this.src : this.currentStyle.b
   ----------------------------^
stdin:4042
/mnt/code/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc/engine.rb:49:in `render'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc/rails/compressor.rb:29:in `call'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:28:in `call'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/mnt/code/shared/bundle/ruby/2.5.0/gems/bugsnag-6.9.0/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/mnt/code/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rbenv/versions/2.5.1/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
rake stderr: Nothing written

Tasks: TOP => deploy:assets:precompile
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as ubuntu@172.16.1.129: rake exit status: 1
rake stdout: rake aborted!
SassC::SyntaxError: Error: Invalid CSS after "...expression(this": expected expression (e.g. 1px, bold), was ".src = this.src ? t"
        on line 4042 of stdin
>>   _behavior: expression(this.src = this.src ? this.src : this.currentStyle.b
   ----------------------------^
stdin:4042
/mnt/code/shared/bundle/ruby/2.5.0/gems/sassc-2.0.0/lib/sassc/engine.rb:49:in `render'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sassc-rails-2.0.0/lib/sassc/rails/compressor.rb:29:in `call'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:28:in `call'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/mnt/code/shared/bundle/ruby/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
`
### System configuration
**Rails version**: 5.2.1

**CMS version**: master

**Ruby version**: 2.5.1

**Comment by glebm** [comment]
It is complaining about the following snippet:

```
_behavior: expression(this.src = this.src ? this.src : this.currentStyle)
```

Any idea why you have this in your Sass / CSS?

**Comment by glebm** [comment]
From what I can tell, this seems to be an IE6 hack:

https://github.com/search?q=%22_behavior%3A+expression%28this.src+%3D+this.src+%3F+this.src+%3A+this.currentStyle%22&type=Code

I've reported the libsass issue here: https://github.com/sass/libsass/issues/2796

If you'd really like to use CMS master, perhaps you can fix it on your side (e.g. by dropping IE6 support)?

**Comment by robmathews** [comment]
I probably can. As you might imagine, I stumbled across this in bad circumstances - I pulled the latest branch b/c I needed some other fix, got this one, and suddenly couldn't deploy, all in a hotfix situation on a weekend.

But now that it's not an emergency, maybe I can figure out exactly where this is coming from. And report back which gem is doing it. Or, if it is my code, drop it. We don't need IE6 support anymore ... dropped it a few years ago, so we are not constrained there.

Thanks for reporting the libsass issue.

**Comment by robmathews** [comment]
Oh wait - I see colorbox in there, which we use in the older parts of the app. And, yes, it is coming from the colorbox.sass file, which we pulled in circa 2011.

and that seems to come from https://wordpress.org/plugins/jquery-colorbox/

which when I pull that source, no longer has the expression "_behavior: expression" in it.

So maybe let me experiment with upgrading colorbox? Or tweaking my local CSS? ...

**Comment by glebm** [comment]
Perhaps upgrading it is best, as there's been a few bugfixes according to the changelog https://wordpress.org/plugins/jquery-colorbox/#developers

**Comment by robmathews** [comment]
Oh, it's buggy alright. Which is one of the reasons we happily switched to bootstrap + and bootstrap dialogs a few years back.

I'm just not looking for to upgrading it and discovering all the workarounds that we had to do are now broken. 🤷‍♂️ Oh well.

**Comment by GBH** [comment]
Thank you guys for figuring this out!

**Comment by robmathews** [comment]
Thank you @gleb
