### ISSUE TITLE
Can't view grandchildren pages

### ISSUE THREAD

**Issue by JohnSmall** [comfy/comfortable-mexican-sofa#861]
*Note:* For general questions and feature requests please leave a message
on Gitter: https://gitter.im/comfy/comfortable-mexican-sofa

### Expected behavior
In admin I have pages which are child pages of the home page. I've tried adding child pages to one of those child pages and I should be able to view and edit them by clicking on the little + widget/icon

### Actual behavior
Tell us what happens instead
The '+' icon changes to a '-' but I don't see the sub-tree of pages within the relevant page

### Steps to reproduce
Things that help:
* Describe issue in detail
Create a new site and populate it with the standard cms seeds. Then add a child page to one of the existing child pages. The existing page will then have a '+' to indicate that it's possible to expand the tree and see its children. But clicking on the '+' changes it to a '-' and nothing else happens. I can't see the sub pages.

* Add relevant code snippets.
No code, just using CMS

* Create a failing test case.
Follow the above instructions 

### System configuration
**Rails version**:
Rails 5.2.1

**CMS version**:
2.0.17
**Ruby version**:
ruby 2.5.1p57

**Comment by JohnSmall** [comment]
The problem is line 7 in `cms/pages/toggle_branch.js.erb`

        li.append('<ul class="children sortable pl-md-3"><%= escape_javascript(render partial: "index_branch", collection: @page.children) %></ul>');

is sent to the browser as 

       li.append('<ul class='children sortable pl-md-3'>

Which obviously causes a problem because the single quote gets closed too early. 

But where's the test for this? Normally I'd write a Cucumber scenario since it requires integration between javascript and the backend in response to a click in the right place. 

I thought I'd try some non-automated testing so I tried setting the path directive in my project Gemfile to point to the cloned repo so I could get that line working. But I then got an error when opening CMS admin

    undefined method `base_controller' for #<ComfortableMexicanSofa::Configuration:

Which is a puzzle because I've always been able to set paths to cloned gems before. So now I'm stuck.

I needed the child page feature to work because I want to have a navbar that creates entries with dropdown menus based on the tree structure in CMS. I'm going to scratch that idea and I'll have to make do with hand coding the navbar.

Anyway, I can see exactly where the problem is so I'll have to hand over to @GBH to fix it.

**Comment by JohnSmall** [comment]
Ah, I've found a temporary workaround. If I click to open a sub-tree then nothing happens, but if I reload the page after I've clicked '+' then the sub-tree loads.

**Comment by GBH** [comment]
Thanks for the report. Will check what's going on there.

**Comment by GBH** [comment]
I can't replicate what you're describing. Checked on both Firefox and Chrome. What I'm seeing that's being send to the browser looks more like this:
```
li.append('<ul class="children sortable pl-md-3"><li data-id=\'7\' ...
```
Everything is properly quoted and escaped.

`toggle_branch.js.erb` also has `li.append('<ul class="children sortable pl-md-3">` so I have no idea where single quotes around class come from.

Let's reopen if we can find actual issue and this is something that can be fixed on CMS side.
