### ISSUE TITLE
Overwrite text label in form.text_field

### ISSUE THREAD

**Issue by hendryiskandar** [comfy/comfortable-mexican-sofa#862]
*Note:* For general questions and feature requests please leave a message
on Gitter: https://gitter.im/comfy/comfortable-mexican-sofa

Hello Oleg,

I'm wondering if I can customise the label text in the automatic created label tag in the form.text_field (see the code below)

```
= comfy_form_with model: @bla, url: [:admin, @bla] do |form|
  **= form.text_field :named_id**
```

**Comment by GBH** [comment]
Yeap. Just do 
```
form.text_field :value, bootstrap: {label: {text: "Custom Label"}}
```

It's using https://github.com/comfy/comfy-bootstrap-form so all documentation about how to use is there.
