### ISSUE TITLE
Tag: cms:file as: image does not regard label attribute

### ISSUE THREAD

**Issue by makjaveli** [comfy/comfortable-mexican-sofa#868]
### Expected behavior

{{ cms:file 1, as: image, label: "My Photo" }} the label attribute should set the alt tag to "My Photo" as stated in the tag documentation

### Actual behavior

The generated alt tag is always populated with the file name

### Steps to reproduce

Insert the {{ cms:file 1, as: image, label: "My Photo" }} tag and view the generated HTML

### System configuration
**Rails version**: 5.2.2

**CMS version**: 2.0.17

**Ruby version**: 2.3.1

**Comment by GBH** [comment]
I'll be releasing new version shorty, but it seems like there's no issue with master branch. 

Layout: `{{ cms:file example, as: image, label: "My Photo"}}`
HTML: `<img src='/rails/active_storage/blobs/eyJfcmFpbHMiOns....1020315.jpg' alt='My Photo'/>`
