### ISSUE TITLE
Exports fail with undefined method 'each' for nil:NilClass

### ISSUE THREAD

**Issue by chiubaka** [comfy/comfortable-mexican-sofa#880]
*Note:* For general questions and feature requests please leave a message
on Gitter: https://gitter.im/comfy/comfortable-mexican-sofa

### Expected behavior
Running the export rake task should result in an export

### Actual behavior
```
rake aborted!
NoMethodError: undefined method `each' for nil:NilClass
/Users/dchiu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.18/lib/comfortable_mexican_sofa/seeds.rb:84:in `export!'
/Users/dchiu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.18/lib/tasks/cms_seeds.rake:35:in `block (3 levels) in <main>'
/Users/dchiu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/dchiu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/dchiu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/dchiu/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
```

### Steps to reproduce
Should be able to just run the command.

This [line of code](https://github.com/comfy/comfortable-mexican-sofa/blob/v2.0.18/lib/tasks/cms_seeds.rake#L27) looks suspect. I think there's a typo here and `classes` should be `klasses`, so the classes list is always coming back nil no matter what you pass to the CLI.

### System configuration
**Rails version**:
5.2.2.1

**CMS version**:
2.0.18

**Ruby version**:
2.5.1

**Comment by pablof300** [comment]
Having the same issue.

**Comment by GBH** [comment]
Fixed in https://github.com/comfy/comfortable-mexican-sofa/commit/4aa580065fa6d34dfab170151c3594385208c11e
