### ISSUE TITLE
"Undefined method `purge_later`" error when attaching file to file fragment in Rails 6

### ISSUE THREAD

**Issue by morgant** [comfy/comfortable-mexican-sofa#898]
*Note:* For general questions and feature requests please leave a message
on Gitter: https://gitter.im/comfy/comfortable-mexican-sofa

### Expected behavior

Upload file via page file fragment, pages#update should result in file being attached to fragment without error.

### Actual behavior

Under Ruby 2.6.3 & Rails 6.0.0, during pages#update the following error is generated:

    A NoMethodError occurred in pages#update:
    
    undefined method `purge_later' for # <ActiveStorage::Attached::Many:0x00007f71be809260>

### Steps to reproduce

1) Edit a page with a layout containing a file tag such as:

    {{ cms:file slide_image, namespace: slide, render: false }}

2) Select an image file for the the file field (e.g. slide_image field)

3) Click "Update Page" button

This does not occur if the image is attached inline within a WYSIWYG content fragment.

### System configuration
**Rails version**: 6.0.0

**CMS version**: 2.0.18

**Ruby version**: 2.6.3

**Comment by morgant** [comment]
I'm not sure why this isn't working, the Rails 6 documentation shows that ActiveStorage::Attached::Many should have a `purge_later` method (see https://api.rubyonrails.org/classes/ActiveStorage/Attached/Many.html#method-i-purge_later). If I debug the code I can successfully perform `attachments.first.purge_later`.

**Comment by morgant** [comment]
It seems that the default action for Rails 6 is to replace existing attachments, instead of append, so the `#purge_later` call might not even be required. See https://github.com/rails/rails/pull/36716

**Comment by morgant** [comment]
It appears that the aforementioned change in Rails 6's default action is for #update, #attach retains its append functionality.

That said, Rails 6 did have a change to the implementation of ActiveStorage::Attached::Many#purge & #purge_later: https://github.com/rails/rails/commit/f9a5839083e697f0d5aad6d9304cd5f26e2a7a11.

**Comment by nitsujri** [comment]
@morgant I am unable to attach through the WYSIWYG as you mention above. I get an infinite loop when attaching a file:

https://gist.github.com/nitsujri/7b0a815d1702f159860a9a679f70abb4

It appears to be trying to add and then immediately purge the blob? I'm not 100% sure/understand.

I am running a similar setup:

Ruby 2.6.4
Rails 6.0.0

Let me know if I can help. I have to downgrade my Rails version since we cannot upload images to blog posts/pages

**Comment by morgant** [comment]
@nitsujri Thanks, upon further investigation, I'm getting an infinite loop if I comment out the `purge_later` call. In fact, the `purge_later` works fine on the first iteration and fails on the second.

**Comment by morgant** [comment]
@nitsujri It looks like this may be a bug in Rails 6.0 related to #attach and `after_save` callbacks: https://github.com/rails/rails/issues/37022

**Comment by morgant** [comment]
@nitsujri Changing the `after_save` callbacks in `app/models/comfy/cms/fragment.rb` seems to resolve the issue in my testing. I can't yet explain precisely why and it doesn't fix https://github.com/rails/rails/issues/37022, but I'm curious if it has a positive effect in your environment.

**Comment by morgant** [comment]
@nitsujri This is essentially the same fix as PR #892, but for Comfy::Cms::Fragment as well as Comfy::Cms::File.

**Comment by nitsujri** [comment]
@morgant Ah yep, that worked! 

https://github.com/nitsujri/comfy-activestorage-example/tree/fixed

The example has a fixed branch now working, and I tested it on our actual app which works great too.

Love to see this merged in asap =)

**Comment by morgant** [comment]
Now that PR #892 applies the fix for Comfy::Cms::Fragment as well, this is working for me. Will close when PR #892 is merged.

**Comment by morgant** [comment]
PR #899—a duplicate of PR #892—was merged, so this can be closed.
