### ISSUE TITLE
Link to ComfyArchive add-on in README?

### ISSUE THREAD

**Issue by morgant** [comfy/comfortable-mexican-sofa#903]
We have released a new ComfortableMexicanSofa add-on named [ComfyArchive](https://github.com/DiscoveryMap/comfy-archive), based loosely on ComfyBlog, but allows creating chronological archives out of any page and its children. Would it be appropriate to link to it from the README along with ComfyBlog?

**Comment by GBH** [comment]
@morgant Let's create a section in Wiki under `Addons` section. Would be good idea to add the ComfyBlog there too.

**Comment by morgant** [comment]
@GBH Sounds great. Just on the main wiki page or an additional page? Would you like me to take care of it?

**Comment by GBH** [comment]
@morgant I added "Plugins" section on the main wiki page. Probably a good place?

**Comment by morgant** [comment]
@GBH, thanks again! I've added a link to ComfyArchive there as well.
