### ISSUE TITLE
Passwords cannot be changed by admin users [Bug?]

### ISSUE THREAD

**Issue by ScottyPcGuy-03** [comfy/comfortable-mexican-sofa#913]
Hi guys,

I have been having a devil of a time narrowing this down and I am at my wits end. I recently migrated one of our websites from a chroot on a dedicated server to a VPS, and after changing the paths it seems to work, however I am unable to reset passwords either via email, or via the admin interface.

I tested bcrypt on the rails cli and it successfully creates a hash, so BCrypt appears to be working correctly. 

### Expected behavior
Password change after submitting via admin interface

### Actual behavior
500 error, Logfiles show BCrypt claims the hash is invalid:
`
BCrypt::Errors::InvalidHash (invalid hash):
  app/models/user.rb:118:in 'update!'
  app/controllers/admin/users_controller.rb:43:in 'update'`

### Steps to reproduce
- Login to admin
- Change user password
- Save

### System configuration
**Rails version**:
4.2.3

**CMS version**:
1.12.8

**Ruby version**:
2.3.0

**Comment by GBH** [comment]
Hi @ScottyPcGuy-03 

This gem doesn't actually handle authentication. It simply hooks in into what you have on the app, Devise or whatever else. `User` model is specific to your app.

You gotta google around, but it might be something with `bcrypt` not being able to read a hash that is saved on the database.
